// AgentsAddIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M11.5 6a4.5 4.5 0 1 1 0 9 4.5 4.5 0 0 1 0-9m-4-4a.5.5 0 0 1 0 1H5.1a.5.5 0 0 0-.43.25l-2.6 4.5a.5.5 0 0 0 0 .5l2.5 4.34a.83.83 0 0 0 1.5-.17l.14-.41q.19.67.54 1.26a1.83 1.83 0 0 1-3.04-.18L1.2 8.75a1.5 1.5 0 0 1 0-1.5l2.6-4.5A1.5 1.5 0 0 1 5.1 2zm4 6a.5.5 0 0 0-.5.5V10H9.5a.5.5 0 0 0 0 1H11v1.5a.5.5 0 1 0 1 0V11h1.5a.5.5 0 0 0 0-1H12V8.5a.5.5 0 0 0-.5-.5m-.79-6c.65 0 1.25.35 1.58.91l1.5 2.59q-.68-.3-1.4-.43l-.97-1.66a.83.83 0 0 0-1.5.17l-.59 1.86q-.7.3-1.3.79l.94-2.95C9.2 2.52 9.9 2 10.7 2"/></>),
  20: (<><path d="M15.5 10a4.5 4.5 0 1 1 0 9 4.5 4.5 0 0 1 0-9m-6-8a.5.5 0 1 1 0 1H6.69q-.41.01-.64.35L2.11 9.6a.8.8 0 0 0 0 .8l3.87 6.13a1 1 0 0 0 .85.47h.02a1 1 0 0 0 .96-.74l3.4-12.78A2 2 0 0 1 13.16 2h.02a2 2 0 0 1 1.7.93l3.86 6.14c.23.35.3.77.25 1.17a6 6 0 0 0-1.15-.72l-3.81-6.05a1 1 0 0 0-.85-.47h-.02a1 1 0 0 0-.97.74l-3.4 12.78A2 2 0 0 1 6.85 18h-.02a2 2 0 0 1-1.7-.93l-3.86-6.14a1.8 1.8 0 0 1 0-1.86L5.2 2.82C5.53 2.3 6.09 2 6.69 2zm6 10a.5.5 0 0 0-.5.5V14h-1.5a.5.5 0 0 0 0 1H15v1.5a.5.5 0 0 0 1 0V15h1.5a.5.5 0 1 0 0-1H16v-1.5a.5.5 0 0 0-.5-.5"/></>),
  24: (<><path d="M18.5 12a5.5 5.5 0 1 1 0 11 5.5 5.5 0 0 1 0-11m0 2a.5.5 0 0 0-.5.5V17h-2.5a.5.5 0 0 0 0 1H18v2.5a.5.5 0 0 0 1 0V18h2.5a.5.5 0 0 0 0-1H19v-2.5a.5.5 0 0 0-.5-.5M11.25 3a.75.75 0 0 1 0 1.5H8.12a.8.8 0 0 0-.65.38l-3.9 6.77a.8.8 0 0 0 0 .73L7.16 19a.95.95 0 0 0 1.74-.17l4.5-14.12a2.47 2.47 0 0 1 4.49-.48l3.82 6.64q.3.54.3 1.16a7 7 0 0 0-1.83-.82L16.59 5a.97.97 0 0 0-1.76.18L10.34 19.3a2.45 2.45 0 0 1-4.48.43L2.24 13.1a2.3 2.3 0 0 1 .03-2.2l3.9-6.77C6.57 3.43 7.3 3 8.12 3z"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function AgentsAddIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
