// ArrowSprintIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
};
const C = {
  16: (<><path d="M8 4a3.5 3.5 0 0 1 3.16 5H10q.48-.64.5-1.5A2.5 2.5 0 1 0 8 10h5.3l-.65-.65a.5.5 0 0 1 .7-.7l1.5 1.5c.2.2.2.5 0 .7l-1.5 1.5a.5.5 0 0 1-.7-.7l.64-.65H8a3.5 3.5 0 1 1 0-7m-3.74 6q.38.57.91 1H2.5a.5.5 0 0 1 0-1z"/></>),
  20: (<><path d="M10 6a3.5 3.5 0 1 0 0 7h7.3l-1.15-1.15a.5.5 0 0 1 .7-.7l2 2c.2.2.2.5 0 .7l-2 2a.5.5 0 0 1-.7-.7L17.29 14H10a4.5 4.5 0 1 1 3.74-2h-1.29A3.49 3.49 0 0 0 10 6m-7.5 7h3.26q.46.58 1.08 1H2.5a.5.5 0 0 1 0-1"/></>),
};
const SIZES = [16, 20];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ArrowSprintIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
