// ArrowCircleDownDoubleIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="m9 12.2-1.65 1.65a.5.5 0 0 1-.7 0L5 12.21a.5.5 0 1 1 .7-.71l.8.8V6.5a.5.5 0 0 1 1 0v5.8l.8-.8a.5.5 0 1 1 .7.7m1 5.8a8 8 0 1 0 0-16 8 8 0 0 0 0 16m7-8a7 7 0 1 1-14 0 7 7 0 0 1 14 0m-3.65 3.85L15 12.21a.5.5 0 1 0-.7-.71l-.8.8V6.5a.5.5 0 0 0-1 0v5.8l-.8-.8a.5.5 0 1 0-.7.7l1.65 1.65c.2.2.5.2.7 0"/></>),
  24: (<><path d="m11.25 13.75-.08-.07a.75.75 0 0 0-.98.07l-.69.69V7.65A.75.75 0 0 0 8.74 7h-.1a.75.75 0 0 0-.65.75v6.7l-.69-.7-.08-.07a.75.75 0 0 0-.98 1.13l1.97 1.97.08.07c.3.22.71.2.98-.07l1.97-1.97.07-.08c.22-.3.2-.71-.07-.98M2 12a10 10 0 1 0 20 0 10 10 0 0 0-20 0m18.5 0a8.5 8.5 0 1 1-17 0 8.5 8.5 0 0 1 17 0m-2.75 1.75-.08-.07a.75.75 0 0 0-.98.07l-.7.69v-6.8a.75.75 0 0 0-.74-.64h-.1a.75.75 0 0 0-.65.75v6.7l-.69-.7-.08-.07a.75.75 0 0 0-.98 1.13l1.97 1.97.08.07c.3.22.71.2.98-.07l1.97-1.97.07-.08c.22-.3.2-.71-.07-.98"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ArrowCircleDownDoubleIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
