// ArrowForwardDownLightningIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M13.61 4.32 16.3 7h-4.55C8.8 6.9 7 5.27 7 3a.5.5 0 0 0-1 0v.2C6.12 6.03 8.48 8 12 8h4.3l-2.69 2.68-.06.07a.5.5 0 0 0 .77.64l3.55-3.55.05-.07.04-.08.02-.06.02-.09v-.06.02l-.01-.1v-.03l-.03-.06-.03-.06-.05-.07-3.56-3.57-.07-.06a.5.5 0 0 0-.64.77M2.51 16h1.74l-.59 2.36c-.12.48.46.83.83.49l4.87-4.55a.75.75 0 0 0-.51-1.3h-1.1l.78-2.34a.5.5 0 0 0-.47-.66H4.59a.5.5 0 0 0-.47.3l-2.08 5c-.14.34.1.7.46.7"/></>),
  24: (<><path d="m19.59 9.5-2.97-2.96a.75.75 0 0 1 .98-1.14l.08.08 4.25 4.24c.26.27.29.68.07.98l-.07.08-4.25 4.24a.75.75 0 0 1-1.13-.97l.07-.09L19.6 11h-5.7a7.75 7.75 0 0 1-7.74-7.5v-.25a.75.75 0 1 1 1.5 0 6.25 6.25 0 0 0 6.02 6.25h5.92M5.32 12h4.83a.5.5 0 0 1 .43.75L8.75 16h1.5c.64 0 .99.76.56 1.24l-4.82 5.51c-.5.58-1.45.09-1.26-.66L5.5 19h-3a.5.5 0 0 1-.45-.71l2.82-6a.5.5 0 0 1 .45-.29"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ArrowForwardDownLightningIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
