// ArrowUpIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
  48: '0 0 48 48',
};
const C = {
  16: (<><path d="M7.5 13.5a.5.5 0 0 0 1 0V3.8l3.63 4.03a.5.5 0 0 0 .74-.66l-4.5-5a.5.5 0 0 0-.74 0l-4.5 5a.5.5 0 0 0 .74.66L7.5 3.8z"/></>),
  20: (<><path d="M3.13 9.16a.5.5 0 1 0 .74.68L9.5 3.67V17.5a.5.5 0 1 0 1 0V3.67l5.63 6.17a.5.5 0 0 0 .74-.68l-6.32-6.92a.75.75 0 0 0-1.1 0z"/></>),
  24: (<><path d="M4.2 10.73a.75.75 0 0 0 1.1 1.04l5.95-6.25v14.73a.75.75 0 0 0 1.5 0V5.52l5.95 6.25a.75.75 0 0 0 1.1-1.04l-7.08-7.42a1 1 0 0 0-1.44 0z"/></>),
  28: (<><path d="M4.21 12.73a.75.75 0 1 0 1.08 1.04l7.96-8.27v18.75a.75.75 0 1 0 1.5 0V5.5l7.96 8.27a.75.75 0 0 0 1.08-1.04L14.72 3.3a1 1 0 0 0-1.44 0z"/></>),
  48: (<><path d="M24 44c-.69 0-1.25-.56-1.25-1.25V10.3l-12.6 12.83a1.25 1.25 0 1 1-1.8-1.76L23.1 6.4l.02-.03a1.25 1.25 0 0 1 1.8.04l14.72 14.97a1.25 1.25 0 1 1-1.78 1.76L25.25 10.3v32.45c0 .69-.56 1.25-1.25 1.25"/></>),
};
const SIZES = [16, 20, 24, 28, 48];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ArrowUpIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
