// ArrowSyncCheckmarkIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M11.41 3.64a.5.5 0 0 0 0-.71L9.3.8a.5.5 0 0 0-.7.7l1 1a7.5 7.5 0 0 0-4.08 13.5.5.5 0 0 0 .6-.8A6.5 6.5 0 0 1 11.4 3.66zM8.6 16.36l.01-.01q.61.14 1.27.15h-.01.07A6.5 6.5 0 0 0 13.9 4.8a.5.5 0 1 1 .6-.8q.44.3.81.7a7.5 7.5 0 0 1-4.88 12.79l1 1a.5.5 0 1 1-.71.7l-2.12-2.12a.5.5 0 0 1 0-.7m3.76-8.21c.2.2.2.5 0 .7l-3 3a.5.5 0 0 1-.7 0l-1.5-1.5a.5.5 0 0 1 .7-.7L9 10.79l2.65-2.64c.2-.2.5-.2.7 0M5 10a5 5 0 1 1 10 0 5 5 0 0 1-10 0m5-4a4 4 0 1 0 0 8 4 4 0 0 0 0-8"/></>),
  24: (<><path d="M16.4 6.23a.75.75 0 1 1 .9-1.2 8.74 8.74 0 0 1-4.58 15.7l.75.74.07.08a.75.75 0 0 1-1.13.98l-2-2-.07-.08a.75.75 0 0 1 .07-.98l.33-.33a7 7 0 0 0 2.06.06 7.25 7.25 0 0 0 3.6-12.97m-5.87-3.7a.75.75 0 1 1 1.06-1.06l2 2c.3.3.3.77 0 1.06l-.33.33a7 7 0 0 0-2.06-.06A7.25 7.25 0 0 0 7.4 17.6a.75.75 0 0 1-.96 1.15 8.75 8.75 0 0 1 4.85-15.47zm4.5 8.5a.75.75 0 1 0-1.06-1.06L11 12.94l-.97-.97a.75.75 0 1 0-1.06 1.06l1.5 1.5c.3.3.77.3 1.06 0zM12 18a6 6 0 1 0 0-12 6 6 0 0 0 0 12m0-1.5a4.5 4.5 0 1 1 0-9 4.5 4.5 0 0 1 0 9"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ArrowSyncCheckmarkIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
