// ArrowUndoIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
  48: '0 0 48 48',
};
const C = {
  16: (<><path d="M3 2.5a.5.5 0 0 1 1 0v3.84l3.17-3.17a4 4 0 0 1 5.66 5.66L7.8 13.85a.5.5 0 0 1-.7-.7l5.02-5.03a3 3 0 1 0-4.24-4.24L4.76 7H8.5a.5.5 0 0 1 0 1H3.6a.6.6 0 0 1-.6-.6z"/></>),
  20: (<><path d="M5 2.5a.5.5 0 0 0-1 0v4.9c0 .33.27.6.6.6h4.9a.5.5 0 0 0 0-1H5.9l3.48-3.02a4 4 0 0 1 5.25 6.04l-8.17 7.1a.5.5 0 0 0 .65.76l8.17-7.1a5 5 0 0 0-6.56-7.55L5 6.46z"/></>),
  24: (<><path d="M4.75 2c.38 0 .7.28.74.65l.01.1v5.69l4.57-4.56a6.4 6.4 0 0 1 8.88-.18l.19.18a6.4 6.4 0 0 1 0 9.06l-8.85 8.84a.75.75 0 0 1-1.06-1.06l8.85-8.84a4.9 4.9 0 0 0-6.77-7.1l-.18.16L6.56 9.5h5.69c.38 0 .7.28.74.65l.01.1c0 .38-.28.7-.65.74l-.1.01h-7.5a.75.75 0 0 1-.74-.65l-.01-.1v-7.5c0-.41.34-.75.75-.75"/></>),
  28: (<><path d="m7.56 10.5 5.34-5.35a5.63 5.63 0 0 1 7.95 7.95L9.22 24.72a.75.75 0 0 0 1.06 1.06l11.63-11.62A7.12 7.12 0 1 0 11.84 4.1L6.5 9.44V2.75a.75.75 0 0 0-1.5 0v8.5a.75.75 0 0 0 .75.75h8.5a.75.75 0 0 0 0-1.5z"/></>),
  48: (<><path d="M35.8 9.84c-4.18-4.6-11.3-4.5-15.86.67l-.02.02-8.56 8.96h12.38a1.25 1.25 0 0 1 0 2.5H8.2c-.7 0-1.25-.56-1.25-1.25V5.27a1.25 1.25 0 0 1 2.5 0v12.6l8.63-9.03c5.45-6.18 14.3-6.48 19.57-.68 5.24 5.78 3.62 13.32-.02 17.2l-8.99 9.18-8.75 8.84-.26.25a1.25 1.25 0 1 1-1.76-1.76l.24-.25 8.75-8.83 8.96-9.15a10.2 10.2 0 0 0-.02-13.8"/></>),
};
const SIZES = [16, 20, 24, 28, 48];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ArrowUndoIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
