// ArrowCircleRightIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
  48: '0 0 48 48',
};
const C = {
  16: (<><path d="m8.85 10.85 2.5-2.5a.5.5 0 0 0 0-.7l-2.5-2.5a.5.5 0 1 0-.7.7L9.79 7.5H5a.5.5 0 0 0 0 1h4.8l-1.65 1.65a.5.5 0 0 0 .7.7M15 8A7 7 0 1 1 1 8a7 7 0 0 1 14 0m-7 6A6 6 0 1 0 8 2a6 6 0 0 0 0 12"/></>),
  20: (<><path d="m10.85 13.35 3-3a.5.5 0 0 0 0-.7l-3-3a.5.5 0 0 0-.7.7l2.14 2.15H6.5a.5.5 0 0 0 0 1h5.8l-2.15 2.15a.5.5 0 0 0 .7.7M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0m-8 7a7 7 0 1 0 0-14 7 7 0 0 0 0 14"/></>),
  24: (<><path d="M12 2a10 10 0 1 1 0 20 10 10 0 0 1 0-20m0 1.5a8.5 8.5 0 1 0 0 17 8.5 8.5 0 0 0 0-17m-.35 4.05.07-.08a.75.75 0 0 1 .98-.07l.08.07 4 4c.27.27.3.68.07.98l-.07.08-4 4a.75.75 0 0 1-1.13-.98l.07-.08 2.72-2.72H7.75a.75.75 0 0 1-.74-.65L7 12c0-.38.28-.7.65-.74l.1-.01h6.69l-2.72-2.72a.75.75 0 0 1-.07-.98l.07-.08z"/></>),
  28: (<><path d="M14.22 8.97c-.3.3-.3.77 0 1.06l3.22 3.22H8.75a.75.75 0 0 0 0 1.5h8.69l-3.22 3.22a.75.75 0 1 0 1.06 1.06l4.5-4.5c.3-.3.3-.77 0-1.06l-4.5-4.5a.75.75 0 0 0-1.06 0M14 2a12 12 0 1 0 0 24 12 12 0 0 0 0-24M3.5 14a10.5 10.5 0 1 1 21 0 10.5 10.5 0 0 1-21 0"/></>),
  48: (<><path d="M23.87 15.37a1.25 1.25 0 0 0 0 1.76l5.61 5.62H15.25a1.25 1.25 0 1 0 0 2.5h14.23l-5.61 5.62a1.25 1.25 0 0 0 1.76 1.76l7.75-7.75c.5-.48.5-1.28 0-1.76l-7.75-7.75a1.25 1.25 0 0 0-1.76 0M24 4a20 20 0 1 0 0 40 20 20 0 0 0 0-40M6.5 24a17.5 17.5 0 1 1 35 0 17.5 17.5 0 0 1-35 0"/></>),
};
const SIZES = [16, 20, 24, 28, 48];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ArrowCircleRightIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
