// ArrowStepInLeftIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
};
const C = {
  16: (<><path d="M7.7 8.5h6.8a.5.5 0 0 0 0-1H7.7l2.15-2.15a.5.5 0 0 0-.7-.7l-3 3a.5.5 0 0 0 0 .7l3 3a.5.5 0 0 0 .7-.7zM1 8a2 2 0 1 1 4 0 2 2 0 0 1-4 0m1 0a1 1 0 1 0 2 0 1 1 0 0 0-2 0"/></>),
  20: (<><path d="M5 10a1 1 0 1 0-2 0 1 1 0 0 0 2 0M4 8a2 2 0 1 1 0 4 2 2 0 0 1 0-4m14 2a.5.5 0 0 1-.5.5H9.7l3.15 3.15a.5.5 0 0 1-.7.7l-4-4a.5.5 0 0 1 0-.7l4-4a.5.5 0 0 1 .7.7L9.71 9.5h7.79c.28 0 .5.22.5.5"/></>),
  24: (<><path d="M15.3 16.23a.75.75 0 0 1-1.1 1.04l-4.5-4.75a.75.75 0 0 1 0-1.04l4.5-4.75a.75.75 0 0 1 1.1 1.04L12 11.25h9.25a.75.75 0 0 1 0 1.5h-9.26zM2 12a3 3 0 1 1 6 0 3 3 0 0 1-6 0m1.5 0a1.5 1.5 0 1 0 3 0 1.5 1.5 0 0 0-3 0"/></>),
  28: (<><path d="M18.3 19.77a.75.75 0 0 0-.03-1.06l-4.15-3.96h11.13a.75.75 0 0 0 0-1.5H14.12l4.15-3.96a.75.75 0 0 0-1.04-1.08l-5.5 5.25a.75.75 0 0 0 0 1.08l5.5 5.25c.3.29.78.28 1.06-.02M6 10a4 4 0 1 0 0 8 4 4 0 0 0 0-8m0 1.5a2.5 2.5 0 1 1 0 5 2.5 2.5 0 0 1 0-5"/></>),
};
const SIZES = [16, 20, 24, 28];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ArrowStepInLeftIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
