// ArrowMinimizeTopLeftBottomRightIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
};
const C = {
  16: (<><path d="M12.5 9a.5.5 0 0 1 0 1h-1.8l3.15 3.15a.5.5 0 0 1-.7.7L10 10.71v1.79a.5.5 0 1 1-1 0V9.6c0-.33.27-.6.6-.6zM2.15 2.15c.2-.2.5-.2.7 0L6 5.29V3.5a.5.5 0 1 1 1 0v2.9a.6.6 0 0 1-.6.6H3.5a.5.5 0 0 1 0-1h1.8L2.14 2.85a.5.5 0 0 1 0-.7"/></>),
  20: (<><path d="M16.5 11a.5.5 0 0 1 0 1h-3.8l5.15 5.15a.5.5 0 0 1-.7.7L12 12.71v3.79a.5.5 0 1 1-1 0v-5c0-.28.22-.5.5-.5zM2.15 2.15c.2-.2.5-.2.7 0L8 7.29V3.5a.5.5 0 1 1 1 0v5a.5.5 0 0 1-.5.5h-5a.5.5 0 0 1 0-1h3.8L2.14 2.85a.5.5 0 0 1 0-.7"/></>),
  24: (<><path d="M21.25 13a.75.75 0 0 1 0 1.5h-5.69l6.22 6.22a.75.75 0 1 1-1.06 1.06l-6.22-6.22v5.69a.75.75 0 0 1-1.5 0v-7.5c0-.41.34-.75.75-.75zm-11-11c.41 0 .75.34.75.75v7.5c0 .41-.34.75-.75.75h-7.5a.75.75 0 0 1 0-1.5h5.69L2.22 3.28a.75.75 0 1 1 1.06-1.06L9.5 8.44V2.75c0-.41.34-.75.75-.75"/></>),
  28: (<><path d="M23.75 15h.1c.37.06.65.37.65.75v.1a.75.75 0 0 1-.75.65h-6.19l7.97 7.97.07.08a.75.75 0 0 1-1.13.98l-7.97-7.97v6.29a.75.75 0 0 1-1.5-.1v-8.1a.75.75 0 0 1 .75-.65zM2.47 2.47c.3-.3.77-.3 1.06 0l7.97 7.97V4.15a.75.75 0 0 1 1.5.1v8.1a.75.75 0 0 1-.75.65h-8.1a.75.75 0 0 1-.65-.75v-.1a.75.75 0 0 1 .75-.65h6.19L2.47 3.53l-.07-.08a.75.75 0 0 1 .07-.98"/></>),
};
const SIZES = [16, 20, 24, 28];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ArrowMinimizeTopLeftBottomRightIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
