// BatteryWarningIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M3.6 9.55a1 1 0 0 1 1.8 0l3.5 7A1 1 0 0 1 8 18H1a1 1 0 0 1-.9-1.45zM4.5 16a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1M16 5a3 3 0 0 1 3 3 1 1 0 0 1 1 1v2a1 1 0 0 1-1 1 3 3 0 0 1-3 3H9.24l-.5-1H16a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2H3a2 2 0 0 0-2 2v4q0 .23.05.44L.47 13.6A3 3 0 0 1 0 12V8a3 3 0 0 1 3-3zM4.5 11a.5.5 0 0 0-.5.5v3a.5.5 0 1 0 1 0v-3a.5.5 0 0 0-.5-.5"/></>),
  24: (<><path d="M8.24 11.2q.36.2.56.56l4 7A1.5 1.5 0 0 1 11.5 21H3.5a1.5 1.5 0 0 1-1.3-2.25l4-7a1.5 1.5 0 0 1 2.05-.55M7.5 18a.5.5 0 1 0 0 1 .5.5 0 0 0 0-1M17 6a3 3 0 0 1 3 3v1h1a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1h-1v1a3 3 0 0 1-3 3h-3.47l-.86-1.5H17c.78 0 1.42-.6 1.5-1.36V9c0-.78-.6-1.42-1.36-1.5H5c-.78 0-1.42.6-1.5 1.36v5.59l-1.14 1.98A3 3 0 0 1 2 15V9a3 3 0 0 1 3-3zm-9.5 7a.5.5 0 0 0-.5.41v3.18a.5.5 0 0 0 .99 0v-3.18a.5.5 0 0 0-.5-.41"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function BatteryWarningIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
