// BeakerAddIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M14 3a.5.5 0 0 1 0 1h-1v4.68q0 .27.04.52-.5.13-.95.35a5 5 0 0 1-.09-.87V4H8v4.69a4.5 4.5 0 0 1-.54 2.13L6.82 12H9.6q-.24.48-.4 1H6.29l-1.22 2.26a.5.5 0 0 0 .44.74h3.7q.15.52.4 1H5.5a1.5 1.5 0 0 1-1.32-2.21l2.4-4.44a3.5 3.5 0 0 0 .41-1.66V4H6a.5.5 0 0 1 0-1zm5 11.5a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0m-4-2a.5.5 0 0 0-1 0V14h-1.5a.5.5 0 0 0 0 1H14v1.5a.5.5 0 0 0 1 0V15h1.5a.5.5 0 0 0 0-1H15z"/></>),
  24: (<><path d="M8 4.5h1v6.24q0 .57-.27 1.07l-3.59 6.6A1.75 1.75 0 0 0 6.68 21h5.34q-.45-.7-.7-1.5H6.67a.25.25 0 0 1-.22-.37l1.97-3.63h2.88q.26-.8.71-1.5H9.25l.8-1.47q.45-.84.45-1.8V4.5h3v6.24q0 .74.28 1.43.62-.44 1.34-.72a2 2 0 0 1-.12-.71V4.5h1A.75.75 0 0 0 16 3H8a.75.75 0 0 0 0 1.5m9.5 7.5a5.5 5.5 0 1 1 0 11 5.5 5.5 0 0 1 0-11m.5 8.5V18h2.5a.5.5 0 1 0 0-1H18v-2.5a.5.5 0 1 0-1 0V17h-2.5a.5.5 0 0 0 0 1H17v2.5a.5.5 0 1 0 1 0"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function BeakerAddIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
