// BluetoothDisabledIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="m13.5 14.2 3.65 3.65a.5.5 0 0 0 .7-.7l-15-15a.5.5 0 1 0-.7.7L9 9.71v.06l-3.83 3.35a.5.5 0 0 0 .66.76L9 11.1v6.4a.5.5 0 0 0 .85.35zm.33-7.32-2.58 2.25-.7-.7 2.22-1.95L10 3.7v4.17l-1-1V2.5a.5.5 0 0 1 .85-.35l4 4a.5.5 0 0 1-.02.73M10 11.1l2.77 2.42L10 16.3z"/></>),
  24: (<><path d="m16.5 17.56 4.22 4.22a.75.75 0 0 0 1.06-1.06L3.28 2.22a.75.75 0 1 0-1.06 1.06l8.56 8.56-4.52 3.84a.75.75 0 1 0 .98 1.14l3.76-3.2v7.63a.75.75 0 0 0 1.28.53zm-3.6-3.6 2.54 2.54-2.94 2.94v-5.82zm4.34-5.64-3.1 2.64-1.07-1.07 2.57-2.18-3.14-3.15v4.76L11 7.82V2.75a.75.75 0 0 1 1.28-.53l5 5a.75.75 0 0 1-.04 1.1"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function BluetoothDisabledIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
