// BoardSplitIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
  48: '0 0 48 48',
};
const C = {
  16: (<><path d="M2 4.5A2.5 2.5 0 0 1 4.5 2h7A2.5 2.5 0 0 1 14 4.5v7a2.5 2.5 0 0 1-2.5 2.5h-7A2.5 2.5 0 0 1 2 11.5zM4.5 3C3.67 3 3 3.67 3 4.5V7h6V3zM3 8v3.5c0 .83.67 1.5 1.5 1.5H9V8zm7 1h3V7h-3zm3 1h-3v3h1.5c.83 0 1.5-.67 1.5-1.5zm0-5.5c0-.83-.67-1.5-1.5-1.5H10v3h3z"/></>),
  20: (<><path d="M3 6a3 3 0 0 1 3-3h8a3 3 0 0 1 3 3v8a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3zm1 4v4c0 1.1.9 2 2 2h5v-6zm7-1V4H6a2 2 0 0 0-2 2v3zm1 7h2a2 2 0 0 0 2-2v-1h-4zm4-9V6a2 2 0 0 0-2-2h-2v3zm0 1h-4v4h4z"/></>),
  24: (<><path d="M3 6.25C3 4.45 4.46 3 6.25 3h11.5C19.55 3 21 4.46 21 6.25v11.5c0 1.8-1.46 3.25-3.25 3.25H6.25A3.25 3.25 0 0 1 3 17.75zm1.5 6.25v5.25c0 .97.78 1.75 1.75 1.75H14v-7zM14 11V4.5H6.25c-.97 0-1.75.78-1.75 1.75V11zm5.5-1.5h-4v5h4zm0 6.5h-4v3.5h2.25c.97 0 1.75-.78 1.75-1.75zm0-8V6.25c0-.97-.78-1.75-1.75-1.75H15.5V8z"/></>),
  28: (<><path d="M3 6.75A3.75 3.75 0 0 1 6.75 3h14.5A3.75 3.75 0 0 1 25 6.75v14.5A3.75 3.75 0 0 1 21.25 25H6.75A3.75 3.75 0 0 1 3 21.25zm1.5 7.75v6.75c0 1.24 1 2.25 2.25 2.25H16v-9zM16 13V4.5H6.75c-1.24 0-2.25 1-2.25 2.25V13zm5.25 10.5c1.24 0 2.25-1 2.25-2.25V18h-6v5.5zm2.25-7v-5h-6v5zm-6-12V10h6V6.75c0-1.24-1-2.25-2.25-2.25z"/></>),
  48: (<><path d="M6 11.25C6 8.35 8.35 6 11.25 6h25.5C39.65 6 42 8.35 42 11.25v25.5c0 2.9-2.35 5.25-5.25 5.25h-25.5A5.25 5.25 0 0 1 6 36.75zM39.5 29v-9.5h-10V29zm-10 2.5v8h7.25a2.75 2.75 0 0 0 2.75-2.75V31.5zm-2.5-6H8.5v11.25a2.75 2.75 0 0 0 2.75 2.75H27zm0-2.5V8.5H11.25a2.75 2.75 0 0 0-2.75 2.75V23zm12.5-6v-5.75a2.75 2.75 0 0 0-2.75-2.75H29.5V17z"/></>),
};
const SIZES = [16, 20, 24, 28, 48];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function BoardSplitIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
