// BookmarkMultipleIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
  48: '0 0 48 48',
};
const C = {
  16: (<><path d="M4.65 2c.3-.6.91-1 1.62-1h4.63A3.1 3.1 0 0 1 14 4.1v7.37c0 .7-.4 1.31-1 1.61V4.1A2.1 2.1 0 0 0 10.9 2zm.15 1C3.8 3 3 3.8 3 4.8v9.7a.5.5 0 0 0 .72.45l3.78-1.9 3.78 1.9a.5.5 0 0 0 .72-.45V4.8c0-1-.8-1.8-1.8-1.8zM4 4.8c0-.44.36-.8.8-.8h5.4c.44 0 .8.36.8.8v8.89l-3.28-1.64a.5.5 0 0 0-.44 0L4 13.7z"/></>),
  20: (<><path d="M6.27 3A2 2 0 0 1 8 2h4.5A3.5 3.5 0 0 1 16 5.5v10a.5.5 0 0 1-.78.42l-.22-.15V5.5A2.5 2.5 0 0 0 12.5 3zM6 4a2 2 0 0 0-2 2v11.5a.5.5 0 0 0 .78.42L9 15.1l4.22 2.82a.5.5 0 0 0 .78-.42V6a2 2 0 0 0-2-2zM5 6a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v10.57l-3.72-2.49a.5.5 0 0 0-.56 0L5 16.57z"/></>),
  24: (<><path d="M4 6.75C4 5.5 5 4.5 6.25 4.5h9c1.24 0 2.25 1 2.25 2.25v14.5a.75.75 0 0 1-1.13.65l-5.62-3.28-5.62 3.28A.75.75 0 0 1 4 21.25zM6.25 6a.75.75 0 0 0-.75.75v13.2l4.87-2.85a.8.8 0 0 1 .76 0L16 19.94V6.74a.75.75 0 0 0-.75-.74zm9-4A4.75 4.75 0 0 1 20 6.75v11.87a.75.75 0 0 1-1.5 0V6.75c0-1.8-1.46-3.25-3.25-3.25H6.64s.11-.56.8-1.08C8 2 8.6 2 8.6 2z"/></>),
  28: (<><path d="M8.4 3.5A3 3 0 0 1 11 2h6.25A5.75 5.75 0 0 1 23 7.75V20a3 3 0 0 1-1.5 2.6V7.75c0-2.35-1.9-4.25-4.25-4.25zM8 5a3 3 0 0 0-3 3v17.25a.75.75 0 0 0 1.17.62l6.33-4.22 6.33 4.22a.75.75 0 0 0 1.17-.62V8a3 3 0 0 0-3-3zM6.5 8c0-.83.67-1.5 1.5-1.5h9c.83 0 1.5.67 1.5 1.5v15.85l-5.58-3.72a.8.8 0 0 0-.84 0L6.5 23.85z"/></>),
  48: (<><path d="M14.67 6.5A5 5 0 0 1 19 4h9.75C34.4 4 39 8.59 39 14.25V34a5 5 0 0 1-2.5 4.33V14.25a7.75 7.75 0 0 0-7.75-7.75zM14 9a5 5 0 0 0-5 5v28.75a1.25 1.25 0 0 0 1.94 1.04l10.56-7.04 10.56 7.04A1.25 1.25 0 0 0 34 42.75V14a5 5 0 0 0-5-5zm-2.5 5a2.5 2.5 0 0 1 2.5-2.5h15a2.5 2.5 0 0 1 2.5 2.5v26.41l-9.3-6.2a1.3 1.3 0 0 0-1.4 0l-9.3 6.2z"/></>),
};
const SIZES = [16, 20, 24, 28, 48];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function BookmarkMultipleIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
