// BookNumberIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M5.5 5.5c0 .27.22.5.5.5h.6l-.22 1H5.5a.5.5 0 0 0 0 1h.66l-.14.64a.5.5 0 0 0 .97.21L7.2 8h.96l-.14.64a.5.5 0 1 0 .97.22l.2-.86H10a.5.5 0 0 0 0-1h-.6l.22-1h.88a.5.5 0 0 0 0-1h-.65l.14-.64A.5.5 0 0 0 9 4.14L8.82 5h-.97l.14-.64A.5.5 0 0 0 7 4.14L6.82 5H6a.5.5 0 0 0-.5.5M8.37 7H7.4l.23-1h.97zM5 1h6a2 2 0 0 1 2 2v9.5a.5.5 0 0 1-.5.5H4a1 1 0 0 0 1 1h7.5a.5.5 0 0 1 0 1H5a2 2 0 0 1-2-2V3c0-1.1.9-2 2-2M4 3v9h8V3a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1"/></>),
  20: (<><path d="M7 7.5c0-.27.22-.5.5-.5h1.29l.22-1.1a.5.5 0 0 1 .98.2l-.18.9h.98l.22-1.1a.5.5 0 0 1 .98.2l-.18.9h.94a.5.5 0 0 1 0 1h-1.14l-.2 1h1.1a.5.5 0 1 1 0 1h-1.3L11 11.1a.5.5 0 0 1-.98-.2l.18-.9h-.98l-.22 1.1a.5.5 0 1 1-.98-.2l.18-.9h-.94a.5.5 0 0 1 0-1H8.4l.2-1H7.5a.5.5 0 0 1-.5-.5M10.4 9l.2-1H9.6l-.2 1zM6 2h8a2 2 0 0 1 2 2v11.5a.5.5 0 0 1-.5.5H5a1 1 0 0 0 1 1h9.5a.5.5 0 0 1 0 1H6a2 2 0 0 1-2-2V4c0-1.1.9-2 2-2M5 15h10V4a1 1 0 0 0-1-1H6a1 1 0 0 0-1 1z"/></>),
  24: (<><path d="m11.02 7.57-.22.91H9.63a.75.75 0 0 0-.65.75v.1c.06.37.37.65.75.65h.7l-.38 1.59h-.9a.75.75 0 0 0-.65.75v.1c.06.36.37.65.75.65h.43l-.12.5-.02.1c-.04.37.2.72.57.81l.1.02c.36.04.71-.2.8-.57l.21-.86h1.54l-.12.51-.01.1c-.04.37.2.72.58.8l.1.02c.37.03.71-.21.8-.58l.2-.85h.93l.1-.01a.75.75 0 0 0 .65-.74v-.1a.75.75 0 0 0-.75-.65h-.6l.37-1.59h.82a.75.75 0 0 0 .65-.75v-.1a.75.75 0 0 0-.75-.65h-.38l.13-.56.02-.1a.75.75 0 0 0-.58-.8l-.1-.02a.75.75 0 0 0-.8.58l-.2.9h-1.48l.14-.55.02-.1a.75.75 0 0 0-1.48-.26m.96 2.41h1.49l-.36 1.59h-1.52zM6.5 2A2.5 2.5 0 0 0 4 4.5v15A2.5 2.5 0 0 0 6.5 22h13.25a.75.75 0 0 0 0-1.5H6.5a1 1 0 0 1-1-1h14.25c.41 0 .75-.34.75-.75V4.5A2.5 2.5 0 0 0 18 2zM19 18H5.5V4.5a1 1 0 0 1 1-1H18a1 1 0 0 1 1 1z"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function BookNumberIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
