// BookArrowClockwiseIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M17.5 3.48a.5.5 0 0 0 .5-.5v-2a.5.5 0 0 0-1 0v.76a4.5 4.5 0 1 0 2 3.74.5.5 0 0 0-1 0 3.5 3.5 0 1 1-1.7-3h-.8a.5.5 0 0 0 0 1zm-1.5 7.3q-.49.13-1 .18V15H5V4a1 1 0 0 1 1-1h3.59q.27-.54.65-1H6a2 2 0 0 0-2 2v12c0 1.1.9 2 2 2h9.5a.5.5 0 0 0 0-1H6a1 1 0 0 1-1-1h10a1 1 0 0 0 1-1z"/></>),
  24: (<><path d="M21.25 5c.41 0 .75-.34.75-.75V1.5a.75.75 0 0 0-1.5 0v.63A6 6 0 1 0 23 7a.75.75 0 0 0-1.5 0 4.5 4.5 0 1 1-1.67-3.5H18.5a.75.75 0 0 0 0 1.5zM6.5 2h5.6q-.68.67-1.16 1.5H6.5a1 1 0 0 0-1 1V18H19v-4.29a7 7 0 0 0 1.5-.65v5.69c0 .41-.34.75-.75.75H5.5a1 1 0 0 0 1 1h13.25a.75.75 0 0 1 0 1.5H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function BookArrowClockwiseIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
