// BoxArrowUpIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M11.3 2.48a3.5 3.5 0 0 0-2.6 0l-5.76 2.3A1.5 1.5 0 0 0 2 6.18v7.64c0 .62.37 1.17.94 1.4l5.76 2.3q.66.26 1.38.25a6 6 0 0 1-.62-1.06l-.39-.12-5.76-2.3a.5.5 0 0 1-.31-.47V6.24l6.5 2.6v3.36q.39-.81 1-1.48V8.84l6.5-2.6V9.6q.54.27 1 .66V6.18a1.5 1.5 0 0 0-.94-1.4zm-2.23.93a2.5 2.5 0 0 1 1.86 0l5.22 2.09-2.27.91-6.16-2.46zm-2.7 1.08 6.16 2.46L10 7.96 3.85 5.5zm8.13 14.5a4.5 4.5 0 1 0 0-8.99 4.5 4.5 0 0 0 0 9m.35-6.85 2 2a.5.5 0 1 1-.7.71L15 13.71v2.79a.5.5 0 0 1-1 0v-2.8l-1.15 1.15a.5.5 0 1 1-.7-.7l2-2a.5.5 0 0 1 .35-.15.5.5 0 0 1 .35.14"/></>),
  24: (<><path d="M10.6 2.51c.9-.36 1.9-.36 2.8 0l7.5 3.04c.67.27 1.1.91 1.1 1.62v5.64a7 7 0 0 0-1.5-1.08V7.77l-7.75 3v2.3a6.5 6.5 0 0 0-1.5 2.64v-4.95L3.5 7.75v9.08q0 .17.16.23l7.5 3.04.09.04.19.07.18.06q.37.8.94 1.45-1 .15-1.97-.23l-7.5-3.04C2.43 18.18 2 17.54 2 16.83V7.17c0-.7.43-1.35 1.1-1.62zm2.25 1.4a2.3 2.3 0 0 0-1.7 0l-1.9.77 7.52 2.93 2.67-1.03zM4.59 6.55 12 9.45l2.7-1.04L7.21 5.5zM23 17.5a5.5 5.5 0 1 0-11 0 5.5 5.5 0 0 0 11 0M17.54 14l.09.02.06.02.07.03.05.04 2.54 2.54.06.07a.5.5 0 0 1-.7.7l-.06-.07L18 15.71v5.38a.5.5 0 0 1-.41.4l-.09.01h-.09a.5.5 0 0 1-.4-.4L17 21v-5.3l-1.65 1.65-.07.06a.5.5 0 0 1-.56 0l-.07-.06-.06-.06a.5.5 0 0 1 0-.57l.06-.07 2.5-2.51.07-.05.07-.04.08-.03.06-.01h.11"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function BoxArrowUpIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
