// BriefcaseMedicalIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M9.25 1c.97 0 1.75.78 1.75 1.75V4h1.5A2.5 2.5 0 0 1 15 6.5v5a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 1 11.5v-5A2.5 2.5 0 0 1 3.5 4H5V2.75C5 1.78 5.78 1 6.75 1zM3.5 5C2.67 5 2 5.67 2 6.5v5c0 .83.67 1.5 1.5 1.5h9c.83 0 1.5-.67 1.5-1.5v-5c0-.83-.67-1.5-1.5-1.5zM8 6.5c.28 0 .5.22.5.5v1.5H10a.5.5 0 0 1 0 1H8.5V11a.5.5 0 0 1-1 0V9.5H6a.5.5 0 0 1 0-1h1.5V7c0-.28.22-.5.5-.5M6.75 2a.75.75 0 0 0-.75.75V4h4V2.75A.75.75 0 0 0 9.25 2z"/></>),
  20: (<><path d="M11.25 2c.97 0 1.75.78 1.75 1.75V5h2a3 3 0 0 1 3 3v6a3 3 0 0 1-3 3H5a3 3 0 0 1-3-2.85V8a3 3 0 0 1 3-3h2V3.75C7 2.78 7.78 2 8.75 2zM5 6a2 2 0 0 0-2 2v6l.01.2A2 2 0 0 0 5 16h10a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2zm5 2c.27 0 .5.23.5.5v2h2a.5.5 0 0 1 0 1h-2v2a.5.5 0 0 1-1 0v-2h-2a.5.5 0 0 1 0-1h2v-2c0-.27.22-.5.5-.5M8.75 3a.75.75 0 0 0-.75.75V5h4V3.75a.75.75 0 0 0-.75-.75z"/></>),
  24: (<><path d="M13.75 2C14.99 2 16 3 16 4.25V6h2.75C20.55 6 22 7.46 22 9.25v8.5c0 1.8-1.46 3.25-3.25 3.25H5.25A3.25 3.25 0 0 1 2 17.75v-8.5C2 7.45 3.46 6 5.25 6H8V4.25C8 3.01 9 2 10.25 2zm-8.5 5.5c-.97 0-1.75.78-1.75 1.75v8.5c0 .97.78 1.75 1.75 1.75h13.5c.97 0 1.75-.78 1.75-1.75v-8.5c0-.97-.78-1.75-1.75-1.75zM12 9.75c.39 0 .7.3.75.67v2.08h2.08a.75.75 0 0 1 0 1.5h-2.08v2a.75.75 0 0 1-1.5 0v-2h-2a.75.75 0 0 1 0-1.5h2v-2.08a.75.75 0 0 1 .75-.67M10.25 3.5a.75.75 0 0 0-.75.75V6h5V4.25a.75.75 0 0 0-.75-.75z"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function BriefcaseMedicalIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
