// BriefcaseSearchIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M4.5 10a3.5 3.5 0 0 1 2.8 5.6l2.55 2.55a.5.5 0 1 1-.7.7L6.6 16.3q-.9.68-2.1.7a3.5 3.5 0 1 1 0-7m6.75-8c.97 0 1.75.78 1.75 1.75V5h2a3 3 0 0 1 3 3v6a3 3 0 0 1-3 3h-4.88l-1-1H15a2 2 0 0 0 2-2v-2.77c-.53.48-1.23.77-2 .77h-4v.5a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5v-2c0-.28.22-.5.5-.5h1c.28 0 .5.22.5.5v.5h4a2 2 0 0 0 2-2V8a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v1q0 .13.02.25-.54.2-1.02.5V8a3 3 0 0 1 3-3h2V3.75C7 2.78 7.78 2 8.75 2zM4.5 11a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5m4.25-8a.75.75 0 0 0-.75.75V5h4V3.75a.75.75 0 0 0-.75-.75z"/></>),
  24: (<><path d="M5.5 12a4.5 4.5 0 0 1 3.67 7.1l2.61 2.62a.75.75 0 1 1-1.06 1.06l-2.61-2.61A4.5 4.5 0 1 1 5.5 12m8.25-10C14.99 2 16 3 16 4.25V6h2.75C20.55 6 22 7.46 22 9.25v8.5c0 1.8-1.46 3.25-3.25 3.25h-6.28l-1.5-1.5h7.78c.97 0 1.75-.78 1.75-1.75v-4.26q-.76.5-1.75.51H14a1 1 0 0 1-1 1h-2l-.22-.02a6 6 0 0 0-.78-1.64V12a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v.5h4.75c.97 0 1.75-.78 1.75-1.75v-1.5c0-.97-.78-1.75-1.75-1.75H5.25c-.97 0-1.75.78-1.75 1.75v1.5q0 .3.1.59a6 6 0 0 0-1.6.92V9.25C2 7.45 3.46 6 5.25 6H8V4.25C8 3.01 9 2 10.25 2zM5.5 13.5a3 3 0 1 0 0 6 3 3 0 0 0 0-6m4.75-10a.75.75 0 0 0-.75.75V6h5V4.25a.75.75 0 0 0-.75-.75z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function BriefcaseSearchIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
