// BuildingSkyscraperIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M6 7.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0m1.5.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1M6 9.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0m1.5.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1m4.5 1.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0m-.5-1.5a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1m-6-9a.5.5 0 0 0-.5.5V3h-.5a.5.5 0 0 0-.5.5v1.65c-.59.27-1 .86-1 1.55v6.8c0 .28.22.5.5.5h10a.5.5 0 0 0 .5-.5v-3.3a3.7 3.7 0 0 0-3.7-3.7h-.31A1.7 1.7 0 0 0 9 5.15V3.5a.5.5 0 0 0-.5-.5H8V1.5a.5.5 0 0 0-.5-.5zM8 5H5V4h3zm1 1.7V13H8v-1.1c0-.5-.4-.9-.9-.9H5.9c-.5 0-.9.4-.9.9V13H4V6.7c0-.39.31-.7.7-.7h3.6c.39 0 .7.31.7.7M6 13v-1h1v1zm4 0V7.5h.3c1.5 0 2.7 1.2 2.7 2.7V13zM7 3H6V2h1z"/></>),
  20: (<><path d="M7.5 8.75a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0m1.75.75a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5M7.5 11.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0m1.75.75a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5m5.25 2.25a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0m-.75-1.75a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5M7 2a.5.5 0 0 0-.5.5V4h-.94a.5.5 0 0 0-.5.5v1.74A2 2 0 0 0 4 8v8.5c0 .27.22.5.5.5h12a.5.5 0 0 0 .5-.5v-4A4.5 4.5 0 0 0 12.5 8H12a2 2 0 0 0-.94-1.7V4.5a.5.5 0 0 0-.5-.5H9.5V2.5A.5.5 0 0 0 9 2zm3 4H6.06V5h4v1zm1 10h-1v-2a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1v2H5V8a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1zm-4 0v-2h2v2zm9 0h-4V9h.5a3.5 3.5 0 0 1 3.5 3.5zM8.5 4h-1V3h1z"/></>),
  24: (<><path d="M12 11a1 1 0 1 1-2 0 1 1 0 0 1 2 0m-1 4a1 1 0 1 0 0-2 1 1 0 0 0 0 2m-2-4a1 1 0 1 1-2 0 1 1 0 0 1 2 0m-1 4a1 1 0 1 0 0-2 1 1 0 0 0 0 2m10 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0m-1 4a1 1 0 1 0 0-2 1 1 0 0 0 0 2M8.25 2a.75.75 0 0 0-.75.75V5H6.25a.75.75 0 0 0-.75.75V7.8A2.8 2.8 0 0 0 4 10.25v10.5c0 .41.34.75.75.75h15c.41 0 .75-.34.75-.75v-5c0-3.1-2.45-5.62-5.51-5.74a2.8 2.8 0 0 0-1.49-2.2V5.74a.75.75 0 0 0-.75-.75H11.5V2.75a.75.75 0 0 0-.75-.75zM12 7.5H7v-1h5zM13.5 20H12v-2.75a.75.75 0 0 0-.75-.75h-3.5a.75.75 0 0 0-.75.75V20H5.5v-9.75C5.5 9.56 6.06 9 6.75 9h5.5c.69 0 1.25.56 1.25 1.25zm-5 0v-2h2v2zm6.5 0v-8.5c2.23.14 4 1.99 4 4.25V20zM10 5H9V3.5h1z"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function BuildingSkyscraperIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
