// CaretDownRightIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M10.3 4.25a1 1 0 0 1 1.7.7v5.55c0 .83-.67 1.5-1.5 1.5H4.96a1 1 0 0 1-.71-1.7zm.7.7L4.96 11h5.54a.5.5 0 0 0 .5-.5z"/></>),
  20: (<><path d="M13.3 5.25a1 1 0 0 1 1.7.7v7.55c0 .83-.67 1.5-1.5 1.5H5.96a1 1 0 0 1-.71-1.7zm.7.7L5.96 14h7.54a.5.5 0 0 0 .5-.5z"/></>),
  24: (<><path d="m16.5 7.81-8.69 8.7h8.44q.23-.03.25-.26zm-.63-1.49a1.25 1.25 0 0 1 2.13.89v9.04c0 .97-.78 1.75-1.75 1.75H7.21a1.25 1.25 0 0 1-.89-2.13z"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function CaretDownRightIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
