// CellularOffIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M2.85 2.15a.5.5 0 1 0-.7.7L10 10.71v4.88a.5.5 0 0 0 1-.09v-3.8l2 2v1.89a.5.5 0 0 0 1-.09v-.8l3.15 3.15a.5.5 0 0 0 .7-.7zM13 10.88V6.5a.5.5 0 0 1 1-.09v5.47zm3 3V4.5a.5.5 0 0 1 1-.09v10.47zm-8-3.47a.5.5 0 0 0-1 .09v5l.01.09a.5.5 0 0 0 1-.09v-5zm-3 2a.5.5 0 0 0-1 .09v3.09a.5.5 0 0 0 1-.09v-3.09"/></>),
  24: (<><path d="M3.28 2.22a.75.75 0 1 0-1.06 1.06L11 12.06v7.29a.75.75 0 0 0 1.5-.1v-5.69l2.5 2.5v3.29a.75.75 0 0 0 1.5-.1v-1.69l4.22 4.22a.75.75 0 0 0 1.06-1.06zM19 15.82l1.5 1.5V5.64a.75.75 0 0 0-1.5.12zm-4-4 1.5 1.5V8.65a.75.75 0 0 0-1.5.1zM3.75 17c.38 0 .7.28.74.65l.01.1v1.5a.75.75 0 0 1-1.5.1v-1.6c0-.41.34-.75.75-.75m4-3c.38 0 .7.28.74.65l.01.1v4.5a.75.75 0 0 1-1.5.1v-4.6c0-.41.34-.75.75-.75"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function CellularOffIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
