// ChatEmptyIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
  48: '0 0 48 48',
};
const C = {
  16: (<><path d="M8 1a7 7 0 1 1-3.54 13.04l-2.8.93a.5.5 0 0 1-.63-.63l.93-2.8A7 7 0 0 1 8 1m0 1a6 6 0 0 0-5.07 9.2q.12.2.05.43l-.69 2.08 2.08-.7q.22-.06.42.06A6 6 0 1 0 8 2"/></>),
  20: (<><path d="M10 2a8 8 0 1 1-3.61 15.14l-.12-.07-3.65.92a.5.5 0 0 1-.62-.45v-.08l.01-.08.92-3.64-.07-.12a8 8 0 0 1-.83-2.9l-.02-.37L2 10a8 8 0 0 1 8-8m0 1a7 7 0 0 0-6.1 10.42.5.5 0 0 1 .06.28l-.02.1-.75 3.01 3.02-.75.19-.01.09.02.09.04A7 7 0 1 0 10 3"/></>),
  24: (<><path d="M12 2a10 10 0 1 1-4.59 18.89L3.6 21.96a1.25 1.25 0 0 1-1.54-1.54l1.06-3.83A10 10 0 0 1 12 2m0 1.5a8.5 8.5 0 0 0-7.43 12.64l.15.27-1.1 3.98 3.98-1.11.27.15A8.5 8.5 0 1 0 12 3.5"/></>),
  28: (<><path d="M14 3.5a10.5 10.5 0 0 0-9.14 15.68q.15.27.07.57L3.61 24.4l4.64-1.32q.3-.08.57.07A10.5 10.5 0 1 0 14 3.5M2 14a12 12 0 1 1 6.36 10.6L3.6 25.95c-.94.27-1.8-.6-1.54-1.54l1.36-4.77C2.5 17.96 2 16.04 2 14"/></>),
  48: (<><path d="M24 6.5A17.5 17.5 0 0 0 8.84 32.74c.17.3.21.65.12.97l-2.12 7.44 7.44-2.11q.51-.14.97.12A17.5 17.5 0 1 0 24 6.5M4 24a20 20 0 1 1 10.47 17.59l-8.24 2.34a1.75 1.75 0 0 1-2.16-2.16l2.34-8.24A20 20 0 0 1 4 24"/></>),
};
const SIZES = [16, 20, 24, 28, 48];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ChatEmptyIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
