// ChevronDownUpIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="m11.85 3.35-3.5 3.5a.5.5 0 0 1-.7 0l-3.5-3.5a.5.5 0 1 1 .7-.7L8 5.79l3.15-3.14a.5.5 0 0 1 .7.7m0 9.3-3.5-3.5a.5.5 0 0 0-.7 0l-3.5 3.5a.5.5 0 0 0 .7.7L8 10.21l3.15 3.14a.5.5 0 0 0 .7-.7"/></>),
  20: (<><path d="M5.85 3.15a.5.5 0 1 0-.7.7l4.5 4.5c.2.2.5.2.7 0l4.5-4.5a.5.5 0 0 0-.7-.7L10 7.29zm9 13-4.5-4.5a.5.5 0 0 0-.7 0l-4.5 4.5a.5.5 0 0 0 .7.7L10 12.71l4.15 4.14a.5.5 0 0 0 .7-.7"/></>),
  24: (<><path d="M6.28 2.97a.75.75 0 0 0-1.06 1.06l6.25 6.25c.3.3.77.3 1.06 0l6.25-6.25a.75.75 0 0 0-1.06-1.06L12 8.69zm0 18.06a.75.75 0 0 1-1.06-1.06l6.25-6.25c.3-.3.77-.3 1.06 0l6.25 6.25a.75.75 0 1 1-1.06 1.06L12 15.31z"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ChevronDownUpIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
