// ChevronDoubleRightIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
};
const C = {
  16: (<><path d="M3.65 3.15c.2-.2.5-.2.7 0l4.5 4.5a.5.5 0 0 1 0 .7l-4.5 4.5a.5.5 0 0 1-.7-.7L7.79 8 3.65 3.85a.5.5 0 0 1 0-.7m4 0c.2-.2.5-.2.7 0l4.5 4.5a.5.5 0 0 1 .14.45.5.5 0 0 1-.14.25l-4.5 4.5a.5.5 0 0 1-.7-.7L11.79 8 7.65 3.85a.5.5 0 0 1 0-.7"/></>),
  20: (<><path d="M4.65 4.15c.2-.2.5-.2.7 0l5.5 5.5a.5.5 0 0 1 0 .7l-5.5 5.5a.5.5 0 1 1-.7-.7L9.79 10 4.65 4.85a.5.5 0 0 1 0-.7m5 0c.2-.2.5-.2.7 0l5.5 5.5a.5.5 0 0 1 0 .7l-5.5 5.5a.5.5 0 1 1-.7-.7L14.79 10 9.65 4.85a.5.5 0 0 1 0-.7"/></>),
};
const SIZES = [16, 20];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ChevronDoubleRightIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
