// ClipboardTaskAddIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M6.5 2c-.65 0-1.2.42-1.41 1H3.5C2.67 3 2 3.67 2 4.5v12c0 .83.67 1.5 1.5 1.5h6.76a6 6 0 0 1-.66-1H3.5a.5.5 0 0 1-.5-.5v-12c0-.28.22-.5.5-.5h1.59c.2.58.76 1 1.41 1h3c.65 0 1.2-.42 1.41-1h1.59c.28 0 .5.22.5.5v4.7q.49-.13 1-.18V4.5c0-.83-.67-1.5-1.5-1.5h-1.59c-.2-.58-.76-1-1.41-1zM6 3.5c0-.28.22-.5.5-.5h3a.5.5 0 0 1 0 1h-3a.5.5 0 0 1-.5-.5m4.85 6.35a.5.5 0 0 0-.7-.7L7 12.29l-1.15-1.14a.5.5 0 0 0-.7.7l1.5 1.5c.2.2.5.2.7 0zM19 14.5a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0m-4-2a.5.5 0 0 0-1 0V14h-1.5a.5.5 0 0 0 0 1H14v1.5a.5.5 0 0 0 1 0V15h1.5a.5.5 0 0 0 0-1H15z"/></>),
  24: (<><path d="M13.99 4a2.25 2.25 0 0 0-2.24-2h-3.5c-1.16 0-2.11.87-2.24 2H4.25C3.01 4 2 5 2 6.25v13.5C2 20.99 3 22 4.25 22h8.56a7 7 0 0 1-1.08-1.5H4.25a.75.75 0 0 1-.75-.75V6.25c0-.41.34-.75.75-.75h2.13c.4.6 1.09 1 1.87 1h3.5c.78 0 1.47-.4 1.87-1h2.13c.41 0 .75.34.75.75v4.83a7 7 0 0 1 1.5-.06V6.25C18 5.01 17 4 15.75 4zm0 .1.01.15zm-5.74-.6h3.5a.75.75 0 0 1 0 1.5h-3.5a.75.75 0 0 1 0-1.5m3.7 10.6a6.5 6.5 0 0 1 2.15-2.14l.93-.93a.75.75 0 1 0-1.06-1.06L9 14.94l-1.97-1.97a.75.75 0 0 0-1.06 1.06l2.5 2.5c.3.3.77.3 1.06 0zM23 17.5a5.5 5.5 0 1 0-11 0 5.5 5.5 0 0 0 11 0m-5 .5v2.5a.5.5 0 1 1-1 0V18h-2.5a.5.5 0 0 1 0-1H17v-2.5a.5.5 0 1 1 1 0V17h2.5a.5.5 0 0 1 0 1z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ClipboardTaskAddIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
