// ClockIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
  48: '0 0 48 48',
};
const C = {
  16: (<><path d="M2 8a6 6 0 1 1 12 0A6 6 0 0 1 2 8m6-7a7 7 0 1 0 0 14A7 7 0 0 0 8 1m0 3.5a.5.5 0 0 0-1 0v4c0 .28.22.5.5.5h3a.5.5 0 0 0 0-1H8z"/></>),
  20: (<><path d="M10 2a8 8 0 1 1 0 16 8 8 0 0 1 0-16m0 1a7 7 0 1 0 0 14 7 7 0 0 0 0-14m-.5 2a.5.5 0 0 1 .5.41V10h2.5a.5.5 0 0 1 .09 1H9.5a.5.5 0 0 1-.5-.41V5.5c0-.28.22-.5.5-.5"/></>),
  24: (<><path d="M3.5 12a8.5 8.5 0 1 1 17 0 8.5 8.5 0 0 1-17 0M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20m0 4.65a.75.75 0 0 0-1.5.1v6.1c.06.37.37.65.75.65h4.1a.75.75 0 0 0-.1-1.5H12V6.65"/></>),
  28: (<><path d="M3.5 14a10.5 10.5 0 1 1 21 0 10.5 10.5 0 0 1-21 0M14 2a12 12 0 1 0 0 24 12 12 0 0 0 0-24m0 5.65a.75.75 0 0 0-1.5.1v7.1c.06.37.37.65.75.65h5.1a.75.75 0 0 0-.1-1.5H14V7.65"/></>),
  48: (<><path d="M24 5a19 19 0 1 1 0 38 19 19 0 0 1 0-38m0 2.5a16.5 16.5 0 1 0 0 33 16.5 16.5 0 0 0 0-33M22.75 12c.65 0 1.18.5 1.24 1.12l.01.13V24h6.75a1.25 1.25 0 0 1 .13 2.5h-8.13c-.65 0-1.18-.5-1.24-1.12l-.01-.13v-12c0-.69.56-1.25 1.25-1.25"/></>),
};
const SIZES = [16, 20, 24, 28, 48];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ClockIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
