// CloudIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
  48: '0 0 48 48',
};
const C = {
  16: (<><path d="M8 3a3 3 0 0 0-3 3 .5.5 0 0 1-.5.5h-.25a2.25 2.25 0 0 0 0 4.5h7.5a2.25 2.25 0 0 0 0-4.5h-.25A.5.5 0 0 1 11 6a3 3 0 0 0-3-3M4.03 5.5a4 4 0 0 1 7.94 0 3.25 3.25 0 0 1-.22 6.5h-7.5a3.25 3.25 0 0 1-.22-6.5"/></>),
  20: (<><path d="M10 4c2.82 0 4.41 1.92 4.65 4.25h.07A3.33 3.33 0 0 1 18 11.62 3.33 3.33 0 0 1 14.72 15H5.28A3.33 3.33 0 0 1 2 11.62c0-1.8 1.37-3.27 3.1-3.37h.25C5.6 5.9 7.18 4 10 4m0 1C7.89 5 6.55 6.32 6.35 8.35a1 1 0 0 1-1 .9h-.07A2.33 2.33 0 0 0 3 11.62 2.33 2.33 0 0 0 5.28 14h9.44A2.33 2.33 0 0 0 17 11.62a2.33 2.33 0 0 0-2.28-2.37h-.07a1 1 0 0 1-1-.9C13.45 6.32 12.11 5 10 5"/></>),
  24: (<><path d="M12 5.5a4.5 4.5 0 0 0-4.5 4.29.75.75 0 0 1-.74.71H6.5a3 3 0 1 0 0 6h11a3 3 0 1 0 0-6h-.26a.75.75 0 0 1-.74-.71A4.5 4.5 0 0 0 12 5.5M6.08 9.02a6 6 0 0 1 11.84 0A4.5 4.5 0 0 1 17.5 18h-11a4.5 4.5 0 0 1-.42-8.98"/></>),
  28: (<><path d="M14 6.5a5.5 5.5 0 0 0-5.5 5.28.75.75 0 0 1-.75.72H7.5a4 4 0 0 0 0 8h13a4 4 0 0 0 0-8h-.25a.75.75 0 0 1-.75-.72A5.5 5.5 0 0 0 14 6.5m-6.93 4.52a7 7 0 0 1 13.86 0A5.5 5.5 0 0 1 20.5 22h-13a5.5 5.5 0 0 1-.43-10.98"/></>),
  48: (<><path d="M24 11.5a9.5 9.5 0 0 0-9.5 9.72 1.25 1.25 0 0 1-1.25 1.28H11.5a6 6 0 0 0 0 12h25a6 6 0 0 0 0-12h-1.75a1.25 1.25 0 0 1-1.25-1.28V21a9.5 9.5 0 0 0-9.5-9.5M12.04 20a12 12 0 0 1 23.92 0h.54a8.5 8.5 0 0 1 0 17h-25a8.5 8.5 0 0 1 0-17z"/></>),
};
const SIZES = [16, 20, 24, 28, 48];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function CloudIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
