// CommentMultipleMentionIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
};
const C = {
  16: (<><path d="M15 7.26a6 6 0 0 0-1-.66V6a3 3 0 0 0-3-3H3.27A2 2 0 0 1 5 2h6a4 4 0 0 1 4 4zM13 6v.2q-.49-.13-1-.18V6a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h1v2l2.09-1.52q.1.54.29 1.03l-1.8 1.3A1 1 0 0 1 3 14v-1a2 2 0 0 1-2-2V6c0-1.1.9-2 2-2h8a2 2 0 0 1 2 2m-1.5 2a3.5 3.5 0 1 0 0 7h1a.5.5 0 0 1 0 1h-1a4.5 4.5 0 1 1 4.5-4.5v.75a1.75 1.75 0 0 1-3.17 1.03c-.4.44-.96.72-1.58.72C10.01 14 9 12.88 9 11.5S10 9 11.25 9q.7.01 1.26.43a.5.5 0 0 1 .99.07v2.75a.75.75 0 0 0 1.5 0v-.75A3.5 3.5 0 0 0 11.5 8m-.25 5c.6 0 1.25-.57 1.25-1.5s-.66-1.5-1.25-1.5c-.6 0-1.25.57-1.25 1.5s.66 1.5 1.25 1.5"/></>),
  20: (<><path d="M14.39 4.11A3.5 3.5 0 0 1 17 7.5v1.84q.52.18 1 .46V7.5A4.5 4.5 0 0 0 13.5 3h-7c-.82 0-1.54.4-2 1h9a4 4 0 0 1 .89.11M16 7.5v1.58A6 6 0 0 0 15 9V7.5c0-.83-.67-1.5-1.5-1.5h-9C3.67 6 3 6.67 3 7.5v6c0 .83.67 1.5 1.5 1.5H6v2l2.73-2H9q0 .5.08 1h-.02l-2.47 1.8A1 1 0 0 1 5 17v-1h-.5A2.5 2.5 0 0 1 2 13.5v-6A2.5 2.5 0 0 1 4.5 5h9A2.5 2.5 0 0 1 16 7.5M15 11a4 4 0 1 0 1.33 7.77.5.5 0 0 1 .34.95A5 5 0 1 1 20 15c0 1.45-.9 2.44-1.97 2.5a1.8 1.8 0 0 1-1.6-.84c-.4.5-.99.84-1.68.84-1.3 0-2.25-1.18-2.25-2.5s.95-2.5 2.25-2.5q.72.02 1.26.42A.5.5 0 0 1 17 13v2c0 .62.16 1 .35 1.22q.28.3.62.28c.43-.03 1.03-.45 1.03-1.5a4 4 0 0 0-4-4m-.25 5.5c.63 0 1.25-.6 1.25-1.5s-.62-1.5-1.25-1.5-1.25.6-1.25 1.5.62 1.5 1.25 1.5"/></>),
};
const SIZES = [16, 20];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function CommentMultipleMentionIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
