// CompassNorthwestIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
};
const C = {
  16: (<><path d="M8 1a7 7 0 1 1 0 14A7 7 0 0 1 8 1m0 1a6 6 0 1 0 0 12A6 6 0 0 0 8 2M4.6 5.9a1 1 0 0 1 1.3-1.3l2.55 1.04a3.5 3.5 0 0 1 1.9 1.91l1.05 2.54a1 1 0 0 1-1.3 1.3l-2.55-1.04a3.5 3.5 0 0 1-1.9-1.9zm1.97 2.17c.26.61.75 1.1 1.36 1.36l2.55 1.04-1.05-2.54a2.5 2.5 0 0 0-1.36-1.36L5.53 5.52z"/></>),
  20: (<><path d="M3 10a7 7 0 1 1 14 0 7 7 0 0 1-14 0m7-8a8 8 0 1 0 0 16 8 8 0 0 0 0-16M6.1 7.42A1 1 0 0 1 7.42 6.1l3.26 1.48a3.5 3.5 0 0 1 1.74 1.74l1.48 3.26a1 1 0 0 1-1.32 1.32l-3.26-1.48a3.5 3.5 0 0 1-1.74-1.74zm4.17 1.07L7 7.01l1.48 3.26c.25.55.7.99 1.24 1.24L13 12.99l-1.48-3.26c-.25-.55-.7-.99-1.24-1.24"/></>),
  24: (<><path d="M12 2a10 10 0 1 1 0 20 10 10 0 0 1 0-20m0 1.5a8.5 8.5 0 1 0 0 17 8.5 8.5 0 0 0 0-17M7.08 8.7c-.4-1.01.6-2.02 1.63-1.62l.2.09 3.75 1.42a4.8 4.8 0 0 1 2.75 2.75l.16.43 1.63 3.79a1.25 1.25 0 0 1-1.64 1.64l-3.76-1.61-.46-.18a4.8 4.8 0 0 1-2.75-2.75L7.21 9.03zm3 3.48c.32.8.95 1.44 1.74 1.78l.52.23 2.98 1.13-1.14-3-.22-.5a3.3 3.3 0 0 0-1.78-1.74L8.7 8.7z"/></>),
  28: (<><path d="M3.5 14a10.5 10.5 0 1 1 21 0 10.5 10.5 0 0 1-21 0M14 2a12 12 0 1 0 0 24 12 12 0 0 0 0-24M8.08 9.7c-.39-1.01.6-2 1.62-1.62l5 1.92a5.8 5.8 0 0 1 3.3 3.3l1.92 5c.39 1.01-.6 2-1.62 1.62l-5-1.92a5.8 5.8 0 0 1-3.3-3.3zm1.6-.02 1.72 4.47a4.3 4.3 0 0 0 2.45 2.45l4.47 1.72-1.72-4.47a4.3 4.3 0 0 0-2.45-2.45z"/></>),
};
const SIZES = [16, 20, 24, 28];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function CompassNorthwestIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
