// ConvertRangeIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M5 2a2 2 0 0 0-2 2v2c0 1.1.9 2 2 2h8a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2zM4 4a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1zm3 9.5a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1zm4.88-3.5H5a2 2 0 0 0-2 2v4c0 1.1.9 2 2 2h8a2 2 0 0 0 2-2v-1.09a1.5 1.5 0 0 1-1 0V16a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1v-4a1 1 0 0 1 1-1h6.09q.1-.31.35-.56zM18 7.5a.5.5 0 0 0-1 0v2c0 .83-.67 1.5-1.5 1.5h-1.8l1.15-1.15a.5.5 0 0 0-.7-.7l-2 2a.5.5 0 0 0 0 .7l2 2a.5.5 0 0 0 .7-.7L13.71 12h1.79A2.5 2.5 0 0 0 18 9.5z"/></>),
  24: (<><path d="M6.25 3C5.01 3 4 4 4 5.25v2.5C4 8.99 5 10 6.25 10h9.5C16.99 10 18 9 18 7.75v-2.5C18 4.01 17 3 15.75 3zM5.5 5.25c0-.41.34-.75.75-.75h9.5c.41 0 .75.34.75.75v2.5c0 .41-.34.75-.75.75h-9.5a.75.75 0 0 1-.75-.75zM8.7 16c-.39 0-.7.34-.7.75s.31.75.7.75h4.6c.39 0 .7-.34.7-.75s-.31-.75-.7-.75zm8.65.45-.07.08a.75.75 0 0 1-.98.07l-.08-.07-2-2a.75.75 0 0 1-.07-.98l.07-.08 2-2a.75.75 0 0 1 1.13.98l-.07.08-.72.72h1.5c.65 0 1.18-.5 1.24-1.12l.01-.13V9.75a.75.75 0 0 1 1.5-.1V12a2.75 2.75 0 0 1-2.58 2.74l-.17.01h-1.5l.72.72c.27.26.3.68.07.98m.65 2.8v-2.03l-.01.02c-.4.4-.96.57-1.49.5v1.51c0 .41-.34.75-.75.75h-9.5a.75.75 0 0 1-.75-.75v-5c0-.41.34-.75.75-.75h6.82q.09-.3.27-.54l.03-.03.12-.14.78-.79H6.25C5.01 12 4 13 4 14.25v5c0 1.24 1 2.25 2.25 2.25h9.5c1.24 0 2.25-1 2.25-2.25"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ConvertRangeIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
