// CouchIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
  48: '0 0 48 48',
};
const C = {
  20: (<><path d="M6 4a2 2 0 0 0-2 2v1.05A2.5 2.5 0 0 0 2 9.5V12c0 1.1.9 2 2 2v1.5a.5.5 0 0 0 1 0V14h10v1.5a.5.5 0 0 0 1 0V14a2 2 0 0 0 2-2V9.5a2.5 2.5 0 0 0-2-2.45V6a2 2 0 0 0-2-2zm9 3.05A2.5 2.5 0 0 0 13.05 9h-6.1A2.5 2.5 0 0 0 5 7.05V6a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1zM16 13H4a1 1 0 0 1-1-1V9.5a1.5 1.5 0 1 1 3 0c0 .28.22.5.5.5h7a.5.5 0 0 0 .5-.5 1.5 1.5 0 0 1 3 0V12a1 1 0 0 1-1 1"/></>),
  24: (<><path d="M7.25 4A2.75 2.75 0 0 0 4.5 6.75v1.34A3.25 3.25 0 0 0 2 11.25v3c0 1.43 1.1 2.61 2.5 2.74v1.26a.75.75 0 0 0 1.5 0V17h12v1.25a.75.75 0 0 0 1.5 0v-1.26c1.4-.13 2.5-1.3 2.5-2.74v-3a3.25 3.25 0 0 0-2.5-3.16V6.75A2.75 2.75 0 0 0 16.75 4zm12 11.5H4.75c-.69 0-1.25-.56-1.25-1.25v-3a1.75 1.75 0 1 1 3.5 0v.5c0 .41.34.75.75.75h8.5c.41 0 .75-.34.75-.75v-.5a1.75 1.75 0 1 1 3.5 0v3c0 .69-.56 1.25-1.25 1.25M18 8.09A3.25 3.25 0 0 0 15.5 11h-7A3.25 3.25 0 0 0 6 8.09V6.75c0-.69.56-1.25 1.25-1.25h9.5c.69 0 1.25.56 1.25 1.25z"/></>),
  48: (<><path d="M13.25 11A5.25 5.25 0 0 0 8 16.25v1.46A5.5 5.5 0 0 0 4 23v6.75c0 2.47 1.7 4.54 4 5.1v2.9a1.25 1.25 0 1 0 2.5 0V35h27v2.75a1.25 1.25 0 1 0 2.5 0v-2.9c2.3-.56 4-2.63 4-5.1V23a5.5 5.5 0 0 0-4-5.3v-1.45c0-2.9-2.35-5.25-5.25-5.25zm24.25 6.6A5.5 5.5 0 0 0 33 23H15a5.5 5.5 0 0 0-4.5-5.4v-1.35a2.75 2.75 0 0 1 2.75-2.75h21.5a2.75 2.75 0 0 1 2.75 2.75zM6.5 23a3 3 0 1 1 6 0v1.25c0 .69.56 1.25 1.25 1.25h20.5c.69 0 1.25-.56 1.25-1.25V23a3 3 0 1 1 6 0v6.75a2.75 2.75 0 0 1-2.75 2.75H9.25a2.75 2.75 0 0 1-2.75-2.75z"/></>),
};
const SIZES = [20, 24, 48];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function CouchIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
