// CreditCardPersonIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M4.75 4A2.75 2.75 0 0 0 2 6.75v6.5A2.75 2.75 0 0 0 4.75 16h5.3q.11-.55.45-1H4.75C3.78 15 3 14.22 3 13.25V9h15V6.75A2.75 2.75 0 0 0 15.25 4zM3 6.75C3 5.78 3.78 5 4.75 5h10.5c.97 0 1.75.78 1.75 1.75V8H3zM16.5 12a2 2 0 1 1-4 0 2 2 0 0 1 4 0m1.5 4.5c0 1.25-1 2.5-3.5 2.5S11 17.75 11 16.5c0-.83.67-1.5 1.5-1.5h4c.83 0 1.5.67 1.5 1.5"/></>),
  24: (<><path d="M5.25 5A3.25 3.25 0 0 0 2 8.25v7.5C2 17.55 3.46 19 5.25 19h7.86c.18-.61.56-1.14 1.07-1.5H5.25c-.97 0-1.75-.78-1.75-1.75V11H22V8.25C22 6.45 20.54 5 18.75 5zM20.5 8.25V9.5h-17V8.25c0-.97.78-1.75 1.75-1.75h13.5c.97 0 1.75.78 1.75 1.75m.5 6.25a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0m2 5.38c0 1.55-1.29 3.12-4.5 3.12S14 21.44 14 19.88v-.1c0-.99.8-1.78 1.77-1.78h5.46c.98 0 1.77.8 1.77 1.77z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function CreditCardPersonIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
