// CropArrowRotateIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M8 2a6 6 0 0 0-5.06 2.77.5.5 0 1 1-.84-.54A7 7 0 0 1 13 3.1V2a.5.5 0 0 1 1 0v2.5a.5.5 0 0 1-.5.5H11a.5.5 0 0 1 0-1h1.47C11.37 2.77 9.77 2 8 2M3.53 12H5a.5.5 0 0 0 0-1H2.5a.5.5 0 0 0-.5.5V14a.5.5 0 0 0 1 0v-1.1a6.98 6.98 0 0 0 10.9-1.13.5.5 0 1 0-.84-.54 6 6 0 0 1-9.53.77M5.5 3.5c.28 0 .5.22.5.5v5a1 1 0 0 0 1 1h5a.5.5 0 0 1 0 1h-1v1a.5.5 0 0 1-1 0v-1H7a2 2 0 0 1-2-2V6H4a.5.5 0 0 1 0-1h1V4c0-.28.22-.5.5-.5M10 7v2h1V7a2 2 0 0 0-2-2H7v1h2a1 1 0 0 1 1 1"/></>),
  20: (<><path d="M3.8 6.73A7 7 0 0 1 15.75 6H14a.5.5 0 0 0 0 1h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-1 0v1.84a8 8 0 0 0-13.58.93.5.5 0 1 0 .89.46M6 14H4.25a7 7 0 0 0 11.94-.73.5.5 0 0 1 .89.46 8 8 0 0 1-13.58.94v1.83a.5.5 0 0 1-1 0v-3c0-.28.22-.5.5-.5h3a.5.5 0 0 1 0 1m1.5-9c.28 0 .5.22.5.5V11a1 1 0 0 0 1 1h5.5a.5.5 0 0 1 0 1H13v1.5a.5.5 0 0 1-1 0V13H9a2 2 0 0 1-2-2V8H5.5a.5.5 0 0 1 0-1H7V5.5c0-.28.22-.5.5-.5m4.5 6V9a1 1 0 0 0-1-1H9V7h2a2 2 0 0 1 2 2v2z"/></>),
  24: (<><path d="M4.7 7.64A8.5 8.5 0 0 1 18.48 6.5h-1.73a.75.75 0 0 0 0 1.5h3.5c.41 0 .75-.34.75-.75v-3.5a.75.75 0 0 0-1.5 0v1.64A9.98 9.98 0 0 0 3.42 6.86a.75.75 0 0 0 1.28.78m-.2 10.98v1.63a.75.75 0 0 1-1.5 0v-3.5c0-.41.34-.75.75-.75h3.5a.75.75 0 0 1 0 1.5H5.52a8.48 8.48 0 0 0 13.78-1.14.75.75 0 1 1 1.28.78A10 10 0 0 1 4.5 18.62m5-11.87a.75.75 0 0 0-1.5 0V8H6.75a.75.75 0 0 0 0 1.5H8v3.75A2.75 2.75 0 0 0 10.75 16h3.75v1.25a.75.75 0 0 0 1.5 0V16h1.25a.75.75 0 0 0 0-1.5h-6.5c-.69 0-1.25-.56-1.25-1.25zm5 4v2.75H16v-2.75A2.75 2.75 0 0 0 13.25 8H10.5v1.5h2.75c.69 0 1.25.56 1.25 1.25"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function CropArrowRotateIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
