// CropIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
  48: '0 0 48 48',
};
const C = {
  16: (<><path d="M5 1.5a.5.5 0 0 0-1 0V4H1.5a.5.5 0 0 0 0 1H4v4.5A2.5 2.5 0 0 0 6.5 12H11v2.5a.5.5 0 0 0 1 0V12h2.5a.5.5 0 0 0 0-1h-8A1.5 1.5 0 0 1 5 9.5zm6 5V10h1V6.5A2.5 2.5 0 0 0 9.5 4H6v1h3.5c.83 0 1.5.67 1.5 1.5"/></>),
  20: (<><path d="M6 2.5a.5.5 0 0 0-1 0V5H2.5a.5.5 0 0 0 0 1H5v6.5A2.5 2.5 0 0 0 7.5 15H14v2.5a.5.5 0 0 0 1 0V15h2.5a.5.5 0 0 0 0-1h-10A1.5 1.5 0 0 1 6 12.5zm8 5V13h1V7.5A2.5 2.5 0 0 0 12.5 5H7v1h5.5c.83 0 1.5.67 1.5 1.5"/></>),
  24: (<><path d="M21.25 17a.75.75 0 0 1 .1 1.5H18.5v2.75a.75.75 0 0 1-1.5.1V18.5H8.75a3.25 3.25 0 0 1-3.24-3.07l-.01-.18V7H2.75a.75.75 0 0 1-.1-1.5H5.5V2.75a.75.75 0 0 1 1.5-.1v12.6c0 .92.7 1.67 1.6 1.74l.15.01zM8 5.5h7.25a3.25 3.25 0 0 1 3.24 3.07l.01.18V16H17V8.75c0-.92-.7-1.67-1.6-1.74L15.24 7H8z"/></>),
  28: (<><path d="M8 2.75a.75.75 0 0 0-1.5 0V6.5H2.75a.75.75 0 0 0 0 1.5H6.5v9.75a3.75 3.75 0 0 0 3.75 3.75H20v3.75a.75.75 0 0 0 1.5 0V21.5h3.75a.75.75 0 0 0 0-1.5h-15C9.01 20 8 19 8 17.75zm12 7.5V19h1.5v-8.75a3.75 3.75 0 0 0-3.75-3.75H9V8h8.75C18.99 8 20 9 20 10.25"/></>),
  48: (<><path d="M14 5.25a1.25 1.25 0 1 0-2.5 0v6.25H5.25a1.25 1.25 0 1 0 0 2.5h6.25v16.25c0 3.45 2.8 6.25 6.25 6.25H34v6.25a1.25 1.25 0 1 0 2.5 0V36.5h6.25a1.25 1.25 0 1 0 0-2.5h-25A3.75 3.75 0 0 1 14 30.25zm20 12.5V32h2.5V17.75c0-3.45-2.8-6.25-6.25-6.25H16V14h14.25A3.75 3.75 0 0 1 34 17.75"/></>),
};
const SIZES = [16, 20, 24, 28, 48];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function CropIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
