// CrownSubtractIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M8.74 5.31 6.6 8.05a.5.5 0 0 1-.62.14L3.86 7.12q.15-.29.14-.62a1.5 1.5 0 1 0-1.8 1.47L3.88 16c.12.58.63.99 1.22.99H9.6q-.24-.48-.4-1H5.1a.25.25 0 0 1-.24-.2L3.2 7.91l2.34 1.17a1.5 1.5 0 0 0 1.86-.42L10 5.31l2.6 3.35q.27.34.65.48A6 6 0 0 1 14.62 9l2.18-1.09-.31 1.46q.48.2.92.46l.4-1.86a1.5 1.5 0 1 0-1.67-.85L14 8.2a.5.5 0 0 1-.62-.14L11.26 5.3q.23-.35.24-.81a1.5 1.5 0 1 0-2.76.8M14.5 19a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9M12 14.5c0-.28.22-.5.5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5"/></>),
  24: (<><path d="M13.46 6.37A2 2 0 0 0 12 3a2 2 0 0 0-1.46 3.37L7.92 9.65c-.07.1-.2.12-.3.07L4.95 8.39A2 2 0 0 0 3 6a2 2 0 0 0-.44 3.95l1.8 9.62c.16.83.88 1.43 1.72 1.43h5.94q-.45-.7-.7-1.5H6.07a.25.25 0 0 1-.25-.2L4.03 9.7l.1-.06 2.81 1.4c.74.38 1.64.18 2.15-.46L11.96 7h.08l2.87 3.59q.4.49.98.61.6-.15 1.27-.2l2.71-1.35.1.06-.32 1.65q.75.27 1.4.7l.4-2.11a2 2 0 1 0-2.41-1.56l-2.65 1.33a.25.25 0 0 1-.3-.07zM23 17.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0m-9 0c0 .28.22.5.5.5h6a.5.5 0 0 0 0-1h-6a.5.5 0 0 0-.5.5"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function CrownSubtractIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
