// CubeTreeIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M8.66 4.53a.5.5 0 0 0-.32.95l1.16.38V7a.5.5 0 0 0 1 0V5.86l1.16-.38a.5.5 0 1 0-.32-.95L10 4.97zm1.77-2.46a1.5 1.5 0 0 0-.86 0l-2.86.85a1 1 0 0 0-.71.95v4.26c0 .44.3.83.72.96l2.79.83-.01.08v1H8a2 2 0 0 0-2 2v.05a2.5 2.5 0 1 0 1 0V13a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1v.05a2.5 2.5 0 1 0 1 0V13a2 2 0 0 0-2-2h-1.5V9.92l2.78-.83a1 1 0 0 0 .72-.96V3.87a1 1 0 0 0-.72-.95zm-.57.95a.5.5 0 0 1 .28 0l2.86.85v4.26l-2.86.85a.5.5 0 0 1-.28 0L7 8.13V3.87zM5 15.5a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0m8.5-1.5a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3"/></>),
  24: (<><path d="M9.79 5.51c.13-.39.55-.6.95-.47l1.26.42 1.26-.42a.75.75 0 0 1 .48 1.42l-.99.33v.96a.75.75 0 0 1-1.5 0v-.96l-.99-.33a.75.75 0 0 1-.47-.95m2.45-3.47a.8.8 0 0 0-.48 0L8.01 3.29c-.3.1-.51.39-.51.71v5c0 .32.2.6.51.71l3.24 1.08V13H9.5c-1.24 0-2.25 1-2.25 2.25v.84a3 3 0 1 0 1.5 0v-.84c0-.41.34-.75.75-.75h5c.41 0 .75.34.75.75v.84a3 3 0 1 0 1.5 0v-.84c0-1.24-1-2.25-2.25-2.25h-1.75v-2.2l3.24-1.09c.3-.1.51-.39.51-.71V4c0-.32-.2-.6-.51-.71zM9 8.46V4.54l3-1 3 1v3.92l-3 1zM8 17.5a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3m6.5 1.5a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function CubeTreeIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
