// CursorProhibitedIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
};
const C = {
  16: (<><path d="M7 4.5a4.5 4.5 0 1 0 9 0 4.5 4.5 0 0 0-9 0m1 0a3.5 3.5 0 0 1 5.6-2.8L8.7 6.6A3.5 3.5 0 0 1 8 4.5M11.5 8c-.79 0-1.51-.26-2.1-.7l4.9-4.9A3.5 3.5 0 0 1 11.5 8m0 2h.47l-.02-.02q.52-.05 1-.17a1 1 0 0 1-.98 1.19H8.04a1 1 0 0 0-.8.39L4.8 14.57a1 1 0 0 1-1.79-.6V3.98a1 1 0 0 1 1.6-.8L6 4.25a6 6 0 0 0 .1 1.32L4 4v9.97l2.45-3.18A2 2 0 0 1 8.04 10h3.46"/></>),
  20: (<><path d="M10 5.5a4.5 4.5 0 1 0 9 0 4.5 4.5 0 0 0-9 0m1 0a3.5 3.5 0 0 1 5.6-2.8l-4.9 4.9a3.5 3.5 0 0 1-.7-2.1M14.5 9c-.79 0-1.51-.26-2.1-.7l4.9-4.9q.68.9.7 2.1A3.5 3.5 0 0 1 14.5 9m2.5 3.12-1.47-1.22q.6-.1 1.14-.35l.97.8a1 1 0 0 1-.63 1.77h-5.6c-.43 0-.85.2-1.13.52l-3.52 4.07A1 1 0 0 1 5 17.06v-14a1 1 0 0 1 1.64-.77l2.48 2.05Q9 4.9 9 5.5v.03L6 3.06v14l3.52-4.07a2.5 2.5 0 0 1 1.9-.87z"/></>),
};
const SIZES = [16, 20];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function CursorProhibitedIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
