// DatabaseArrowUpIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
};
const C = {
  16: (<><path d="M4 12.5V5.02A7.4 7.4 0 0 0 8 6a7.4 7.4 0 0 0 4-.98v1q.51.05 1 .19V3.5C13 2.08 10.85 1 8 1S3 2.08 3 3.5v9c0 1.3 1.78 2.3 4.24 2.47q-.4-.5-.7-1.08C4.97 13.63 4 12.98 4 12.5M8 2c2.44 0 4 .89 4 1.5S10.44 5 8 5s-4-.89-4-1.5S5.56 2 8 2m3.5 5a4.5 4.5 0 1 0 0 9 4.5 4.5 0 0 0 0-9m2.35 4.85a.5.5 0 0 1-.7 0L12 10.71v2.8a.5.5 0 0 1-1 0v-2.8l-1.14 1.14a.5.5 0 0 1-.71-.7l2-2A.5.5 0 0 1 11.5 9a.5.5 0 0 1 .36.15l2 2c.19.2.19.5 0 .7"/></>),
  20: (<><path d="M4 5c0-1 .88-1.76 1.9-2.22 1.3-.54 2.7-.8 4.1-.78 1.4-.03 2.8.24 4.1.78C15.13 3.24 16 3.99 16 5v4.2q-.49-.13-1-.18V6.7q-.42.3-.9.52c-1.3.54-2.7.8-4.1.78-1.4.03-2.8-.24-4.1-.78A5 5 0 0 1 5 6.7V15c0 .37.36.87 1.32 1.31A9 9 0 0 0 9.6 17q.27.55.66 1H10c-1.4.03-2.8-.24-4.1-.78C4.87 16.75 4 16.01 4 15zm1 0c0 .37.36.87 1.32 1.31A9 9 0 0 0 10 7a9 9 0 0 0 3.68-.69C14.64 5.87 15 5.37 15 5s-.36-.88-1.32-1.31A9 9 0 0 0 10 3a9 9 0 0 0-3.68.69C5.36 4.12 5 4.63 5 5m5 9.5a4.5 4.5 0 1 1 9 0 4.5 4.5 0 0 1-9 0m4.85-2.35a.5.5 0 0 0-.35-.15.5.5 0 0 0-.35.15l-2 2a.5.5 0 0 0 .7.7L14 13.71v2.79a.5.5 0 0 0 1 0v-2.8l1.15 1.15a.5.5 0 0 0 .7-.7z"/></>),
};
const SIZES = [16, 20];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DatabaseArrowUpIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
