// DatabaseArrowDownIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
};
const C = {
  20: (<><path d="M4 5c0-1 .88-1.76 1.9-2.22 1.3-.54 2.7-.8 4.1-.78 1.4-.03 2.8.24 4.1.78C15.13 3.24 16 3.99 16 5v4.2q-.49-.13-1-.18V6.7q-.42.3-.9.52c-1.3.54-2.7.8-4.1.78-1.4.03-2.8-.24-4.1-.78A5 5 0 0 1 5 6.7V15c0 .37.36.87 1.32 1.31A9 9 0 0 0 9.6 17q.27.55.66 1H10c-1.4.03-2.8-.24-4.1-.78C4.87 16.75 4 16.01 4 15zm1 0c0 .37.36.87 1.32 1.31A9 9 0 0 0 10 7a9 9 0 0 0 3.68-.69C14.64 5.87 15 5.37 15 5s-.36-.88-1.32-1.31A9 9 0 0 0 10 3a9 9 0 0 0-3.68.69C5.36 4.12 5 4.63 5 5m14 9.5a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0m-4.85 2.35a.5.5 0 0 0 .35.15.5.5 0 0 0 .35-.15l2-2a.5.5 0 0 0-.7-.7L15 15.29V12.5a.5.5 0 0 0-1 0v2.8l-1.15-1.15a.5.5 0 0 0-.7.7z"/></>),
};
const SIZES = [20];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DatabaseArrowDownIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
