// DataWaterfallIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M1 3.5c0-.28.22-.5.5-.5H7a2 2 0 0 1 2 2v4.5h6c1.04 0 2 .74 2 1.8V16h1.5a.5.5 0 0 1 0 1H13c-1.04 0-2-.74-2-1.8v-4.7H5a2 2 0 0 1-2-2V4H1.5a.5.5 0 0 1-.5-.5M4 4v4.5a1 1 0 0 0 1 1h3V5a1 1 0 0 0-1-1zm12 12v-4.7c0-.38-.38-.8-1-.8h-3v4.7c0 .38.38.8 1 .8z"/></>),
  24: (<><path d="M2 3.75c0-.41.34-.75.75-.75h6.5c1.24 0 2.25 1 2.25 2.25V11h6.25c1.24 0 2.25 1 2.25 2.25v6.25h1.25a.75.75 0 0 1 0 1.5h-6.5c-1.24 0-2.25-1-2.25-2.25V12.5H6.25c-1.24 0-2.25-1-2.25-2.25V4.5H2.75A.75.75 0 0 1 2 3.75M18.5 19.5v-6.25a.75.75 0 0 0-.75-.75H14v6.25c0 .41.34.75.75.75zM10 5.25a.75.75 0 0 0-.75-.75H5.5v5.75c0 .41.34.75.75.75H10z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DataWaterfallIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
