// DataBarVerticalEditIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M12.81 6.55a1.87 1.87 0 0 1 2.64 2.64l-4.82 4.83a2 2 0 0 1-1.03.58l-1.5.37a.9.9 0 0 1-1.07-1.07l.37-1.5q.15-.6.58-1.02zM3.5 8C4.33 8 5 8.67 5 9.5v3a1.5 1.5 0 0 1-3 0v-3C2 8.67 2.67 8 3.5 8m4-3C8.33 5 9 5.67 9 6.5v2.44l-1 1V6.5a.5.5 0 0 0-1 0v4.48a3 3 0 0 0-.57 1.18l-.26 1.04a1.5 1.5 0 0 1-.17-.7v-6C6 5.67 6.67 5 7.5 5m-4 4a.5.5 0 0 0-.5.5v3a.5.5 0 0 0 1 0v-3a.5.5 0 0 0-.5-.5m8-7c.83 0 1.5.67 1.5 1.5v1.73q-.5.21-.9.61l-.1.1V3.5a.5.5 0 0 0-1 0v3.44l-1 1V3.5c0-.83.67-1.5 1.5-1.5"/></>),
  20: (<><path d="M15.81 10.55a1.87 1.87 0 1 1 2.64 2.64l-4.82 4.83a2 2 0 0 1-1.03.58l-1.5.37a.9.9 0 0 1-1.07-1.07l.37-1.5q.16-.6.58-1.02zM5 9a2 2 0 0 1 2 2v4a2 2 0 1 1-4 0v-4c0-1.1.9-2 2-2m5-3a2 2 0 0 1 2 2v4.94l-1 1V8a1 1 0 1 0-2 0v7q.02.59.52.88l-.09.28-.17.7A2 2 0 0 1 8 15V8c0-1.1.9-2 2-2m-5 4a1 1 0 0 0-1 1v4a1 1 0 1 0 2 0v-4a1 1 0 0 0-1-1m10-7a2 2 0 0 1 2 2v4q-.52.03-1 .23V5a1 1 0 1 0-2 0v5.94l-1 1V5c0-1.1.9-2 2-2"/></>),
  24: (<><path d="M19.1 12.67a2.29 2.29 0 0 1 3.23 3.23l-5.9 5.9q-.53.54-1.25.71l-1.83.46c-.8.2-1.52-.52-1.32-1.32l.46-1.83q.18-.71.7-1.25zM5.25 11c1.24 0 2.25 1 2.25 2.25v5.5a2.25 2.25 0 0 1-4.5 0v-5.5C3 12 4 11 5.25 11m6.5-4C12.99 7 14 8 14 9.25v7.1l-1.5 1.5v-8.6a.75.75 0 1 0-1.5 0v9.5c0 .35.23.63.55.72q0 .06-.03.1l-.34 1.35a2.25 2.25 0 0 1-1.68-2.17v-9.5C9.5 8 10.5 7 11.75 7m-6.5 5.5a.75.75 0 0 0-.75.75v5.5a.75.75 0 0 0 1.5 0v-5.5a.75.75 0 0 0-.75-.75m13-9.5c1.24 0 2.25 1 2.25 2.25V11q-.8.05-1.5.48V5.25a.75.75 0 1 0-1.5 0v7.6l-1.5 1.5v-9.1C16 4 17 3 18.25 3"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DataBarVerticalEditIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
