// DataLineIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M13 6a2 2 0 1 0-1.5-.67L9.97 7.25a2 2 0 0 0-2.8 2.56l-2.5 1.08a2 2 0 1 0 .32.94l2.84-1.21a2 2 0 0 0 2.87-2.68l1.63-2.05A2 2 0 0 0 13 6m0-1a1 1 0 1 1 0-2 1 1 0 0 1 0 2m-9 7a1 1 0 1 1-2 0 1 1 0 0 1 2 0m6-3a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/></>),
  20: (<><path d="M15.5 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3M13 5.5a2.5 2.5 0 1 1 1.56 2.32l-1.29 1.92A2.5 2.5 0 0 1 11.5 14a2.5 2.5 0 0 1-2.05-1.08L6.95 14A2.5 2.5 0 0 1 4.5 17a2.5 2.5 0 1 1 2.05-3.92L9.05 12A2.5 2.5 0 0 1 11.5 9q.5 0 .94.18l1.29-1.92A2.5 2.5 0 0 1 13 5.5m-3 6a1.5 1.5 0 1 0 3 0 1.5 1.5 0 0 0-3 0m-7 3a1.5 1.5 0 1 0 3 0 1.5 1.5 0 0 0-3 0"/></>),
  24: (<><path d="M19 4.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3M16 6a3 3 0 1 1 2.52 2.96l-2.03 3.36q.5.74.51 1.68a3 3 0 0 1-5.26 1.97L8 17.84V18a3 3 0 1 1-.47-1.6l3.54-1.77A3 3 0 0 1 14 11q.73 0 1.34.32l1.8-2.97A3 3 0 0 1 16 6m-2 6.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3m-9 4a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DataLineIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
