// DecimalArrowLeftIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M8.5 3A2.5 2.5 0 0 0 6 5.5v4a2.5 2.5 0 0 0 5 0v-4A2.5 2.5 0 0 0 8.5 3M7 5.5a1.5 1.5 0 1 1 3 0v4a1.5 1.5 0 0 1-3 0zM3 12a1 1 0 1 0 0-2 1 1 0 0 0 0 2m12.5-9A2.5 2.5 0 0 0 13 5.5v3.7q.49-.13 1-.18V5.5a1.5 1.5 0 0 1 3 0v4.1q.48.24.9.58.1-.33.1-.68v-4A2.5 2.5 0 0 0 15.5 3m-1 16a4.5 4.5 0 1 1 0-9 4.5 4.5 0 0 1 0 9m-2.35-4.85a.5.5 0 0 0-.15.35.5.5 0 0 0 .15.35l2 2a.5.5 0 0 0 .7-.7L13.71 15h2.79a.5.5 0 0 0 0-1h-2.8l1.15-1.15a.5.5 0 0 0-.7-.7z"/></>),
  24: (<><path d="M10 4a3 3 0 0 0-3 3v4a3 3 0 1 0 6 0V7a3 3 0 0 0-3-3m1.5 7a1.5 1.5 0 0 1-3 0V7a1.5 1.5 0 1 1 3 0zM5 12.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0M19.5 7v4l-.03.3q.73.24 1.38.63A3 3 0 0 0 21 11V7a3 3 0 1 0-6 0v4q0 .25.04.48.7-.29 1.46-.4V7a1.5 1.5 0 0 1 3 0M23 17.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0m-2.5.5a.5.5 0 0 0 0-1h-4.8l1.65-1.65a.5.5 0 0 0-.7-.7l-2.5 2.5a.5.5 0 0 0 0 .7l2.5 2.5a.5.5 0 0 0 .7-.7L15.71 18z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DecimalArrowLeftIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
