// DesktopTowerIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M4 2a2 2 0 0 0-2 2v12c0 1.1.9 2 2 2h2.09a1.5 1.5 0 0 1 0-1H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h4a1 1 0 0 1 1 1h1a2 2 0 0 0-2-2zm1 5c0-1.1.9-2 2-2h9a2 2 0 0 1 2 2v6a2 2 0 0 1-2 2h-2v2h1.5a.5.5 0 0 1 0 1h-8a.5.5 0 0 1 0-1H9v-2H7a2 2 0 0 1-2-2zm5 10h3v-2h-3zm6-3a1 1 0 0 0 1-1V7a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1z"/></>),
  24: (<><path d="M4.25 2C3.01 2 2 3 2 4.25v15.5C2 20.99 3 22 4.25 22h4.42a1.7 1.7 0 0 1 0-1.5H4.25a.75.75 0 0 1-.75-.75V4.25c0-.41.34-.75.75-.75h5.5c.41 0 .75.34.75.75V6H12V4.25C12 3.01 11 2 9.75 2zM7 9.25C7 8.01 8 7 9.25 7h10.5C20.99 7 22 8 22 9.25v6.5c0 1.24-1 2.25-2.25 2.25H17.5v2.5h1.25a.75.75 0 0 1 0 1.5h-8.5a.75.75 0 0 1 0-1.5h1.25V18H9.25C8.01 18 7 17 7 15.75zm9 11.25V18h-3v2.5zm3.75-4c.41 0 .75-.34.75-.75v-6.5a.75.75 0 0 0-.75-.75H9.25a.75.75 0 0 0-.75.75v6.5c0 .41.34.75.75.75z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DesktopTowerIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
