// DesktopIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
  48: '0 0 48 48',
};
const C = {
  16: (<><path d="M4 2a2 2 0 0 0-2 2v6c0 1.1.9 2 2 2h2v1H4.5a.5.5 0 0 0 0 1h7a.5.5 0 1 0 0-1H10v-1h2a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2zm5 10v1H7v-1zM3 4a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v6a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z"/></>),
  20: (<><path d="M4 2a2 2 0 0 0-2 2v9c0 1.1.9 2 2 2h3v2H5.5a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1H13v-2h3a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2zm8 13v2H8v-2zM3 4a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v9a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1z"/></>),
  24: (<><path d="M6.75 22a.75.75 0 0 1-.1-1.5H8.5V18H4.25c-1.2 0-2.17-.92-2.24-2.1L2 15.76V5.25c0-1.2.93-2.17 2.1-2.24L4.25 3h15.5c1.19 0 2.16.93 2.24 2.1v10.65c0 1.2-.92 2.17-2.09 2.25h-4.4v2.5h1.75a.75.75 0 0 1 .1 1.5H6.75M14 18h-4v2.5h4zm5.75-13.5H4.25c-.38 0-.7.28-.74.65l-.01.1v10.5c0 .38.28.7.65.75h15.6c.38 0 .7-.28.74-.65V5.25c0-.38-.27-.7-.64-.74z"/></>),
  28: (<><path d="M19.75 25H8.25a.75.75 0 0 1-.1-1.5H10V21H4.25C3.01 21 2 20 2 18.75V5.25C2 4.01 3 3 4.25 3h19.5C24.99 3 26 4 26 5.25v13.5C26 20 25 21 23.75 21H18v2.5h1.75c.38 0 .7.28.74.65l.01.1c0 .38-.28.7-.65.74zH8.25zm-3.25-4h-5v2.5h5zm7.25-16.5H4.25a.75.75 0 0 0-.75.75v13.5c0 .42.34.75.75.75h19.5c.41 0 .75-.33.75-.75V5.25a.75.75 0 0 0-.75-.75"/></>),
  48: (<><path d="M8.25 5A4.25 4.25 0 0 0 4 9.25v23.5C4 35.1 5.9 37 8.25 37H17v3.5h-2.75a1.25 1.25 0 1 0 0 2.5h19.5a1.25 1.25 0 1 0 0-2.5H31V37h8.75C42.1 37 44 35.1 44 32.75V9.25C44 6.9 42.1 5 39.75 5zM28.5 37v3.5h-9V37zM6.5 9.25c0-.97.78-1.75 1.75-1.75h31.5c.97 0 1.75.78 1.75 1.75v23.5c0 .97-.78 1.75-1.75 1.75H8.25c-.97 0-1.75-.78-1.75-1.75z"/></>),
};
const SIZES = [16, 20, 24, 28, 48];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DesktopIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
