// DesktopMacIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M2 4c0-1.1.9-2 2-2h8a2 2 0 0 1 2 2v6a2 2 0 0 1-2 2h-2v.5c0 .28.22.5.5.5h.5a.5.5 0 0 1 0 1H5a.5.5 0 0 1 0-1h.5a.5.5 0 0 0 .5-.5V12H4a2 2 0 0 1-2-2zm1 6a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1zm10-1V4a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v5zm-4 3.5V12H7v.5q0 .26-.09.5H9.1a2 2 0 0 1-.09-.5"/></>),
  20: (<><path d="M2 4c0-1.1.9-2 2-2h12a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2h-4v1a1 1 0 0 0 1 1h.5a.5.5 0 0 1 0 1h-7a.5.5 0 0 1 0-1H7a1 1 0 0 0 1-1v-1H4a2 2 0 0 1-2-2zm1 8v1a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-1zm14-1V4a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v7zm-5.73 6a2 2 0 0 1-.27-1v-1H9v1a2 2 0 0 1-.27 1z"/></>),
  24: (<><path d="M4.25 3C3.01 3 2 4 2 5.25v10.5C2 16.99 3 18 4.25 18H9.5v1.25c0 .69-.56 1.25-1.25 1.25h-.5a.75.75 0 0 0 0 1.5h8.5a.75.75 0 0 0 0-1.5h-.5c-.69 0-1.25-.56-1.25-1.25V18h5.25c1.24 0 2.25-1 2.25-2.25V5.25C22 4.01 21 3 19.75 3zM13 18v1.25q0 .68.3 1.25h-2.6q.3-.57.3-1.25V18zM3.5 5.25c0-.41.34-.75.75-.75h15.5c.41 0 .75.34.75.75V13h-17zm0 9.25h17v1.25c0 .41-.34.75-.75.75H4.25a.75.75 0 0 1-.75-.75z"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DesktopMacIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
