// DeveloperBoardSearchIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M8 9a3 3 0 1 1 6 0 3 3 0 0 1-6 0m3-2a2 2 0 1 0 0 4 2 2 0 0 0 0-4M9 1.5a.5.5 0 0 0-1 0V3h-.5A2.5 2.5 0 0 0 5 5.5V6H3.5a.5.5 0 0 0 0 1H5v1.5H3.5a.5.5 0 0 0-.44.74A4.5 4.5 0 0 1 6 9.26V5.5C6 4.67 6.67 4 7.5 4h7c.83 0 1.5.67 1.5 1.5v7c0 .83-.67 1.5-1.5 1.5H8.97q-.05.52-.23 1h1.76v1.5a.5.5 0 0 0 1 0V15H13v1.5a.5.5 0 0 0 1 0V15h.5a2.5 2.5 0 0 0 2.5-2.5V12h1.5a.5.5 0 0 0 0-1H17V9.5h1.5a.5.5 0 0 0 0-1H17V7h1.5a.5.5 0 0 0 0-1H17v-.5A2.5 2.5 0 0 0 14.5 3H14V1.5a.5.5 0 0 0-1 0V3h-1.5V1.5a.5.5 0 0 0-1 0V3H9zM4.5 17q1.2-.02 2.1-.7l2.55 2.55a.5.5 0 0 0 .7-.7L7.3 15.6q.68-.9.7-2.1A3.5 3.5 0 1 0 4.5 17m0-1a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5"/></>),
  24: (<><path d="M17 1.65a.75.75 0 0 0-.75-.65h-.1l-.1.03a.75.75 0 0 0-.55.72V4h-1.75V1.65A.75.75 0 0 0 13 1h-.1a.75.75 0 0 0-.65.75V4H10.5V1.65a.75.75 0 0 0-1.5.1v2.32A3.8 3.8 0 0 0 6.08 7H3.65a.75.75 0 0 0-.65.75v.1c.06.37.37.65.75.65H6v1.75H3.65A.75.75 0 0 0 3 11v.1q.05.25.2.4a5.5 5.5 0 0 1 4.3-.13V7.75c0-1.24 1-2.25 2.25-2.25h6.5c1.24 0 2.25 1 2.25 2.25v6.5c0 1.24-1 2.25-2.25 2.25H11a6 6 0 0 1-.2 1.5h1.45v2.35c.06.37.37.65.75.65h.1a.75.75 0 0 0 .65-.75V18h1.75v2.35a.75.75 0 0 0 1.5-.1v-2.33A3.8 3.8 0 0 0 19.92 15h2.43a.75.75 0 0 0 .65-.75v-.1a.75.75 0 0 0-.75-.65H20v-1.75h2.35A.75.75 0 0 0 23 11v-.1a.75.75 0 0 0-.75-.65H20V8.5h2.35a.75.75 0 0 0-.1-1.5h-2.32A3.8 3.8 0 0 0 17 4.08V1.65M16 11a3 3 0 1 0-6 0 3 3 0 0 0 6 0m-4.5 0a1.5 1.5 0 1 1 3 0 1.5 1.5 0 0 1-3 0m-6 10c.97 0 1.87-.3 2.6-.83l2.62 2.61a.75.75 0 1 0 1.06-1.06l-2.61-2.61A4.5 4.5 0 1 0 5.5 21m0-1.5a3 3 0 1 1 0-6 3 3 0 0 1 0 6"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DeveloperBoardSearchIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
