// DocumentFooterDismissIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M19 5.5a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0m-2.65-1.15a.5.5 0 0 0-.7-.7L14.5 4.79l-1.15-1.14a.5.5 0 0 0-.7.7l1.14 1.15-1.14 1.15a.5.5 0 0 0 .7.7l1.15-1.14 1.15 1.14a.5.5 0 0 0 .7-.7L15.21 5.5zM15 16v-5.02q.51-.05 1-.19V16a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V4c0-1.1.9-2 2-2h4.26q-.39.46-.66 1H6a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1m-8-2a1 1 0 1 0 0 2h6a1 1 0 1 0 0-2z"/></>),
  24: (<><path d="M23 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0m-7.15-2.35a.5.5 0 1 0-.7.7l1.64 1.65-1.64 1.65a.5.5 0 0 0 .7.7l1.65-1.64 1.65 1.64a.5.5 0 1 0 .7-.7L18.21 6.5l1.64-1.65a.5.5 0 1 0-.7-.7L17.5 5.79zm2.65 15.6v-6.83a7 7 0 0 0 1.5-.42v7.24c0 1.2-.93 2.17-2.1 2.25H6.25c-1.2 0-2.17-.92-2.25-2.1V4.25C4 3.06 4.92 2.09 6.1 2h6.71q-.64.66-1.07 1.5h-5.5c-.37 0-.69.28-.74.64v15.6c0 .38.28.7.64.75h11.6c.39 0 .7-.28.75-.64zM8.5 16a1.5 1.5 0 0 0 0 3h7a1.5 1.5 0 0 0 0-3z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DocumentFooterDismissIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
