// DocumentPageTopCenterIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M8.07 9.44a.5.5 0 1 0 1 .15L9.14 9h1.24l-.07.44a.5.5 0 1 0 1 .15L11.4 9h.6a.5.5 0 0 0 0-1h-.46l.22-1.5h.74a.5.5 0 0 0 0-1h-.59l.14-.93a.5.5 0 0 0-1-.14L10.9 5.5H9.66l.14-.93a.5.5 0 0 0-1-.14L8.66 5.5H8a.5.5 0 0 0 0 1h.5L8.28 8H7.5a.5.5 0 0 0 0 1h.64zm2.68-2.94L10.53 8H9.3l.22-1.5zM6 2a2 2 0 0 0-2 2v12c0 1.1.9 2 2 2h8a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2zm0 1h8a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1"/></>),
  24: (<><path d="M17.74 2c1.2 0 2.17.92 2.25 2.1v15.65c0 1.18-.92 2.16-2.1 2.24H6.25c-1.19 0-2.16-.92-2.24-2.1V4.25C4 3.07 4.91 2.09 6.08 2h11.65m0 1.5H6.24c-.38 0-.69.28-.74.64v15.6c0 .38.28.7.64.75h11.6c.38 0 .7-.28.75-.64V4.25c0-.38-.28-.7-.64-.75zM13.02 12a.75.75 0 0 1-.63-.86l.1-.66h-1.47l-.14.9a.75.75 0 1 1-1.49-.24l.1-.66h-.74a.75.75 0 0 1 0-1.5h.99l.23-1.5h-.72a.75.75 0 1 1 0-1.5h.96l.2-1.26a.75.75 0 1 1 1.48.24l-.16 1.02h1.48l.2-1.26a.75.75 0 1 1 1.48.24l-.16 1.02h.52a.75.75 0 0 1 0 1.5h-.76l-.23 1.5h.49a.75.75 0 0 1 0 1.5h-.73l-.14.9a.75.75 0 0 1-.86.62m-1.53-4.52-.23 1.5h1.48l.23-1.5z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DocumentPageTopCenterIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
