// DocumentHeaderArrowDownIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M4.75 1C3.78 1 3 1.78 3 2.75v10.5c0 .97.78 1.75 1.75 1.75h2.59q-.6-.42-1.08-1H4.75a.75.75 0 0 1-.75-.75V2.75c0-.41.34-.75.75-.75h6.5c.41 0 .75.34.75.75v2.46q.52.15 1 .39V2.75C13 1.78 12.22 1 11.25 1zM6 3a1 1 0 0 0 0 2h4a1 1 0 1 0 0-2zm9 7.5a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0m-4.85 2.35a.5.5 0 0 0 .35.15.5.5 0 0 0 .35-.15l2-2a.5.5 0 0 0-.7-.7L11 11.29V8.5a.5.5 0 0 0-1 0v2.8l-1.15-1.15a.5.5 0 0 0-.7.7z"/></>),
  20: (<><path d="M6 2a2 2 0 0 0-2 2v12c0 1.1.9 2 2 2h4.26a6 6 0 0 1-.66-1H6a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v5.02q.51.05 1 .19V4a2 2 0 0 0-2-2zm1 2a1 1 0 0 0 0 2h6a1 1 0 1 0 0-2zm12 10.5a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0m-4.85 2.35a.5.5 0 0 0 .35.15.5.5 0 0 0 .35-.15l2-2a.5.5 0 0 0-.7-.7L15 15.29V12.5a.5.5 0 0 0-1 0v2.8l-1.15-1.15a.5.5 0 0 0-.7.7z"/></>),
  24: (<><path d="M8.5 5a1.5 1.5 0 0 0 0 3h7a1.5 1.5 0 0 0 0-3zM20 4.1A2.25 2.25 0 0 0 17.74 2H6.1A2.25 2.25 0 0 0 4 4.26V19.9A2.25 2.25 0 0 0 6.26 22h6.56a7 7 0 0 1-1.08-1.5H6.15a.75.75 0 0 1-.65-.75V4.15a.75.75 0 0 1 .75-.65h11.6c.37.06.65.37.65.75v6.83q.79.12 1.5.42V4.1m3 13.4a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0m-5-3a.5.5 0 0 0-1 0v4.8l-1.65-1.65a.5.5 0 0 0-.7.7l2.5 2.5c.2.2.5.2.7 0l2.5-2.5a.5.5 0 0 0-.7-.7L18 19.29z"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DocumentHeaderArrowDownIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
