// DocumentTableSearchIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M6.44 9.44A1.5 1.5 0 0 1 7.5 9h5c.83 0 1.5.67 1.5 1.5v4c0 .83-.67 1.5-1.5 1.5H9.12l-.56-.56q.43-.9.44-1.94V15h3.5a.5.5 0 0 0 .5-.5V13H9v.5c0-1.07-.37-2.06-1-2.83V10h-.5l-.15.02a5 5 0 0 0-.91-.58M13 10.5a.5.5 0 0 0-.5-.5H9v2h4zM5 9.03a5 5 0 0 0-1 0V4c0-1.1.9-2 2-2h4.59q.62.01 1.06.44l3.91 3.91c.28.28.44.67.44 1.06V16a2 2 0 0 1-2 2h-3.09a2 2 0 0 0-.35-.56l-.44-.44H14a1 1 0 0 0 1-1V8h-3.5A1.5 1.5 0 0 1 10 6.5V3H6a1 1 0 0 0-1 1zM11.5 7h3.3L11 3.2v3.3c0 .28.22.5.5.5m-4.2 8.6q.68-.9.7-2.1a3.5 3.5 0 1 0-1.4 2.8l2.55 2.55a.5.5 0 1 0 .7-.7zM7 13.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0"/></>),
  24: (<><path d="M15.25 11.5c.97 0 1.75.78 1.75 1.75v4c0 .97-.78 1.75-1.75 1.75h-4.78l-.04-.05a5.5 5.5 0 0 0-.43-5.61V13h-.26a6 6 0 0 0-1.67-1.36q.32-.15.68-.14zM11.5 16v1.5h3.75q.23-.02.25-.25V16zm4-1.5v-1.25a.25.25 0 0 0-.25-.25H11.5v1.5zm2.5 6h-6.03l.52.51q.41.43.5.99H18a2 2 0 0 0 2-2V9.83a2 2 0 0 0-.59-1.42L13.6 2.6A2 2 0 0 0 12.17 2H6a2 2 0 0 0-2 2v7.2q.72-.2 1.5-.2V4c0-.27.22-.5.5-.5h6V8c0 1.1.9 2 2 2h4.5v10a.5.5 0 0 1-.5.5m-.62-12H14a.5.5 0 0 1-.5-.5V4.62zM5.5 21c.97 0 1.87-.3 2.6-.83l2.62 2.61a.75.75 0 1 0 1.06-1.06l-2.61-2.61A4.5 4.5 0 1 0 5.5 21m0-1.5a3 3 0 1 1 0-6 3 3 0 0 1 0 6"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DocumentTableSearchIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
