// DocumentMarkdownIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
};
const C = {
  16: (<><path d="M5.62 10.01a.5.5 0 0 1 .38.49v4a.5.5 0 0 1-1 0v-1.88l-1.02 2.04-.02.04-.01.02a.5.5 0 0 1-.9 0L2 12.62v1.88a.5.5 0 0 1-1 0v-4a.5.5 0 0 1 .95-.22l1.55 3.1 1.55-3.1a.5.5 0 0 1 .57-.27M9 10c.28 0 .5.22.5.5v2.8l.65-.65a.5.5 0 1 1 .7.7l-1.5 1.5-.11.09a.5.5 0 0 1-.34.05l-.14-.05-.11-.09-1.5-1.5a.5.5 0 1 1 .7-.7l.65.64V10.5c0-.28.22-.5.5-.5m-.41-9q.62.01 1.06.44l2.91 2.91c.28.28.44.67.44 1.06V13a2 2 0 0 1-2 2h-.38l.94-.94c.28-.28.43-.65.44-1.02V6H9.5A1.5 1.5 0 0 1 8 4.5V2H5a1 1 0 0 0-1 1v7.15l-.5 1-.5-1V3c0-1.1.9-2 2-2zM9 4.5c0 .28.22.5.5.5h2.3L9 2.2z"/></>),
  20: (<><path d="M6.62 12.01a.5.5 0 0 1 .38.49v5a.5.5 0 0 1-1 0v-2.88l-1.55 3.1a.5.5 0 0 1-.9 0L2 14.62v2.88a.5.5 0 0 1-1 0v-5a.5.5 0 0 1 .95-.22L4 16.38l.03-.06 2.02-4.04a.5.5 0 0 1 .57-.27M10.5 12c.28 0 .5.22.5.5v3.8l1.15-1.15a.5.5 0 1 1 .7.7l-2 2-.11.09a.5.5 0 0 1-.34.05l-.14-.05-.11-.09-2-2a.5.5 0 1 1 .7-.7L10 16.29V12.5c0-.28.22-.5.5-.5m.09-10c.4 0 .78.16 1.06.44l3.91 3.91c.28.28.44.67.44 1.06V16a2 2 0 0 1-2 2h-1.88l1-1H14a1 1 0 0 0 1-1V8h-3.5A1.5 1.5 0 0 1 10 6.5V3H6a1 1 0 0 0-1 1v8.15l-1 2V4c0-1.1.9-2 2-2zM11 6.5c0 .28.22.5.5.5h3.3L11 3.2z"/></>),
};
const SIZES = [16, 20];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DocumentMarkdownIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
