// DocumentSettingsIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
};
const C = {
  16: (<><path d="M6 1a2 2 0 0 0-2 2v2.2q.48-.13 1-.18V3a1 1 0 0 1 1-1h3v2.5c0 .83.67 1.5 1.5 1.5H13v7a1 1 0 0 1-1 1H9.74q-.47.58-1.08 1H12a2 2 0 0 0 2-2V5.41c0-.4-.16-.78-.44-1.06l-2.91-2.91A1.5 1.5 0 0 0 9.59 1zm6.8 4h-2.3a.5.5 0 0 1-.5-.5V2.2zM1.62 9.92a2 2 0 0 0 1.43-2.48l-.15-.55q.38-.3.82-.5l.34.36a2 2 0 0 0 2.9 0l.33-.35q.45.21.84.52L8 7.34a2 2 0 0 0 1.46 2.52l.35.09a5 5 0 0 1 0 1.01l-.45.12a2 2 0 0 0-1.44 2.48l.16.55q-.38.3-.82.5l-.34-.36a2 2 0 0 0-2.9 0l-.33.35q-.45-.21-.84-.52l.13-.42a2 2 0 0 0-1.46-2.52l-.35-.09a5 5 0 0 1 0-1.01zm4.87.58a1 1 0 1 0-2 0 1 1 0 0 0 2 0"/></>),
  20: (<><path d="M6 2a2 2 0 0 0-2 2v4.2q.49-.13 1-.18V4a1 1 0 0 1 1-1h4v3.5c0 .83.67 1.5 1.5 1.5H15v8a1 1 0 0 1-1 1H9.74q-.47.57-1.08 1H14a2 2 0 0 0 2-2V7.41c0-.4-.16-.78-.44-1.06l-3.91-3.91A1.5 1.5 0 0 0 10.59 2zm8.8 5h-3.3a.5.5 0 0 1-.5-.5V3.2zM3.05 10.44a2 2 0 0 1-1.43 2.48l-.46.12a5 5 0 0 0 .01 1.01l.35.09A2 2 0 0 1 3 16.66l-.13.42q.39.3.84.52l.32-.35a2 2 0 0 1 2.91 0l.34.36q.45-.2.82-.5l-.16-.55a2 2 0 0 1 1.44-2.48l.46-.12a5 5 0 0 0-.01-1.01l-.35-.09A2 2 0 0 1 8 10.34l.13-.42q-.39-.3-.84-.52l-.32.35a2 2 0 0 1-2.91 0l-.34-.36q-.45.2-.82.5zM5.5 14.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2"/></>),
};
const SIZES = [16, 20];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DocumentSettingsIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
