// DocumentEndnoteIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M6 2a2 2 0 0 0-2 2v6h1V4a1 1 0 0 1 1-1h4v3.5c0 .83.67 1.5 1.5 1.5H15v8a1 1 0 0 1-1 1h-3v1h3a2 2 0 0 0 2-2V7.41c0-.4-.16-.78-.44-1.06l-3.91-3.91A1.5 1.5 0 0 0 10.59 2zm8.8 5h-3.3a.5.5 0 0 1-.5-.5V3.2zM3.5 11a.5.5 0 0 1 0 1h-1a.5.5 0 0 0-.5.5v5c0 .28.22.5.5.5h1a.5.5 0 0 1 0 1h-1A1.5 1.5 0 0 1 1 17.5v-5c0-.83.67-1.5 1.5-1.5zm4 7a.5.5 0 0 0 0 1h1c.83 0 1.5-.67 1.5-1.5v-5c0-.83-.67-1.5-1.5-1.5h-1a.5.5 0 0 0 0 1h1c.28 0 .5.22.5.5v5a.5.5 0 0 1-.5.5zm-2-4c.27 0 .5.22.5.5v3a.5.5 0 1 1-1 0v-3c0-.28.22-.5.5-.5m0-1a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1"/></>),
  24: (<><path d="M5.5 4.25c0-.41.34-.75.75-.75H12V8c0 1.1.9 2 2 2h4.5v9.75c0 .41-.34.75-.75.75H13V22h4.75c1.24 0 2.25-1 2.25-2.25V9.66c0-.46-.18-.9-.51-1.23L13.57 2.5A1.8 1.8 0 0 0 12.34 2H6.25C5.01 2 4 3 4 4.25V12h1.5zm8 3.75V4.56l3.94 3.94H14a.5.5 0 0 1-.5-.5m-9 5.75c0 .41-.34.75-.75.75H2.5v7h1.25a.75.75 0 0 1 0 1.5H2.5A1.5 1.5 0 0 1 1 21.5v-7c0-.83.67-1.5 1.5-1.5h1.25c.41 0 .75.34.75.75m4.75.75a.75.75 0 0 1 0-1.5h1.25c.83 0 1.5.67 1.5 1.5v7c0 .83-.67 1.5-1.5 1.5H9.25a.75.75 0 0 1 0-1.5h1.25v-7zM6.5 16.75c.41 0 .75.34.75.75V21a.75.75 0 0 1-1.5 0v-3.5c0-.41.34-.75.75-.75m0-.75a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DocumentEndnoteIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
