// DocumentFooterIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M6 11a1 1 0 1 0 0 2h4a1 1 0 1 0 0-2zM4.75 1C3.78 1 3 1.78 3 2.75v10.5c0 .97.78 1.75 1.75 1.75h6.5c.97 0 1.75-.78 1.75-1.75V2.75C13 1.78 12.22 1 11.25 1zM4 2.75c0-.41.34-.75.75-.75h6.5c.41 0 .75.34.75.75v10.5c0 .41-.34.75-.75.75h-6.5a.75.75 0 0 1-.75-.75z"/></>),
  20: (<><path d="M6 2a2 2 0 0 0-2 2v12c0 1.1.9 2 2 2h8a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2zM5 4a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1zm2 10a1 1 0 1 0 0 2h6a1 1 0 1 0 0-2z"/></>),
  24: (<><path d="M8.5 16a1.5 1.5 0 1 0 0 3h7a1.5 1.5 0 0 0 0-3zM20 4.1A2.25 2.25 0 0 0 17.74 2H6.09A2.25 2.25 0 0 0 4 4.25v15.5l.01.15A2.25 2.25 0 0 0 6.25 22h11.5l.15-.01a2.25 2.25 0 0 0 2.1-2.25V4.1M6.24 3.5h11.6c.36.05.65.37.65.75v15.5l-.01.1a.75.75 0 0 1-.74.64H6.15a.75.75 0 0 1-.65-.75V4.14a.75.75 0 0 1 .75-.64"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DocumentFooterIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
