// DocumentFsIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
};
const C = {
  16: (<><path d="m13.56 4.35-2.91-2.91A1.5 1.5 0 0 0 9.59 1H6a2 2 0 0 0-2 2v5.83c.42.13.78.4 1 .79V3a1 1 0 0 1 1-1h3v2.5A1.5 1.5 0 0 0 10.5 6H13v7a1 1 0 0 1-1 1h-.83q-.21.65-.8 1H12a2 2 0 0 0 2-2V5.41q-.01-.61-.44-1.06M10.5 5a.5.5 0 0 1-.5-.5V2.2L12.8 5zm-1 8H9v-1h.5a.5.5 0 0 0 0-1H9v-.5a.5.5 0 0 0-1 0v.5H7v-.5a.5.5 0 0 0-1 0v.5h-.5a.5.5 0 0 0 0 1H6l.01 1H5.5a.5.5 0 0 0 0 1h.52v.5a.5.5 0 0 0 1 0V14H8v.5a.5.5 0 0 0 1 0V14h.5a.5.5 0 0 0 0-1M8 13h-.99v-1H8zm-4.15-2.15A.5.5 0 0 0 3.5 10h-2a.5.5 0 0 0-.5.5v4a.5.5 0 0 0 1 0V13h1a.5.5 0 0 0 0-1H2v-1h1.5a.5.5 0 0 0 .35-.15"/></>),
};
const SIZES = [16];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DocumentFsIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
