// DoorTagIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M9.3 6.3A1 1 0 1 1 10 8H7a2 2 0 0 0-2 2v6c0 1.1.9 2 2 2h6a2 2 0 0 0 2-2V7.05a4.98 4.98 0 0 0-8.54-3.59A2 2 0 1 0 9.3 6.3M11.4 8.4A2 2 0 1 0 8.6 5.6a1 1 0 0 1-1.42-1.42A4 4 0 0 1 14 7V16a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1v-6a1 1 0 0 1 1-1h3a2 2 0 0 0 1.41-.59M8 14a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1z"/></>),
  24: (<><path d="M9.75 17.5a.75.75 0 0 0 0 1.5h4.5a.75.75 0 0 0 0-1.5zM10.8 7.1A1.5 1.5 0 1 1 12 9.5H8a2 2 0 0 0-2 2V20c0 1.1.9 2 2 2h8a2 2 0 0 0 2-2V8A6 6 0 0 0 7.2 4.4a2.25 2.25 0 1 0 3.6 2.7M12 5a3 3 0 0 0-2.4 1.2.75.75 0 0 1-1.2-.9A4.5 4.5 0 0 1 16.5 8v12a.5.5 0 0 1-.5.5H8a.5.5 0 0 1-.5-.5v-8.5c0-.28.22-.5.5-.5h4a3 3 0 1 0 0-6"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DoorTagIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
