// DoorArrowLeftIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M4.75 1C3.78 1 3 1.78 3 2.75v10.5c0 .97.78 1.75 1.75 1.75h2.5a6 6 0 0 1-.65-1H4.75a.75.75 0 0 1-.75-.75V2.75c0-.41.34-.75.75-.75h6.5c.41 0 .75.34.75.75v3.27q.51.05 1 .19V2.75C13 1.78 12.22 1 11.25 1zM7 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0m9 3.5a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0m-6.85-.35a.5.5 0 0 0-.15.35.5.5 0 0 0 .15.35l2 2a.5.5 0 0 0 .7-.7L10.71 12h2.79a.5.5 0 0 0 0-1h-2.8l1.15-1.15a.5.5 0 0 0-.7-.7z"/></>),
  20: (<><path d="M6 2a2 2 0 0 0-2 2v12c0 1.1.9 2 2 2h4.26a6 6 0 0 1-.66-1H6a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v5.02q.51.05 1 .19V4a2 2 0 0 0-2-2zm2 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0m11 4.5a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0m-6.85-.35a.5.5 0 0 0-.15.35.5.5 0 0 0 .15.35l2 2a.5.5 0 0 0 .7-.7L13.71 15h2.79a.5.5 0 0 0 0-1h-2.8l1.15-1.15a.5.5 0 0 0-.7-.7z"/></>),
  24: (<><path d="M6.25 2C5.01 2 4 3 4 4.25v15.5C4 20.99 5 22 6.25 22h6.56a7 7 0 0 1-1.08-1.5H6.25a.75.75 0 0 1-.75-.75V4.25c0-.41.34-.75.75-.75h11.5c.41 0 .75.34.75.75v6.83q.79.12 1.5.42V4.25C20 3.01 19 2 17.75 2zM17.5 23a5.5 5.5 0 1 0 0-11 5.5 5.5 0 0 0 0 11m3.5-5.5a.5.5 0 0 1-.5.5h-4.8l1.65 1.65a.5.5 0 0 1-.7.7l-2.5-2.5a.5.5 0 0 1 0-.7l2.5-2.5a.5.5 0 0 1 .7.7L15.71 17h4.79c.28 0 .5.22.5.5M8.5 13.25a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DoorArrowLeftIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
