// DoubleSwipeUpIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M5.85 2.15a.5.5 0 0 0-.7 0l-3 3a.5.5 0 1 0 .7.7L5 3.71V14.5a.5.5 0 0 0 1 0V3.7l2.15 2.15a.5.5 0 1 0 .7-.7zm9 0a.5.5 0 0 0-.7 0l-3 3a.5.5 0 0 0 .7.7L14 3.71V14.5a.5.5 0 0 0 1 0V3.7l2.15 2.15a.5.5 0 0 0 .7-.7zM11 14.5c0-1.4.82-2.6 2-3.16v1.16a2.5 2.5 0 1 0 3 0v-1.16a3.5 3.5 0 1 1-5 3.16m-7-3.16a3.5 3.5 0 1 0 3 0v1.16a2.5 2.5 0 1 1-3 0z"/></>),
  24: (<><path d="M6.75 18c.38 0 .7-.28.74-.65l.01-.1V4.56l2.22 2.22c.27.27.68.3.98.07l.08-.07a.75.75 0 0 0 .07-.98l-.07-.08-3.5-3.5a.75.75 0 0 0-.98-.07l-.08.07-3.5 3.5a.75.75 0 0 0 .98 1.13l.08-.07L6 4.56v12.69c0 .41.34.75.75.75m10.5 0c.38 0 .7-.28.74-.65V4.56l2.23 2.22c.26.27.68.3.97.07l.09-.07c.26-.27.29-.68.07-.98l-.07-.08-3.5-3.5a.75.75 0 0 0-.98-.07l-.08.07-3.5 3.5a.75.75 0 0 0 .97 1.13l.09-.07 2.22-2.22v12.69c0 .41.33.75.75.75m-10.5 4a4.75 4.75 0 0 0 1.75-9.17v1.68a3.25 3.25 0 1 1-3.5 0v-1.68A4.75 4.75 0 0 0 6.75 22m10.5 0A4.75 4.75 0 0 0 19 12.83v1.68a3.25 3.25 0 1 1-3.5 0v-1.68A4.75 4.75 0 0 0 17.25 22"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DoubleSwipeUpIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
