// DrawerAddIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M13.5 10a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9m0-7c.28 0 .5.22.5.5V5h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V6h-1.5a.5.5 0 0 1 0-1H13V3.5c0-.28.22-.5.5-.5M17 9.74V15a3 3 0 0 1-3 3H6a3 3 0 0 1-3-3V7a3 3 0 0 1 3-3h2.2q-.13.49-.18 1H6a2 2 0 0 0-2 2h4.2q.16.52.4 1H4v3h3.5c.28 0 .5.22.5.5a2 2 0 1 0 4 0c0-.28.22-.5.5-.5H16v-.6q.54-.27 1-.66M14 17a2 2 0 0 0 2-2v-3h-3.04a3 3 0 0 1-5.92 0H4v3c0 1.1.9 2 2 2z"/></>),
  24: (<><path d="M22 6.5a5.5 5.5 0 1 0-11 0 5.5 5.5 0 0 0 11 0M17 7v2.5a.5.5 0 1 1-1 0V7h-2.5a.5.5 0 0 1 0-1H16V3.5a.5.5 0 0 1 1 0V6h2.5a.5.5 0 0 1 0 1zm4 4.19q-.67.65-1.5 1.08V14h-4.56a.7.7 0 0 0-.69.7v.05a2.25 2.25 0 0 1-4.5 0v-.06a.7.7 0 0 0-.7-.69H4.5V9.5h6.23a7 7 0 0 1-.56-1.5H4.5v-.75c0-.97.78-1.75 1.75-1.75h3.83q.12-.79.42-1.5H6.25A3.25 3.25 0 0 0 3 7.25v11.5C3 20.55 4.46 22 6.25 22h11.5c1.8 0 3.25-1.46 3.25-3.25zm-1.5 4.31v3.25c0 .97-.78 1.75-1.75 1.75H6.25c-.97 0-1.75-.78-1.75-1.75V15.5h3.83a3.75 3.75 0 0 0 7.35 0z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DrawerAddIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
