// DrinkWineIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M10.73 6.3a.5.5 0 0 0-1-.1A1.75 1.75 0 0 1 8.36 7.7a.5.5 0 0 0 .2.98 2.75 2.75 0 0 0 2.18-2.39M4.5 1a.5.5 0 0 0-.5.5v5a4 4 0 0 0 3.5 3.97V14H6a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1H8.5v-3.53A4 4 0 0 0 12 6.5v-5a.5.5 0 0 0-.5-.5zM5 4V2h6v2zm0 1h6v1.5a3 3 0 0 1-6 0z"/></>),
  20: (<><path d="M13.45 8.08a.5.5 0 0 0-.98-.17 2.5 2.5 0 0 1-2.05 2.05.5.5 0 0 0 .16 1 3.5 3.5 0 0 0 2.87-2.88M5.5 2a.5.5 0 0 0-.5.5V8a5 5 0 0 0 4.5 5v4h-2a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1h-2v-4.02A5 5 0 0 0 15 8V2.5a.5.5 0 0 0-.5-.5zM6 5.5V3h8v2.5zm0 1h8V8a4 4 0 0 1-8 0z"/></>),
  24: (<><path d="M15.93 9.75a.75.75 0 0 0-1.47-.28 2.5 2.5 0 0 1-1.95 1.98.75.75 0 1 0 .31 1.47 4 4 0 0 0 3.1-3.17M6 2.75c0-.41.34-.75.75-.75h10.5c.41 0 .75.34.75.75v6.5c0 3.2-2.4 5.83-5.5 6.2v5.06l2.75-.01a.75.75 0 0 1 0 1.5l-3.5.01-3-.01a.75.75 0 0 1 0-1.5H11v-5.05a5.75 5.75 0 0 1-5-5.7zm1.5.75v2.75h9V3.5zm0 6.25C7.5 12.1 9.4 14 11.75 14a4.75 4.75 0 0 0 4.75-4.75v-1.5h-9z"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DrinkWineIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
