// DrinkBottleOffIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
};
const C = {
  20: (<><path d="M6.28 6.99 2.15 2.85a.5.5 0 1 1 .7-.7l15 15a.5.5 0 0 1-.7.7l-2.16-2.15a2.5 2.5 0 0 1-3.74 1.97 2.5 2.5 0 0 1-2.5 0q-.56.31-1.25.33A2.5 2.5 0 0 1 5 15.5v-5l.01-.22a4.1 4.1 0 0 1 1.27-3.29M13.3 14l-6-6h-.57A3.2 3.2 0 0 0 6 10.34L6 10.5V14zM6 15v.5a1.5 1.5 0 0 0 2.44 1.17.5.5 0 0 1 .62 0 1.5 1.5 0 0 0 1.88 0 .5.5 0 0 1 .62 0q.4.31.94.33c.83 0 1.5-.67 1.5-1.5V15zm8-4.5v1.38l1 1V10.5l-.01-.22a4 4 0 0 0-.67-2.56c-.4-.6-.86-1.04-1.24-1.42l-.01-.01c-.55-.54-.9-.9-1.02-1.4A1.5 1.5 0 0 0 11.5 2h-3a1.5 1.5 0 0 0-.54 2.9q-.09.34-.3.64l.71.71q.44-.51.59-1.25h2.09c.16.86.74 1.43 1.27 1.96l.05.04H9.12l1 1h3.17l.19.27a3 3 0 0 1 .51 2.07zM8.5 4a.5.5 0 0 1 0-1h3a.5.5 0 0 1 0 1z"/></>),
};
const SIZES = [20];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DrinkBottleOffIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
