// DualScreenVibrateIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M7 5a2 2 0 0 0-2 2v6c0 1.1.9 2 2 2h6a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2zM6 7a1 1 0 0 1 1-1h2.5v8H7a1 1 0 0 1-1-1zm4.5 7V6H13a1 1 0 0 1 1 1v6a1 1 0 0 1-1 1zm1-1.5c0-.28.22-.5.5-.5h.5a.5.5 0 0 1 0 1H12a.5.5 0 0 1-.5-.5m-4-.5a.5.5 0 0 0 0 1H8a.5.5 0 0 0 0-1zM1.88 6.51a.5.5 0 0 1 .6.37l.41 1.64q.14.54-.1 1.03l-.62 1.23a.5.5 0 0 0 0 .44l.78 1.56a.5.5 0 1 1-.9.44l-.77-1.55a1.5 1.5 0 0 1 0-1.34l.6-1.22a.5.5 0 0 0 .04-.35l-.4-1.64a.5.5 0 0 1 .36-.6m16.6.37a.5.5 0 0 0-.97.24l.41 1.64a.5.5 0 0 1-.03.35l-.61 1.22a1.5 1.5 0 0 0 0 1.34l.77 1.55a.5.5 0 1 0 .9-.44l-.78-1.56a.5.5 0 0 1 0-.44l.61-1.23q.24-.5.11-1.03z"/></>),
  24: (<><path d="M16.75 6c.92 0 1.67.7 1.75 1.6v9.65c0 .92-.7 1.67-1.6 1.74l-.15.01h-9.5c-.92 0-1.67-.7-1.74-1.6l-.01-.15v-9.5c0-.92.7-1.68 1.6-1.75h9.65M11.5 7.5H7.25a.25.25 0 0 0-.24.19L7 7.75v9.5q.01.2.2.24l.05.01h4.25zm5.25 0H12.5v10h4.25q.2-.01.24-.2l.01-.05v-9.5a.25.25 0 0 0-.2-.25zm-1.5 7.5a.75.75 0 0 1 .1 1.5h-1.1a.75.75 0 0 1-.1-1.49h1.1m-5.5 0a.75.75 0 0 1 .1 1.5h-1.1a.75.75 0 0 1-.1-1.49h1.1m11.37-6.96.06.09.04.1.58 1.45c.34.83.24 1.77-.24 2.51l-.11.16-.15.2c-.23.31-.3.7-.2 1.08l.04.13.58 1.46a.75.75 0 0 1-1.35.65l-.04-.1-.58-1.45a2.8 2.8 0 0 1 .24-2.51l.1-.16.16-.2c.23-.31.3-.71.2-1.08l-.04-.14-.58-1.45a.75.75 0 0 1 1.29-.74m-17.55 0 .06.09.04.1.58 1.45c.34.83.24 1.77-.24 2.51l-.1.16-.16.2c-.23.31-.3.7-.2 1.08l.04.13.58 1.46a.75.75 0 0 1-1.35.65l-.04-.1-.58-1.45a2.8 2.8 0 0 1 .24-2.51l.11-.16.15-.2c.23-.31.3-.71.2-1.08l-.04-.14-.58-1.45a.75.75 0 0 1 1.29-.74"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function DualScreenVibrateIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
