// FastForwardIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
};
const C = {
  16: (<><path d="M2 4.46a1 1 0 0 1 1.58-.81L8 6.77v-2.3a1 1 0 0 1 1.58-.82l5 3.53a1 1 0 0 1 0 1.64l-5 3.53A1 1 0 0 1 8 11.54v-2.3l-4.42 3.11A1 1 0 0 1 2 11.54zM8 8 3 4.46v7.08L8 8zm1 3.55L14.01 8 9 4.46z"/></>),
  20: (<><path d="M10.02 5.49a1 1 0 0 1 1.59-.81l5.88 4.31c.68.5.68 1.52 0 2.02l-5.88 4.3a1 1 0 0 1-1.6-.8v-3.16l-5.4 3.97a1 1 0 0 1-1.6-.8V5.48a1 1 0 0 1 1.6-.81l5.4 3.97zm6.88 4.3-5.88-4.3v9.02l5.88-4.3c.13-.1.13-.31 0-.41m-7 0L4.02 5.5v9.02l5.88-4.3c.13-.1.13-.31 0-.41"/></>),
  24: (<><path d="M11.5 5.5a1.5 1.5 0 0 1 2.47-1.14l7.41 6.3c.82.7.82 1.97 0 2.67l-7.4 6.3a1.5 1.5 0 0 1-2.48-1.13v-4l-6.03 5.14A1.5 1.5 0 0 1 3 18.5v-13a1.5 1.5 0 0 1 2.47-1.14L11.5 9.5zm0 5.96-7-5.96v13l7-5.96zm8.91.35L13 5.5V18.5l7.41-6.31a.25.25 0 0 0 0-.38"/></>),
  28: (<><path d="M13 10.7V6.13a1.63 1.63 0 0 1 2.64-1.27l9.63 7.64c.97.77.97 2.24 0 3l-9.63 7.64A1.63 1.63 0 0 1 13 21.87V17.3l-7.36 5.84A1.63 1.63 0 0 1 3 21.87V6.13a1.62 1.62 0 0 1 2.64-1.27zm0 4.69V12.6L4.7 6.03 4.64 6q-.03 0-.07.02l-.05.04-.02.07v15.74q0 .04.02.07l.05.04.07.02.06-.03zm1.7-9.36L14.64 6q-.03 0-.07.02l-.05.04-.02.07v15.74l.02.07.05.04.07.02.06-.03 9.64-7.64a.42.42 0 0 0 0-.66z"/></>),
};
const SIZES = [16, 20, 24, 28];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function FastForwardIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
