// FastAccelerationIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M11 4a6 6 0 1 1-3.3 11.01V15h-.02A6 6 0 0 1 11 4M5.25 14q.39.54.85 1H1.5a.5.5 0 0 0 0 1h5.9a7 7 0 1 0 0-12H2.5a.5.5 0 0 0 0 1h3.6a7 7 0 0 0-1.43 8H3.5a.5.5 0 0 0 0 1zM8.2 7.9a3.5 3.5 0 0 0 0 4.2l1.08-1.08a2 2 0 0 1 0-2.04zm.7-.7 1.08 1.08a2 2 0 0 1 2.04 0L13.1 7.2a3.5 3.5 0 0 0-4.2 0m4.9.7-1.08 1.08a2 2 0 0 1 0 2.04l1.08 1.08a3.5 3.5 0 0 0 0-4.2m-.7 4.9-1.08-1.08a2 2 0 0 1-2.04 0L8.9 12.8a3.5 3.5 0 0 0 4.2 0M6.5 10a4.5 4.5 0 1 1 9 0 4.5 4.5 0 0 1-9 0m3.5 0a1 1 0 1 0 2 0 1 1 0 0 0-2 0"/></>),
  24: (<><path d="M13.5 4a8.5 8.5 0 1 1-4.82 15.5H1.75a.75.75 0 0 1-.1-1.5h5.37q-.6-.69-1.02-1.5H3.75a.75.75 0 0 1-.1-1.5h1.72a8.5 8.5 0 0 1 1.65-8H2.75a.75.75 0 0 1-.1-1.5h6.03A8.5 8.5 0 0 1 13.5 4m0 1.5a7 7 0 1 0 0 14 7 7 0 0 0 0-14m0 1.5a5.5 5.5 0 1 1 0 11 5.5 5.5 0 0 1 0-11m1.15 7.72a2.5 2.5 0 0 1-2.3 0l-1.09 1.1a4 4 0 0 0 4.5 0zM9.5 12.5c0 .84.26 1.62.7 2.26l1.09-1.1a2.5 2.5 0 0 1 0-2.32l-1.1-1.09c-.43.65-.69 1.42-.69 2.25m7.32-2.24-1.1 1.1a2.5 2.5 0 0 1 0 2.3l1.1 1.1a4 4 0 0 0 0-4.5M13.5 11.5a1 1 0 1 0 0 2 1 1 0 0 0 0-2m0-3q-1.26.02-2.25.7l1.1 1.08a2.5 2.5 0 0 1 2.32 0l1.09-1.08a4 4 0 0 0-2.26-.7"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function FastAccelerationIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
