// FaxIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
};
const C = {
  16: (<><path d="M5.5 2C4.67 2 4 2.67 4 3.5V6a2 2 0 0 0-2 2v4.5c0 .83.67 1.5 1.5 1.5h6q-.33-.45-.45-1H3.5a.5.5 0 0 1-.5-.5V8a1 1 0 0 1 1-1h5.05q.11-.55.45-1H5V3.5c0-.28.22-.5.5-.5h5c.28 0 .5.22.5.5v1.55q.24-.05.5-.05h.5V3.5c0-.83-.67-1.5-1.5-1.5zm6 4c-.83 0-1.5.67-1.5 1.5v5c0 .83.67 1.5 1.5 1.5h1c.83 0 1.5-.67 1.5-1.5v-5c0-.83-.67-1.5-1.5-1.5zM11 7.5c0-.28.22-.5.5-.5h1c.28 0 .5.22.5.5v5a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5zm-6 1a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0M4.5 11a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1M7 8.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0M6.5 11a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1"/></>),
  20: (<><path d="M5 4.5C5 3.67 5.67 3 6.5 3h7c.83 0 1.5.67 1.5 1.5V7h-1V4.5a.5.5 0 0 0-.5-.5h-7a.5.5 0 0 0-.5.5V8h5.5q-.33.45-.45 1H5a1 1 0 0 0-1 1v5.5c0 .28.22.5.5.5h6.55q.11.55.45 1h-7A1.5 1.5 0 0 1 3 15.5V10c0-1.1.9-2 2-2zm7 5c0-.83.67-1.5 1.5-1.5h2c.83 0 1.5.67 1.5 1.5v6c0 .83-.67 1.5-1.5 1.5h-2a1.5 1.5 0 0 1-1.5-1.5zm1.5-.5a.5.5 0 0 0-.5.5v6c0 .28.22.5.5.5h2a.5.5 0 0 0 .5-.5v-6a.5.5 0 0 0-.5-.5zm-7.87 1a.62.62 0 1 1 0 1.25.62.62 0 0 1 0-1.25m0 2.25a.62.62 0 1 1 0 1.25.62.62 0 0 1 0-1.25M8.5 13a.62.62 0 1 0-1.25 0 .62.62 0 0 0 1.25 0m-.62-3a.62.62 0 1 1 0 1.25.62.62 0 0 1 0-1.25"/></>),
};
const SIZES = [16, 20];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function FaxIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
