// FilmstripMusicNote2Icon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
};
const C = {
  20: (<><path d="M17.09 5.02c.46-.1.91.24.91.73V15a2 2 0 1 1-1-1.73V8.61l-6 2.14V16a2 2 0 1 1-1-1.73v-6.2c0-.32.2-.6.5-.7L17 5.04zM9 15a1 1 0 1 0 0 2 1 1 0 0 0 0-2m7-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2M11.5 2A2.5 2.5 0 0 1 14 4.5v.55l-1 .36V4.5c0-.83-.67-1.5-1.5-1.5h-7C3.67 3 3 3.67 3 4.5v6c0 .83.67 1.5 1.5 1.5H9v1H4.5A2.5 2.5 0 0 1 2 10.5v-6A2.5 2.5 0 0 1 4.5 2zm-7 7.5c.28 0 .5.22.5.5v.5a.5.5 0 0 1-1 0V10c0-.28.22-.5.5-.5M11 8.25v1.44l6-2.14V6.1zm-6.5-1.5c.28 0 .5.22.5.5v.5a.5.5 0 0 1-1 0v-.5c0-.28.22-.5.5-.5M4.5 4c.28 0 .5.22.5.5V5a.5.5 0 0 1-1 0v-.5c0-.28.22-.5.5-.5m7 0c.28 0 .5.22.5.5V5a.5.5 0 0 1-1 0v-.5c0-.28.22-.5.5-.5"/></>),
};
const SIZES = [20];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function FilmstripMusicNote2Icon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
