// FlowchartCircleIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M6 6.5c0-.28.22-.5.5-.5h2c.28 0 .5.22.5.5v2a.5.5 0 0 1-.5.5H8v1.8L9.2 12H11v-.5c0-.28.22-.5.5-.5h2c.28 0 .5.22.5.5v2a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5V13H9.2l-1.35 1.35a.5.5 0 0 1-.7 0l-1.5-1.5a.5.5 0 0 1 0-.7L7 10.79V9h-.5a.5.5 0 0 1-.5-.5zM2 10a8 8 0 1 1 16 0 8 8 0 0 1-16 0m8-7a7 7 0 1 0 0 14 7 7 0 0 0 0-14"/></>),
  24: (<><path d="M7.25 6.5a.75.75 0 0 0-.75.75v2.5c0 .41.34.75.75.75h.5v2.69l-1.78 1.78c-.3.3-.3.77 0 1.06l2 2c.3.3.77.3 1.06 0l1.78-1.78h2.69v.5c0 .41.34.75.75.75h2.5c.41 0 .75-.34.75-.75v-2.5a.75.75 0 0 0-.75-.75h-2.5a.75.75 0 0 0-.75.75v.5h-2.69l-1.56-1.56V10.5h.5c.41 0 .75-.34.75-.75v-2.5a.75.75 0 0 0-.75-.75zM2 12a10 10 0 1 1 20 0 10 10 0 0 1-20 0m10-8.5a8.5 8.5 0 1 0 0 17 8.5 8.5 0 0 0 0-17"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function FlowchartCircleIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
