// FluentIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
  48: '0 0 48 48',
};
const C = {
  20: (<><path d="M10.28 2.05a.5.5 0 0 1 .44 0l5 2.5a.5.5 0 0 1 0 .9l-4.1 2.05 4.1 2.05a.5.5 0 0 1 0 .9L11 12.8v4.69a.5.5 0 0 1-.76.43l-5-3A.5.5 0 0 1 5 14.5V5q0-.3.28-.45zM6 5.31v8.9l4 2.4v-3.8a1 1 0 0 1 .55-.9L14.38 10l-4.1-2.05a.5.5 0 0 1 0-.9L14.38 5 10.5 3.06z"/></>),
  24: (<><path d="M11.91 2.08q.34-.15.68 0l6 3a.75.75 0 0 1 0 1.34l-4.66 2.33 4.66 2.33a.75.75 0 0 1 0 1.34L13 15.22v6.03a.75.75 0 0 1-1.15.64l-6-3.77a.8.8 0 0 1-.35-.64V5.75c0-.28.16-.54.41-.67zM7 6.22v10.85l4.5 2.82v-5.14c0-.28.16-.54.41-.67l4.66-2.33-4.66-2.33a.75.75 0 0 1 0-1.34l4.66-2.33-4.32-2.16z"/></>),
  48: (<><path d="M23.83 4.16a1.5 1.5 0 0 1 1.34 0l12 6a1.5 1.5 0 0 1 0 2.68l-9.32 4.66 9.32 4.66a1.5 1.5 0 0 1 0 2.68L26 30.43V42.5a1.5 1.5 0 0 1-2.3 1.27l-12-7.54a1.5 1.5 0 0 1-.7-1.27V11.5c0-.57.32-1.09.83-1.34zM14 12.43v21.7l9 5.66V29.5c0-.57.32-1.08.83-1.34l9.32-4.66-9.32-4.66a1.5 1.5 0 0 1 0-2.68l9.32-4.66-8.65-4.32z"/></>),
};
const SIZES = [20, 24, 48];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function FluentIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
