// GestureIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M5.01 4.4A.5.5 0 0 1 5.5 4h9a.5.5 0 0 1 0 1H7.8l8.9 4.04a.5.5 0 0 1 .04.9l-11 5.92a.5.5 0 1 1-.48-.88l10.12-5.44L5.29 4.96a.5.5 0 0 1-.28-.57M17 4.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0M3.5 17a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1"/></>),
  24: (<><path d="M3.75 17.5a.75.75 0 1 1 0 1.5.75.75 0 0 1 0-1.5m3-13.5h10.5a.75.75 0 0 1 .1 1.5h-6.6l9.77 3.8c.57.22.64.98.16 1.31l-.1.06L6.1 17.93a.75.75 0 0 1-.76-1.3l.09-.04 12.97-6.5L6.48 5.45c-.74-.28-.58-1.35.16-1.44zh10.51zm13 0a.75.75 0 1 1 0 1.5.75.75 0 0 1 0-1.5"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function GestureIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
