// GiftCardIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M1 5c0-1.1.9-2 2-2h10a2 2 0 0 1 2 2v6a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2zm12 7a1 1 0 0 0 1-1V8H6.7l1.15 1.15a.5.5 0 1 1-.7.7L6 8.71V12zM7.91 7H14V5a1 1 0 0 0-1-1H6v1.09A1.5 1.5 0 0 1 7.91 7M6.5 7a.5.5 0 1 0-.5-.5V7zM5 5.09V4H3a1 1 0 0 0-1 1v2h1.09A1.5 1.5 0 0 1 5 5.09M4.5 7H5v-.5a.5.5 0 1 0-.5.5m-.2 1H2v3a1 1 0 0 0 1 1h2V8.7L3.85 9.86a.5.5 0 0 1-.7-.7z"/></>),
  20: (<><path d="M2 6.75A2.75 2.75 0 0 1 4.75 4h10.5A2.75 2.75 0 0 1 18 6.75v6.5A2.75 2.75 0 0 1 15.25 16H4.75A2.75 2.75 0 0 1 2 13.25zM3 10v3.25c0 .97.78 1.75 1.75 1.75H7v-4.3l-1.65 1.65a.5.5 0 0 1-.7-.7L6.29 10zm1.27-1A2 2 0 0 1 7 6.27V5H4.75C3.78 5 3 5.78 3 6.75V9zM6 9h1V8a1 1 0 1 0-1 1m2-1v1h1a1 1 0 1 0-1-1m2.73 1H17V6.75C17 5.78 16.22 5 15.25 5H8v1.27A2 2 0 0 1 10.73 9m-2.02 1 1.64 1.65a.5.5 0 0 1-.7.7L8 10.71V15h7.25c.97 0 1.75-.78 1.75-1.75V10z"/></>),
  24: (<><path d="M5.25 4A3.25 3.25 0 0 0 2 7.25v8.5C2 17.55 3.46 19 5.25 19h13.5c1.8 0 3.25-1.46 3.25-3.25v-8.5C22 5.45 20.54 4 18.75 4zM3.5 7.25c0-.97.78-1.75 1.75-1.75H8v1.2A2.5 2.5 0 0 0 4.5 9q0 .54.2 1H3.5zM9.5 9a1 1 0 1 1 1 1h-1zM8 10H7a1 1 0 1 1 1-1zm0 2.56v4.94H5.25c-.97 0-1.75-.78-1.75-1.75V11.5h3.44l-1.72 1.72a.75.75 0 1 0 1.06 1.06zm1.5 4.94v-4.94l1.72 1.72a.75.75 0 1 0 1.06-1.06l-1.72-1.72h9.94v4.25c0 .97-.78 1.75-1.75 1.75zm0-10.8V5.5h9.25c.97 0 1.75.78 1.75 1.75V10h-7.7a2.5 2.5 0 0 0-2.3-3.5q-.54 0-1 .2"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function GiftCardIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
