// GiftCardMultipleIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M4.75 4A2.75 2.75 0 0 0 2 6.75v5.5A2.75 2.75 0 0 0 4.75 15h8.5A2.75 2.75 0 0 0 16 12.25v-5.5A2.75 2.75 0 0 0 13.25 4zM3 12.25V10h3.3l-1.65 1.65a.5.5 0 0 0 .7.7L7 10.71V14H4.75C3.78 14 3 13.22 3 12.25M3 9V6.75C3 5.78 3.78 5 4.75 5H7v1.27A2 2 0 0 0 4.27 9zm4 0H6a1 1 0 1 1 1-1zm1 0V8a1 1 0 1 1 1 1zm3-1a2 2 0 0 0-3-1.73V5h5.25c.97 0 1.75.78 1.75 1.75V9h-4.27A2 2 0 0 0 11 8m-.65 3.65L8.71 10H15v2.25c0 .97-.78 1.75-1.75 1.75H8v-3.3l1.65 1.65a.5.5 0 0 0 .7-.7M6.75 17c-.85 0-1.62-.39-2.12-1h8.62A3.75 3.75 0 0 0 17 12.25V6.63c.61.5 1 1.27 1 2.12v3.5A4.75 4.75 0 0 1 13.25 17z"/></>),
  24: (<><path d="M5 4a3 3 0 0 0-3 3v7.5a3 3 0 0 0 3 3h11.5a3 3 0 0 0 3-3V7a3 3 0 0 0-3-3zM3.5 7c0-.83.67-1.5 1.5-1.5h3v1.2A2.5 2.5 0 0 0 4.5 9q0 .54.2 1H3.5zm6-.3V5.5h7c.83 0 1.5.67 1.5 1.5v3h-5.2a2.5 2.5 0 0 0-2.3-3.5q-.54 0-1 .2m1.06 4.8H18v3c0 .83-.67 1.5-1.5 1.5h-7v-3.44l1.72 1.72a.75.75 0 1 0 1.06-1.06zM8 12.56V16H5a1.5 1.5 0 0 1-1.5-1.5v-3h3.44l-1.72 1.72a.75.75 0 1 0 1.06 1.06zM11.5 9a1 1 0 0 1-1 1h-1V9a1 1 0 0 1 2 0M7 8a1 1 0 0 1 1 1v1H7a1 1 0 1 1 0-2m.5 12a3 3 0 0 1-2.6-1.5h11.6a4 4 0 0 0 4-4V6.9A3 3 0 0 1 22 9.5v5a5.5 5.5 0 0 1-5.5 5.5z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function GiftCardMultipleIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
