// GroupIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M7 4.5q0 .26-.05.5H10a1 1 0 0 1 1 1v2h-1a2 2 0 0 0-2 2v1H6a1 1 0 0 1-1-1V6.95a3 3 0 0 1-1 0V10c0 1.1.9 2 2 2h2v2c0 1.1.9 2 2 2h3.05a3 3 0 0 1 0-1H10a1 1 0 0 1-1-1v-2h1a2 2 0 0 0 2-2V9h2a1 1 0 0 1 1 1v3.05a3 3 0 0 1 1 0V10a2 2 0 0 0-2-2h-2V6a2 2 0 0 0-2-2H6.95q.05.24.05.5M11 9v1a1 1 0 0 1-1 1H9v-1a1 1 0 0 1 1-1zM6 4.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0m11 11a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0m0-11a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0m-11 11a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0"/></>),
  24: (<><path d="M5 7a2 2 0 1 0 0-4 2 2 0 0 0 0 4m14 0a2 2 0 1 0 0-4 2 2 0 0 0 0 4m2 12a2 2 0 1 1-4 0 2 2 0 0 1 4 0M5 21a2 2 0 1 0 0-4 2 2 0 0 0 0 4M7.96 5.5A3 3 0 0 0 7.83 4h4.67A2.5 2.5 0 0 1 15 6.5V9h2.5a2.5 2.5 0 0 1 2.5 2.5v4.67a3 3 0 0 0-1.5-.13V11.5a1 1 0 0 0-1-1H15v2a2.5 2.5 0 0 1-2.5 2.5h-2v2.5a1 1 0 0 0 1 1h4.54a3 3 0 0 0 .13 1.5H11.5A2.5 2.5 0 0 1 9 17.5V15H6.5A2.5 2.5 0 0 1 4 12.5V7.83a3 3 0 0 0 1.5.13v4.54a1 1 0 0 0 1 1H9v-2A2.5 2.5 0 0 1 11.5 9h2V6.5a1 1 0 0 0-1-1zm4.54 8a1 1 0 0 0 1-1v-2h-2a1 1 0 0 0-1 1v2z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function GroupIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
