// GroupListIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M2.5 3a.5.5 0 0 0-.5.5v5c0 .28.22.5.5.5h2a.5.5 0 0 0 0-1H3V4h1.5a.5.5 0 0 0 0-1zm0 8a.5.5 0 0 0-.5.5v5c0 .28.22.5.5.5h2a.5.5 0 0 0 0-1H3v-4h1.5a.5.5 0 0 0 0-1zM6 4.5c0-.28.22-.5.5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5m.5 7.5a.5.5 0 0 0 0 1h11a.5.5 0 0 0 0-1zM6 7.5c0-.28.22-.5.5-.5h11a.5.5 0 0 1 0 1h-11a.5.5 0 0 1-.5-.5m.5 7.5a.5.5 0 0 0 0 1h11a.5.5 0 0 0 0-1z"/></>),
  24: (<><path d="M2.75 12h2.5a.75.75 0 0 1 .1 1.5H3.5V19h1.75c.38 0 .7.28.74.65v.1c0 .38-.27.7-.64.74l-.1.01h-2.5a.75.75 0 0 1-.74-.65l-.01-.1v-7c0-.38.28-.7.65-.75zm18.5 5.5a.75.75 0 0 1 .1 1.5H7.75a.75.75 0 0 1-.1-1.5h13.6m0-4a.75.75 0 0 1 .1 1.5H7.75a.75.75 0 0 1-.1-1.5h13.6m-18.5-11 2.5.01a.75.75 0 0 1 .1 1.5H3.5v5.48h1.75c.38 0 .7.29.74.65v.1c0 .38-.27.7-.64.75h-2.6a.75.75 0 0 1-.74-.64l-.01-.1v-7c0-.38.28-.7.65-.74zM21.25 8a.75.75 0 0 1 .1 1.5H7.75a.75.75 0 0 1-.1-1.49h13.6m0-4a.75.75 0 0 1 .1 1.5H7.75a.75.75 0 0 1-.1-1.49h13.6"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function GroupListIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
