// HdrOffIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M2.85 2.15a.5.5 0 1 0-.7.7l1.41 1.42A2.8 2.8 0 0 0 2 6.75v6.5A2.75 2.75 0 0 0 4.75 16h10.54l1.86 1.85a.5.5 0 0 0 .7-.7zM14.3 15H4.75C3.78 15 3 14.22 3 13.25v-6.5c0-.83.57-1.52 1.34-1.7l2.72 2.72A1 1 0 0 0 7 8v1.5H5V8a.5.5 0 0 0-1 0v4a.5.5 0 0 0 1 0v-1.5h2V12a.5.5 0 0 0 1 0V8.7l1 1V12c0 .28.22.5.5.5h.25q.88-.02 1.48-.56zM10 10.7l.52.53q-.22.18-.52.24zm-.38-3.2L12 9.88v-.13c0-1.24-1-2.25-2.25-2.25zM13 10.88l1 1V10.5h.4l.63 1.68a.5.5 0 0 0 .94-.36l-.6-1.6a1.5 1.5 0 0 0-.87-2.72h-1a.5.5 0 0 0-.5.5zm4 2.37q-.02.69-.45 1.18l.7.7c.47-.49.75-1.15.75-1.88v-6.5A2.75 2.75 0 0 0 15.25 4H6.12l1 1h8.13c.97 0 1.75.78 1.75 1.75zM14 9.5v-1h.5a.5.5 0 0 1 0 1z"/></>),
  24: (<><path d="M3.28 2.22a.75.75 0 1 0-1.06 1.06l.96.96C2.46 4.84 2 5.74 2 6.75v10.5c0 1.8 1.46 3.25 3.25 3.25h13.5q.33 0 .63-.06l1.34 1.34a.75.75 0 0 0 1.06-1.06zM17.94 19H5.25c-.97 0-1.75-.78-1.75-1.75V6.75c0-.6.3-1.12.75-1.44L8.04 9.1a.6.6 0 0 0-.29.52v1.77H6.27V9.54a.63.63 0 0 0-1.25.1v4.84a.63.63 0 0 0 1.25-.1v-1.74h1.48v1.73l.01.1a.63.63 0 0 0 1.24-.1v-4.3l1 .99v3.41c.05.3.31.53.62.53h.92a2.6 2.6 0 0 0 1.66-.74zm-6.7-6.69 1.08 1.07q-.39.36-.94.37h-.13zm5.02.77L15 11.82V9.64c0-.31.22-.57.53-.62h1.66a1.8 1.8 0 0 1 1.02 3.29l.74 1.83a.63.63 0 0 1-.83.8l-.32-.31v-.02l-.8-1.99h-.75zm0-1.7h.94a.55.55 0 0 0 .1-1.1l-.1-.01h-.95zm4.24 5.94V6.75c0-.97-.78-1.75-1.75-1.75H8.18l-1.5-1.5h12.07c1.8 0 3.25 1.46 3.25 3.25v10.5q0 .7-.27 1.3z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function HdrOffIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
