// HeadphonesIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
  48: '0 0 48 48',
};
const C = {
  16: (<><path d="M8 1a7 7 0 0 1 7 7v4.5a2.5 2.5 0 0 1-2.5 2.5h-2a.5.5 0 0 1-.5-.5v-5c0-.28.22-.5.5-.5H14V8A6 6 0 0 0 2 8v1h3.5c.28 0 .5.22.5.5v5a.5.5 0 0 1-.5.5h-2a2.5 2.5 0 0 1-2.49-2.24L1 12.5V8a7 7 0 0 1 7-7M2 12.5v.15A1.5 1.5 0 0 0 3.5 14H5v-4H2zm9 1.5h1.5c.83 0 1.5-.67 1.5-1.5V10h-3z"/></>),
  20: (<><path d="M3 10a7 7 0 0 1 14 0v1h-3.5a.5.5 0 0 0-.5.5v6c0 .28.22.5.5.5H16a2 2 0 0 0 2-2v-6a8 8 0 1 0-16 0v6c0 1.1.9 2 2 2h2.5a.5.5 0 0 0 .5-.5v-6a.5.5 0 0 0-.5-.5H3zm0 2h3v5H4a1 1 0 0 1-1-1zm14 0v4a1 1 0 0 1-1 1h-2v-5z"/></>),
  24: (<><path d="M22 12v7a3 3 0 0 1-2.82 3H16a1 1 0 0 1-1-.88V15a1 1 0 0 1 .88-1h4.62v-2a8.5 8.5 0 0 0-17 0v2H8a1 1 0 0 1 1 1v6a1 1 0 0 1-1 1H5a3 3 0 0 1-3-3v-7a10 10 0 1 1 20 0v7zM7.5 15.5h-4V19c0 .83.67 1.5 1.5 1.5h2.5zm13 0h-4v5H19c.78 0 1.42-.6 1.5-1.36V15.5"/></>),
  28: (<><path d="M22 26h-3a1 1 0 0 1-1-.88V17a1 1 0 0 1 .88-1h5.62v-2a10.5 10.5 0 1 0-21 0v2H9a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H6a4 4 0 0 1-4-4v-8a12 12 0 1 1 24 0v8a4 4 0 0 1-3.8 4zh-3zM8.5 17.5h-5V22A2.5 2.5 0 0 0 6 24.5h2.5zm16 0h-5v7H22a2.5 2.5 0 0 0 2.5-2.5z"/></>),
  48: (<><path d="M24 6.5A17.5 17.5 0 0 0 6.5 24v4h9.25c.69 0 1.25.56 1.25 1.25v13.5c0 .69-.56 1.25-1.25 1.25h-6A5.75 5.75 0 0 1 4 38.25V24a20 20 0 1 1 40 0v14.25A5.75 5.75 0 0 1 38.25 44h-6c-.69 0-1.25-.56-1.25-1.25v-13.5c0-.69.56-1.25 1.25-1.25h9.25v-4A17.5 17.5 0 0 0 24 6.5m17.5 24h-8v11h4.75c1.8 0 3.25-1.46 3.25-3.25zm-35 0v7.75c0 1.8 1.46 3.25 3.25 3.25h4.75v-11z"/></>),
};
const SIZES = [16, 20, 24, 28, 48];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function HeadphonesIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
