// HeartPulseIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="m10.5 16.8 4.75-4.8h-1a2 2 0 0 1-.36-.04l-3.86 3.9-3.87-3.9a2 2 0 0 1-.36.04h-1l4.75 4.8c.26.27.69.27.95 0m6.22-12.49a4.4 4.4 0 0 1 .98 4.7L17.5 9h-.89c.67-1.28.48-2.9-.6-3.98A3.3 3.3 0 0 0 11.3 5l-.95.96a.5.5 0 0 1-.71 0L8.68 5a3.3 3.3 0 0 0-4.7-.01A3.4 3.4 0 0 0 3.41 9H2.5l-.18.01a4.4 4.4 0 0 1 .94-4.74 4.3 4.3 0 0 1 6.13.02l.6.61.6-.6.1-.1a4.3 4.3 0 0 1 6.03.11m-8.76 2a.5.5 0 0 0-.92 0L5.47 10H2.5a.5.5 0 0 0 0 1h3.3a.5.5 0 0 0 .46-.3L7.5 7.79l2.04 4.9a.5.5 0 0 0 .88.08l2.15-3.43 1.3 1.49q.16.16.38.17h3.25a.5.5 0 0 0 0-1h-3.02l-1.6-1.83a.5.5 0 0 0-.8.06l-2 3.18z"/></>),
  24: (<><path d="M12.82 5.58 12 6.4l-.82-.82A5.37 5.37 0 0 0 2.25 11h1.6a3.88 3.88 0 0 1 6.27-4.36L11.47 8c.3.3.79.29 1.08-.02l1.33-1.34A3.88 3.88 0 0 1 20.15 11h1.6a5.37 5.37 0 0 0-8.93-5.42m-1.35 15.5L4.89 14.5h2.12L12 19.47l4.99-4.98h2.12l-6.58 6.58c-.3.29-.77.29-1.06 0M9.42 8.4a.75.75 0 0 0-1.35.02L6.38 12H2.75a.75.75 0 0 0 0 1.5h4.1c.3 0 .56-.17.69-.43l1.23-2.6 2.56 5.11a.75.75 0 0 0 1.28.1l2.7-3.73 1.13 1.3q.22.24.56.25h4.25a.75.75 0 0 0 0-1.5h-3.91l-1.53-1.74a.75.75 0 0 0-1.17.05l-2.52 3.5z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function HeartPulseIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
