// HomeDatabaseIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M11 2.39a1.5 1.5 0 0 0-2 0L3.5 7.33c-.32.28-.5.69-.5 1.12v7.05c0 .83.67 1.5 1.5 1.5h4.55a2 2 0 0 1-.05-.5V16H4.5a.5.5 0 0 1-.5-.5V8.45a.5.5 0 0 1 .17-.38l5.5-4.94a.5.5 0 0 1 .66 0l5.5 4.94.03.03a8 8 0 0 1 1.14.26 1.5 1.5 0 0 0-.5-1.03zm6 7.03A7.86 7.86 0 0 0 14.5 9c-2.49 0-4.5 1.12-4.5 2.5s2.01 2.5 4.5 2.5 4.5-1.12 4.5-2.5c0-.87-.8-1.63-2-2.08m1.17 4.72c-1 .55-2.29.86-3.67.86s-2.68-.3-3.67-.86q-.45-.24-.83-.59v2.95c0 1.38 2.01 2.5 4.5 2.5s4.5-1.12 4.5-2.5v-2.95q-.38.35-.83.6"/></>),
  24: (<><path d="M10.55 2.53c.84-.7 2.06-.7 2.9 0l6.75 5.7c.5.42.8 1.05.8 1.71v1.5a9 9 0 0 0-1.5-.34V9.94q0-.35-.27-.57l-6.75-5.7a.75.75 0 0 0-.96 0l-6.75 5.7a.8.8 0 0 0-.27.57v9.31c0 .14.11.25.25.25H12v1q0 .26.06.5H4.75C3.78 21 3 20.22 3 19.25v-9.3c0-.67.3-1.3.8-1.73zM21 12.5q-.67-.25-1.5-.39A10 10 0 0 0 18 12c-2.76 0-5 1.12-5 2.5s2.24 2.5 5 2.5a10 10 0 0 0 1.5-.11 8 8 0 0 0 1.5-.39c1.21-.46 2-1.18 2-2s-.79-1.54-2-2m0 5.06a9 9 0 0 1-3 .44 9 9 0 0 1-3.98-.84q-.55-.26-1.02-.67v4.01q0 .54.42 1c.77.88 2.53 1.5 4.58 1.5 2.76 0 5-1.12 5-2.5v-4q-.47.4-1.02.66-.45.23-.98.4"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function HomeDatabaseIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
