// HomePersonIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M16.5 14c.83 0 1.5.67 1.5 1.5 0 1.24-1 2.5-3.5 2.5S11 16.75 11 15.5c0-.83.67-1.5 1.5-1.5zM9 2.39a1.5 1.5 0 0 1 2 0l5.5 4.95c.32.28.5.69.5 1.11v.9q-.4-.6-1-.95a.5.5 0 0 0-.16-.32l-5.5-4.95a.5.5 0 0 0-.67 0l-5.5 4.95a.5.5 0 0 0-.17.37v7.05c0 .28.22.5.5.5h5.54q.08.53.33 1H4.5A1.5 1.5 0 0 1 3 15.5V8.45c0-.42.18-.83.5-1.11zM14.5 9a2 2 0 1 1 0 4 2 2 0 0 1 0-4"/></>),
  24: (<><path d="M20.23 17c.98 0 1.77.8 1.77 1.77v.1c0 1.56-1.29 3.13-4.5 3.13S13 20.44 13 18.88v-.1c0-.99.8-1.78 1.77-1.78zM10.55 2.53c.84-.7 2.06-.7 2.9 0l6.75 5.7c.5.43.8 1.05.8 1.72v1.84c0 .12-.1.21-.2.21a.2.2 0 0 1-.2-.12q-.4-.76-1.1-1.25v-.68q0-.34-.27-.58l-6.75-5.7a.75.75 0 0 0-.96 0l-6.75 5.7a.8.8 0 0 0-.27.58v8.8c0 .41.34.75.75.75h6.8q.15.8.61 1.5H5.25C4.01 21 3 20 3 18.75v-8.8c0-.67.3-1.3.8-1.72zM17.5 11a2.5 2.5 0 1 1 0 5 2.5 2.5 0 0 1 0-5"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function HomePersonIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
