// HomeGarageIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="m9.67 3.13-5.5 4.96a.5.5 0 0 0-.17.37v7.04c0 .28.22.5.5.5H6v-4.5c0-.83.67-1.5 1.5-1.5h5c.83 0 1.5.67 1.5 1.5V16h1.5a.5.5 0 0 0 .5-.5V8.46a.5.5 0 0 0-.17-.37l-5.5-4.96a.5.5 0 0 0-.66 0M4.5 17A1.5 1.5 0 0 1 3 15.5V8.46c0-.43.18-.83.5-1.11L9 2.39a1.5 1.5 0 0 1 2 0l5.5 4.96c.32.28.5.68.5 1.1v7.05c0 .83-.67 1.5-1.5 1.5zm8.5-1v-2H7v2zm0-4.5a.5.5 0 0 0-.5-.5h-5a.5.5 0 0 0-.5.5V13h6z"/></>),
  24: (<><path d="M11.51 3.68 4.76 9.4a.8.8 0 0 0-.26.57v9.27c0 .14.11.25.25.25H7v-5.25c0-.97.78-1.75 1.75-1.75h6.5c.97 0 1.75.78 1.75 1.75v5.25h2.25q.23-.02.25-.25V9.98q-.01-.35-.26-.57l-6.75-5.73a.75.75 0 0 0-.98 0M8.5 17.5v2h7v-2zm7-1.5v-1.75a.25.25 0 0 0-.25-.25h-6.5a.25.25 0 0 0-.25.25V16zM4.75 21C3.78 21 3 20.22 3 19.25V9.98c0-.66.29-1.3.8-1.72l6.74-5.73a2.25 2.25 0 0 1 2.92 0l6.75 5.73c.5.43.79 1.06.79 1.72v9.27c0 .97-.78 1.75-1.75 1.75z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function HomeGarageIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
