// IconArrowLeft — MyWorkDrive app icon (migrated from src/ui/icons.jsx).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
import React from 'react';

const VB = '0 0 16 13.9974';
const NW = 16, NH = 13.9974;

export function IconArrowLeft({ size = 20, ...props }) {
  const s = size / Math.max(NW, NH); // fit within a size×size box, preserving aspect
  return (
    <svg width={+(NW * s).toFixed(3)} height={+(NH * s).toFixed(3)} viewBox={VB} fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}><path d="M7.16289 13.8666C7.36683 14.0528 7.68308 14.0384 7.86926 13.8345C8.05544 13.6305 8.04105 13.3143 7.83711 13.1281L1.66925 7.49736H15.5C15.7761 7.49736 16 7.2735 16 6.99736C16 6.72122 15.7761 6.49736 15.5 6.49736H1.67214L7.83711 0.86927C8.04105 0.68309 8.05544 0.366835 7.86926 0.162895C7.68308 -0.0410457 7.36683 -0.0554433 7.16289 0.130737L0.246538 6.44478C0.106589 6.57254 0.0267601 6.74008 0.00704861 6.91323C0.00241375 6.94058 0 6.96869 0 6.99736C0 7.02423 0.00211954 7.05061 0.00620079 7.07633C0.0243754 7.25224 0.104488 7.4229 0.246538 7.55258L7.16289 13.8666Z" fill="currentColor"/></svg>
  );
}
