// IconChevronDown — MyWorkDrive app icon (migrated from src/ui/icons.jsx).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
import React from 'react';

const VB = '0 0 12.0008 6.49919';
const NW = 12.0008, NH = 6.49919;

export function IconChevronDown({ size = 20, ...props }) {
  const s = size / Math.max(NW, NH); // fit within a size×size box, preserving aspect
  return (
    <svg width={+(NW * s).toFixed(3)} height={+(NH * s).toFixed(3)} viewBox={VB} fill="none" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}><path d="M11.8537 0.145818C12.0493 0.340732 12.0499 0.657314 11.855 0.852924L6.39 6.33741C6.17505 6.55312 5.82574 6.55312 5.6108 6.33741L0.145817 0.852923C-0.0490969 0.657313 -0.0485323 0.340731 0.147077 0.145817C0.342687 -0.0490966 0.659269 -0.0485327 0.854182 0.147077L6.0004 5.31166L11.1466 0.147077C11.3415 -0.0485323 11.6581 -0.0490961 11.8537 0.145818Z" fill="currentColor"/></svg>
  );
}
