// KeyboardLayoutResizeIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M3 3.5c0-.28.22-.5.5-.5h7a.5.5 0 0 0 0-1h-7C2.67 2 2 2.67 2 3.5v4a.5.5 0 0 0 1 0zM3.5 9C2.67 9 2 9.67 2 10.5v6c0 .83.67 1.5 1.5 1.5h8c.83 0 1.5-.67 1.5-1.5v-6c0-.83-.67-1.5-1.5-1.5zM3 10.5c0-.28.22-.5.5-.5h8c.28 0 .5.22.5.5v6a.5.5 0 0 1-.5.5h-8a.5.5 0 0 1-.5-.5zM5.5 15a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1zm0-2.75a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0m2 .75a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5m3.5-.75a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0M17.5 9c.28 0 .5.22.5.5v7c0 .83-.67 1.5-1.5 1.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 0 .5-.5v-7c0-.28.22-.5.5-.5m-4-7a.5.5 0 0 0 0 1h2.8l-4.15 4.15a.5.5 0 0 0 .7.7L17 3.71V6.5a.5.5 0 0 0 1 0v-4a.5.5 0 0 0-.5-.5z"/></>),
  24: (<><path d="M13.25 10.5c1.2 0 2.17.93 2.24 2.1l.01.15v7c0 1.2-.93 2.17-2.1 2.24l-.15.01h-9c-1.2 0-2.17-.93-2.24-2.1L2 19.75v-7c0-1.2.93-2.17 2.1-2.24l.15-.01zm8 0c.38 0 .7.28.74.65l.01.1v8.5c0 1.2-.93 2.17-2.1 2.24l-.15.01h-2a.75.75 0 0 1-.1-1.5h2.1c.38 0 .7-.28.74-.65l.01-.1v-8.5c0-.41.34-.75.75-.75m-8 1.5h-9c-.38 0-.7.28-.74.65l-.01.1v7c0 .38.28.7.65.74l.1.01h9c.38 0 .7-.28.74-.65l.01-.1v-7a.75.75 0 0 0-.75-.75m-2.5 5.5c.41 0 .75.34.75.75 0 .38-.34.75-.75.75h-4a.75.75 0 0 1-.75-.75c0-.38.34-.75.75-.75zM6 13.5a1 1 0 1 1 0 2 1 1 0 0 1 0-2m5.5 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2m-2.75 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2M21.25 2a1 1 0 0 1 .33.07l.04.03.08.05.08.07.05.06.01.01.04.05a1 1 0 0 1 .11.3l.01.11v5a.75.75 0 0 1-1.5.1V4.56l-4.47 4.47a.75.75 0 0 1-1.13-.98l.07-.08 4.47-4.47h-3.19a.75.75 0 0 1-.74-.65l-.01-.1c0-.38.28-.7.65-.74l.1-.01zm-8.5 0a.75.75 0 0 1 .1 1.5h-8.6c-.38 0-.7.28-.74.65l-.01.1v4a.75.75 0 0 1-1.5.1v-4.1c0-1.2.93-2.17 2.1-2.24L4.25 2z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function KeyboardLayoutResizeIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
