// LaptopSettingsIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M3 7c0-1.1.9-2 2-2h10a2 2 0 0 1 2 2v2.6q-.48-.24-1-.4V7a1 1 0 0 0-1-1H5a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h4.2q-.13.49-.18 1H5a2 2 0 0 1-2-2zm6.2 9q-.13-.49-.18-1H2.5a.5.5 0 0 0 0 1zm2.86-4.56a2 2 0 0 1-1.43 2.48l-.46.12a5 5 0 0 0 .01 1.01l.35.09A2 2 0 0 1 12 17.66l-.13.42q.39.3.84.52l.32-.35a2 2 0 0 1 2.91 0l.34.36q.45-.2.82-.5l-.16-.55a2 2 0 0 1 1.44-2.48l.46-.12a5 5 0 0 0-.01-1.01l-.35-.09A2 2 0 0 1 17 11.34l.13-.42q-.39-.3-.84-.52l-.32.35a2 2 0 0 1-2.91 0l-.34-.36q-.45.2-.82.5zm2.44 4.06a1 1 0 1 1 0-2 1 1 0 0 1 0 2"/></>),
  24: (<><path d="M6.25 4C5.01 4 4 5 4 6.25v7.5C4 14.99 5 16 6.25 16h4.77q.06-.78.3-1.5H6.24a.75.75 0 0 1-.75-.75v-7.5c0-.41.34-.75.75-.75h11.5c.41 0 .75.34.75.75v3.83q.79.12 1.5.42V6.25C20 5.01 19 4 17.75 4zm-3.5 13.5h8.33q.12.79.42 1.5H2.75a.75.75 0 0 1 0-1.5m11.53-4.52a2 2 0 0 1-1.44 2.5l-.59.14a6 6 0 0 0 0 1.8l.55.13a2 2 0 0 1 1.45 2.51l-.19.64q.66.58 1.49.92l.49-.52a2 2 0 0 1 2.9 0l.5.52a5 5 0 0 0 1.48-.91l-.2-.69a2 2 0 0 1 1.44-2.5l.59-.14a6 6 0 0 0-.01-1.8l-.54-.13a2 2 0 0 1-1.45-2.51l.19-.63q-.66-.59-1.49-.93l-.49.52a2 2 0 0 1-2.9 0l-.5-.52q-.82.34-1.48.9zM17.5 18c-.8 0-1.45-.67-1.45-1.5S16.7 15 17.5 15s1.45.67 1.45 1.5S18.3 18 17.5 18"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function LaptopSettingsIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
