// LearningAppIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M11 1H5a2 2 0 0 0-2 2v10c0 1.1.9 2 2 2h2.26a6 6 0 0 1-.66-1H5a1 1 0 0 1-1-1h2.2q-.13-.5-.18-1H4V3a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v3.02q.51.05 1 .19V3a2 2 0 0 0-2-2M6 3a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1h4a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1zm0 1h4v1H6zm10 7.5a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0M10 13c0 .38.42.62.76.42l2.5-1.5a.5.5 0 0 0 0-.85l-2.5-1.5A.5.5 0 0 0 10 10z"/></>),
  20: (<><path d="M6 3h8a1 1 0 0 1 1 1v5.02q.51.05 1 .19V4a2 2 0 0 0-2-2H6a2 2 0 0 0-2 2v12c0 1.1.9 2 2 2h4.26a6 6 0 0 1-.66-1H6a1 1 0 0 1-1-1h4.2q-.13-.49-.18-1H5V4a1 1 0 0 1 1-1m1 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1zm6 1v1H7V5zm6 9.5a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0m-4.98-1.97a.5.5 0 0 0-.45-.03l-.15.1-.1.17a1 1 0 0 0-.05.2v3.07a.5.5 0 0 0 .15.35q.06.07.16.12a.5.5 0 0 0 .32.01l.13-.06 2.3-1.57q.1-.06.16-.18a.5.5 0 0 0 0-.49 1 1 0 0 0-.17-.18z"/></>),
  24: (<><path d="M5.5 2A2.5 2.5 0 0 0 3 4.5v15A2.5 2.5 0 0 0 5.5 22h7.31a7 7 0 0 1-1.08-1.5H5.5a1 1 0 0 1-1-1h6.81a7 7 0 0 1-.3-1.5H4.5V4.5a1 1 0 0 1 1-1H17a1 1 0 0 1 1 1v6.52q.78.06 1.5.3V4.5A2.5 2.5 0 0 0 17 2zM23 17.5a5.5 5.5 0 1 0-11 0 5.5 5.5 0 0 0 11 0m-6.09-2.4 2.81 1.84a.6.6 0 0 1 .28.52q0 .15-.07.3a1 1 0 0 1-.2.22l-2.8 1.92-.17.07-.16.03a1 1 0 0 1-.23-.05 1 1 0 0 1-.2-.13l-.12-.2a1 1 0 0 1-.05-.24v-3.76a.6.6 0 0 1 .37-.57.55.55 0 0 1 .55.05M6 6a1 1 0 0 1 1-1h8a1 1 0 0 1 1 1v2a1 1 0 0 1-1 1H7a1 1 0 0 1-1-1zm1.5 1.5h7v-1h-7z"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function LearningAppIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
