// LocationLiveIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M8.53 3.01 9 3a7 7 0 0 1 6.98 7.47.5.5 0 1 0 1 .07L17 10A8 8 0 0 0 8.46 2a.5.5 0 1 0 .07 1M8 4.98a.5.5 0 0 1 .52-.47 6.25 6.25 0 0 1 5.97 5.97.5.5 0 1 1-1 .04A5.25 5.25 0 0 0 8.49 5.5.5.5 0 0 1 8 4.98m-.5 7.64a1.13 1.13 0 1 0 0-2.25 1.13 1.13 0 0 0 0 2.25m-3.18 2.06 2.83 2.83a.5.5 0 0 0 .7 0l2.83-2.83a4.5 4.5 0 1 0-6.36 0m.7-.7a3.5 3.5 0 1 1 4.95 0L7.5 16.44z"/></>),
  24: (<><path d="M9.8 2.03a.75.75 0 0 0-.1 1.5 10.5 10.5 0 0 1 9.78 9.77.75.75 0 1 0 1.5-.1A12 12 0 0 0 9.8 2.03m-1.3 13.6a1.13 1.13 0 1 0 0-2.26 1.13 1.13 0 0 0 0 2.25m-.52 6.14-.4-.38-2.96-2.96a5.5 5.5 0 1 1 7.77 0l-2.01 2-1.35 1.34c-.29.3-.76.3-1.05 0m-2.3-10.05a4 4 0 0 0 0 5.65l2.04 2.03.78.78.82-.8 2.01-2a4 4 0 1 0-5.65-5.66M9.82 5.5A.75.75 0 0 0 9.68 7 7 7 0 0 1 16 13.3a.75.75 0 1 0 1.5-.13A8.5 8.5 0 0 0 9.82 5.5"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function LocationLiveIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
