// MailOffIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="m12.27 12.98 1.88 1.87a.5.5 0 0 0 .7-.7l-13-13a.5.5 0 1 0-.7.7l1.59 1.6A2 2 0 0 0 2 5v6c0 1.1.9 2 2 2h8q.14 0 .27-.02M11.3 12H4a1 1 0 0 1-1-1V6.88l4.76 2.56a.5.5 0 0 0 .48 0l.32-.17zM7.4 8.11 3 5.74V5a1 1 0 0 1 .45-.84zM13 5.74l-3.34 1.8.74.74 2.6-1.4v4l.86.86A2 2 0 0 0 14 11V5a2 2 0 0 0-2-2H5.12l1 1H12a1 1 0 0 1 1 1z"/></>),
  20: (<><path d="M2.85 2.15a.5.5 0 1 0-.7.7L3.5 4.21A2.5 2.5 0 0 0 2 6.5v8A2.5 2.5 0 0 0 4.5 17h11q.36 0 .7-.1l.95.95a.5.5 0 0 0 .7-.7zM15.3 16H4.5A1.5 1.5 0 0 1 3 14.5V7.96l6.75 3.97.08.04q.23.08.42-.04l.61-.36zm-5.16-5.16-.13.08L3 6.8v-.3c0-.76.57-1.4 1.3-1.49zM17 6.8l-5.09 3 .73.72L17 7.96v6.54q0 .18-.04.34l.78.78q.26-.52.26-1.12v-8A2.5 2.5 0 0 0 15.5 4H6.12l1 1h8.38c.83 0 1.5.67 1.5 1.5z"/></>),
  24: (<><path d="M3.28 2.22a.75.75 0 1 0-1.06 1.06l1.25 1.25A3.3 3.3 0 0 0 2 7.25v9.68A3.25 3.25 0 0 0 5.26 20h13.68l1.79 1.78a.75.75 0 0 0 1.06-1.06zM17.44 18.5H5.1c-.9-.08-1.61-.83-1.61-1.75V9.37l8.15 4.3.1.04q.3.1.6-.05l.17-.08zm-7.36-7.36L3.5 7.68V7.1c.06-.67.49-1.23 1.07-1.47zM20.5 7.68 14.18 11l1.11 1.11 5.21-2.74v7.52l-.07.36 1.13 1.13q.43-.73.44-1.63V7.07A3.25 3.25 0 0 0 18.74 4H7.18l1.5 1.5H18.9c.9.08 1.61.83 1.61 1.75z"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function MailOffIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
