// MailShieldIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
};
const C = {
  16: (<><path d="M7 5H3a2 2 0 0 0-2 2v6c0 1.1.9 2 2 2h8a2 2 0 0 0 2-2v-2.54a7 7 0 0 1-1 .44V13a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V8.88l4.76 2.56a.5.5 0 0 0 .48 0l2.32-1.25a6 6 0 0 1-.86-.68l-1.7.92-5-2.69V7a1 1 0 0 1 1-1h4.05L7 5.4V5m7-2.56a4 4 0 0 1-1-.35 5 5 0 0 1-1.25-.98.33.33 0 0 0-.5 0 3.9 3.9 0 0 1-2.9 1.39c-.2 0-.35.17-.35.38v2.48q.06 1.55.75 2.64.36.55.88 1 .72.6 1.76.98.11.04.22 0A4.75 4.75 0 0 0 15 5.13V2.8a.36.36 0 0 0-.35-.3q-.33 0-.65-.06"/></>),
  20: (<><path d="M18 2.62a4 4 0 0 1-1-.27 5 5 0 0 1-1.72-1.23.4.4 0 0 0-.56 0 4.5 4.5 0 0 1-3.32 1.55.4.4 0 0 0-.4.41v2.77A5.5 5.5 0 0 0 12.01 9q.4.55.99 1 .78.6 1.87.98.13.04.26 0 3.86-1.35 3.87-5.4V3a.4.4 0 0 0-.4-.33q-.3 0-.6-.05M10 4H4.5A2.5 2.5 0 0 0 2 6.5v8A2.5 2.5 0 0 0 4.5 17h11a2.5 2.5 0 0 0 2.5-2.5v-4.03q-.46.4-1 .74v3.29c0 .83-.67 1.5-1.5 1.5h-11A1.5 1.5 0 0 1 3 14.5V7.96l6.75 3.97.08.04q.23.08.42-.04l2.05-1.2a6 6 0 0 1-.76-.72l-1.54.91L3 6.8v-.3C3 5.67 3.67 5 4.5 5H10z"/></>),
};
const SIZES = [16, 20];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function MailShieldIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
