// MailOpenPersonIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M2.49 6h.01l-.4-.21a1 1 0 0 1 .16-.13L8 2.57l5.95 3.2-.29.15a3 3 0 0 1 .57.83l.27-.14a.95.95 0 0 0 0-1.68L8.23 1.56a.5.5 0 0 0-.47 0L1.8 4.78A1.5 1.5 0 0 0 1 6.1V12c0 1.1.9 2 2 2h4.37a3 3 0 0 1-.33-1H3a1 1 0 0 1-1-1V6.87l5.53 2.95a1 1 0 0 0 .94 0l.47-.25q-.26-.43-.37-.94l-.57.3zM13.5 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0m1.5 4.5c0 1.25-1 2.5-3.5 2.5S8 13.75 8 12.5c0-.83.67-1.5 1.5-1.5h4c.83 0 1.5.67 1.5 1.5"/></>),
  20: (<><path d="M10 3.08 3.49 7 3.47 7 10 10.92 16.53 7zM9.98 12a1 1 0 0 1-.24-.07L3 7.88v5.62c0 .83.67 1.5 1.5 1.5h7q-.33.45-.45 1H4.5A2.5 2.5 0 0 1 2 13.5V7.85a2 2 0 0 1 .97-1.72l6.76-4.05a.5.5 0 0 1 .53 0l6.93 4.15a.9.9 0 0 1 0 1.54l-2.1 1.26a3 3 0 0 0-2.02 1.21l-2.81 1.69a.5.5 0 0 1-.28.07m7.52 0a2 2 0 1 1-4 0 2 2 0 0 1 4 0m1.5 4.5c0 1.25-1 2.5-3.5 2.5S12 17.75 12 16.5c0-.83.67-1.5 1.5-1.5h4c.83 0 1.5.67 1.5 1.5"/></>),
  24: (<><path d="M12 3.62 3.9 8.43l8.1 4.22 8.23-4.22zm-.17 10.61-.19-.07L3.5 9.91v6.84c0 .92.7 1.67 1.6 1.74l.15.01h8.06q-.3.57-.31 1.27V20H5.25a3.25 3.25 0 0 1-3.24-3.07L2 16.75V9.1c0-.73.36-1.42.96-1.84l.14-.1 8.5-5.05a.8.8 0 0 1 .78 0l9 5.26c.85.5.82 1.74-.06 2.19L18.52 11h-.02a3.5 3.5 0 0 0-2.85 1.47l-3.3 1.7a.8.8 0 0 1-.52.06m9.17.27a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0m2 5.38c0 1.55-1.29 3.12-4.5 3.12S14 21.44 14 19.88v-.1c0-.99.8-1.78 1.77-1.78h5.46c.98 0 1.77.8 1.77 1.77z"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function MailOpenPersonIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
