// MailRewindIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 25 24',
};
const C = {
  16: (<><path d="M12 7V5.8l2.36 1.97A1 1 0 0 0 16 7V2a1 1 0 0 0-1.64-.77L12 3.2V2a1 1 0 0 0-1.64-.77l-3 2.5a1 1 0 0 0 0 1.54l3 2.5A1 1 0 0 0 12 7m-3.76 3.44L10.9 9a2 2 0 0 1-1.2-.46l-.01-.02-1.7.91-5-2.69V6a1 1 0 0 1 1-1h2.06a2 2 0 0 1 0-1H4a2 2 0 0 0-2 2v6c0 1.1.9 2 2 2h8a2 2 0 0 0 2-2V8.73l-.28-.2-.72-.6V12a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V7.88l4.76 2.56a.5.5 0 0 0 .48 0"/></>),
  20: (<><path d="M16 8V6.8l2.36 1.97A1 1 0 0 0 20 8V3a1 1 0 0 0-1.64-.77L16 4.2V3a1 1 0 0 0-1.64-.77l-3 2.5a1 1 0 0 0 0 1.54l3 2.5A1 1 0 0 0 16 8m-2.28 1.54.27.19-3.74 2.2a.5.5 0 0 1-.42.04l-.08-.04L3 7.96v6.54c0 .83.67 1.5 1.5 1.5h11c.83 0 1.5-.67 1.5-1.5V8.94l.72.6.28.2v4.76a2.5 2.5 0 0 1-2.5 2.5h-11A2.5 2.5 0 0 1 2 14.5v-8A2.5 2.5 0 0 1 4.5 4h6.18q-.47.43-.62 1H4.5C3.67 5 3 5.67 3 6.5v.3l7 4.12 3.15-1.86z"/></>),
  24: (<><path d="M19 9V6.83l3.34 2.92A1 1 0 0 0 24 9V2a1 1 0 0 0-1.66-.75L19 4.17V2a1 1 0 0 0-1.66-.75l-4 3.5a1 1 0 0 0 0 1.5l4 3.5A1 1 0 0 0 19 9m-7 3.15L16.1 10l.59.52a2 2 0 0 0 .82.43l-5.16 2.72q-.3.15-.6.05l-.1-.05L3.5 9.37v7.38c0 .92.7 1.67 1.6 1.74l.15.01h13.5c.92 0 1.67-.7 1.74-1.6l.01-.15V9.47l1.19 1.04q.15.12.31.22v6.02a3.25 3.25 0 0 1-3.07 3.24l-.18.01H5.25a3.25 3.25 0 0 1-3.24-3.07L2 16.75v-9.5a3.25 3.25 0 0 1 3.07-3.24L5.25 4h7.43A2 2 0 0 0 12 5.5H5.25c-.92 0-1.67.7-1.74 1.6l-.01.15v.43z"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function MailRewindIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
