// MicRecordIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
};
const C = {
  16: (<><path d="M10.5 6a4.5 4.5 0 1 1 0 9 4.5 4.5 0 0 1 0-9m0 1a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7m0 1a2.5 2.5 0 1 1 0 5 2.5 2.5 0 0 1 0-5m-8-.5c.28 0 .5.22.5.5a3.5 3.5 0 0 0 2.04 3.18q.07.61.28 1.16A4.5 4.5 0 0 1 2 8c0-.28.22-.5.5-.5m4-5.5A2.5 2.5 0 0 1 9 4.5v.7q-.52.16-1 .4V4.5a1.5 1.5 0 1 0-3 0V8q.01.47.26.84-.18.56-.24 1.18A2.5 2.5 0 0 1 4 8V4.5A2.5 2.5 0 0 1 6.5 2"/></>),
  20: (<><path d="M9 13h.2q.18-.6.46-1.11A2 2 0 0 1 7 10V5a2 2 0 1 1 4 0v5q0 .14-.02.27.47-.39 1.02-.67V5a3 3 0 1 0-6 0v5a3 3 0 0 0 3 3m-4.5-3A4.5 4.5 0 0 0 9 14.5q.01 1.24.5 2.3v.7a.5.5 0 0 1-1 0v-2.02a5.5 5.5 0 0 1-5-5.48.5.5 0 0 1 1 0M17 14.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0m2 0a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0m-8 0a3.5 3.5 0 1 0 7 0 3.5 3.5 0 0 0-7 0"/></>),
  24: (<><path d="M11 17.5q.02 1.66.75 3.03v.72a.75.75 0 0 1-1.5.1v-2.37A6.75 6.75 0 0 1 4 12.48v-.73a.75.75 0 0 1 1.5-.1v.6a5.25 5.25 0 0 0 5.03 5.25H11M15 6v5.5a7 7 0 0 0-1.53.9q.03-.2.03-.4V6a2.5 2.5 0 0 0-5 0v6a2.5 2.5 0 0 0 3.3 2.37q-.42.76-.63 1.63H11a4 4 0 0 1-4-4V6a4 4 0 1 1 8 0m5 11.5a2.5 2.5 0 1 1-5 0 2.5 2.5 0 0 1 5 0m3 0a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0m-9.5 0a4 4 0 1 0 8 0 4 4 0 0 0-8 0"/></>),
  28: (<><path d="M8.5 6.5a4.5 4.5 0 1 1 9 0v7.12q-.81.36-1.5.88v-8a3 3 0 1 0-6 0v8a3 3 0 0 0 3.66 2.93q-.35.75-.51 1.57H13a4.5 4.5 0 0 1-4.5-4.5zM13.02 21H13a6.5 6.5 0 0 1-6.5-6.5v-.75a.75.75 0 1 0-1.5 0v.75a8 8 0 0 0 7.25 7.97v2.78a.75.75 0 0 0 1.5 0v-1.48a8 8 0 0 1-.73-2.77m7.48 4.5a5 5 0 1 1 0-10 5 5 0 0 1 0 10m0 1.5a6.5 6.5 0 1 0 0-13 6.5 6.5 0 0 0 0 13m0-3a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7"/></>),
};
const SIZES = [16, 20, 24, 28];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function MicRecordIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
