// MoleculeIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
  48: '0 0 48 48',
};
const C = {
  16: (<><path d="M11 8a3 3 0 1 0-2.7-1.7L5.94 7.45Q5.34 7.01 4.5 7a2.5 2.5 0 1 0 2.21 3.67l2.3 1.14L9 12a2 2 0 1 0 .35-1.13L7 9.69a2.5 2.5 0 0 0-.34-1.46l2.23-1.11A3 3 0 0 0 11 8m0-1a2 2 0 1 1 0-4 2 2 0 0 1 0 4m-6.5 4a1.5 1.5 0 1 1 0-3 1.5 1.5 0 0 1 0 3m7.5 1a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/></>),
  20: (<><path d="M13 10a4 4 0 1 0-3.77-2.67L7.1 8.39a3.5 3.5 0 1 0 1.3 5.08l2.69 1.38a2.5 2.5 0 1 0 .44-.9l-2.7-1.38a3.5 3.5 0 0 0-.82-3.51l1.66-.84A4 4 0 0 0 13 10m0-1a3 3 0 1 1 0-6 3 3 0 0 1 0 6m-7.5 5a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5m9.5 1.5a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0"/></>),
  24: (<><path d="M16 12a5 5 0 1 0-4.34-2.51l-2.71 1.8A3.99 3.99 0 0 0 2 14a4 4 0 0 0 7.18 2.43l3.89 1.94a3 3 0 1 0 .67-1.34l-3.89-1.94a4 4 0 0 0-.11-2.52l2.86-1.9c.9.82 2.09 1.33 3.4 1.33m0-1.5a3.5 3.5 0 1 1 0-7 3.5 3.5 0 0 1 0 7m-10 6a2.5 2.5 0 1 1 0-5 2.5 2.5 0 0 1 0 5M17.5 19a1.5 1.5 0 1 1-3 0 1.5 1.5 0 0 1 3 0"/></>),
  28: (<><path d="M19 14a6 6 0 1 0-5.36-3.3l-3.36 2.35a4.5 4.5 0 1 0-.3 5.3l5.2 3.04a3.5 3.5 0 1 0 .77-1.29l-5.23-3.05a4.5 4.5 0 0 0 .16-2.59l3.6-2.52A6 6 0 0 0 19 14m0-1.5a4.5 4.5 0 1 1 0-9 4.5 4.5 0 0 1 0 9m-12.5 6a3 3 0 1 1 0-6 3 3 0 0 1 0 6m14 4a2 2 0 1 1-4 0 2 2 0 0 1 4 0"/></>),
  48: (<><path d="M32 24a10 10 0 1 0-8.55-4.8l-5.38 3.58a8 8 0 1 0 .44 9.87l7.68 3.84a6.01 6.01 0 1 0 1.12-2.23l-7.68-3.84a8 8 0 0 0-.25-5.5l5.64-3.76A10 10 0 0 0 32 24m0-2.5a7.5 7.5 0 1 1 0-15 7.5 7.5 0 0 1 0 15m-20 12a5.5 5.5 0 1 1 0-11 5.5 5.5 0 0 1 0 11M35.5 38a3.5 3.5 0 1 1-7 0 3.5 3.5 0 0 1 7 0"/></>),
};
const SIZES = [16, 20, 24, 28, 48];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function MoleculeIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
