// MusicNoteOff2Icon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="m12.55 13.26 1.6 1.6a.5.5 0 0 0 .7-.71l-13-13a.5.5 0 1 0-.7.7L5 5.71v5.56A2 2 0 1 0 6 13V7.35l.48-.17 3.26 3.27a2 2 0 1 0 2.81 2.81m-.71-.71a1 1 0 1 1-1.39-1.39zM4 12a1 1 0 1 1 0 2 1 1 0 0 1 0-2m8-7.85-4.22 1.5.78.79L12 5.2v4.67l1 1V1.93a.8.8 0 0 0-1.07-.76L5.57 3.45l.78.78L12 2.2z"/></>),
  20: (<><path d="M2.85 2.15a.5.5 0 1 0-.7.7L7 7.71v5.79q-.64-.48-1.5-.5A2.5 2.5 0 1 0 8 15.5V8.7l3.41 3.42q-.4.6-.41 1.38a2.5 2.5 0 0 0 3.88 2.09l2.27 2.26a.5.5 0 0 0 .7-.7zm11.3 12.7q-.3.15-.65.15a1.5 1.5 0 0 1-1.35-2.15zM5.5 14a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3m8-3q-.18 0-.35.02l2.83 2.83.02-.35V3.18a1 1 0 0 0-1.3-.95l-7 2.18a1 1 0 0 0-.61.55l.91.92v-.51l7-2.19v1.95L9.1 6.98l.8.8 5.1-1.6v5.32q-.64-.48-1.5-.5"/></>),
  24: (<><path d="M8.5 9.56v6.07a3.5 3.5 0 1 0 1.5 2.62v-7.19l3.55 3.55q-.54.84-.55 1.89a3.5 3.5 0 0 0 5.39 2.95l2.33 2.33a.75.75 0 0 0 1.06-1.06L3.28 2.22a.75.75 0 1 0-1.06 1.06zm8.78 8.78a2 2 0 0 1-2.62-2.62zM6.5 16.5a2 2 0 1 1 0 4 2 2 0 0 1 0-4m10-3.5-.3.01 3.79 3.8a4 4 0 0 0 .01-.56V2.75a.75.75 0 0 0-.97-.72l-10 3q-.3.1-.44.37L10 6.82V6.3l8.5-2.55v2.43l-7.02 2.1 1.2 1.21 5.82-1.74v5.87a3.5 3.5 0 0 0-2-.63"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function MusicNoteOff2Icon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
