// NextFrameIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M4.5 3c.28 0 .5.22.5.5v13a.5.5 0 0 1-1 0v-13c0-.28.22-.5.5-.5m5.45.21A1.25 1.25 0 0 0 8 4.25v11.5c0 1 1.12 1.6 1.95 1.04l8.5-5.8c.73-.5.73-1.58 0-2.07zM9 4.25c0-.2.22-.32.39-.2l8.5 5.7c.15.1.15.32 0 .42l-8.5 5.79c-.17.11-.39 0-.39-.2z"/></>),
  24: (<><path d="M5.5 3.75a.75.75 0 0 0-1.5 0v16.5a.75.75 0 0 0 1.5 0zm6.24-.44A1.75 1.75 0 0 0 9 4.75v14.5a1.75 1.75 0 0 0 2.75 1.43l10.5-7.3c1-.7 1-2.19-.01-2.88zM10.5 4.75c0-.2.23-.32.4-.2l10.49 7.19c.14.1.14.31 0 .41l-10.5 7.3c-.16.12-.39 0-.39-.2z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function NextFrameIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
