// NoteEditIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M3 14.18A3 3 0 0 0 6 17h2l.06-.35.16-.65H5.85A2 2 0 0 1 4 14v-4h3.18A3 3 0 0 0 10 7V4h4.15A2 2 0 0 1 16 6v2q.52-.02 1 .13V5.82A3 3 0 0 0 14 3H9.45a2 2 0 0 0-1.24.59L3.59 8.2l-.12.13A2 2 0 0 0 3 9.62v4.56M7 9H4.22l.07-.09L8.91 4.3 9 4.22v2.93A2 2 0 0 1 7 9m2.98 5.38 4.83-4.83a1.87 1.87 0 1 1 2.64 2.64l-4.83 4.83a2 2 0 0 1-1.02.58l-1.5.37a.9.9 0 0 1-1.07-1.07l.37-1.5q.15-.6.58-1.02"/></>),
  24: (<><path d="M3 17.75C3 19.55 4.46 21 6.25 21h4.92l.35-1.42.02-.08H6.25c-.97 0-1.75-.78-1.75-1.75V11h3.43A3.25 3.25 0 0 0 11 7.74V4.5h6.75c.97 0 1.75.78 1.75 1.75v4.98q.73-.28 1.5-.22V6.25C21 4.45 19.54 3 17.75 3h-6.88c-.6 0-1.17.24-1.59.66L3.66 9.28c-.42.42-.66 1-.66 1.6zM7.75 9.5H5.56L9.5 5.56V7.9c-.08.9-.83 1.61-1.75 1.61m11.35 3.17-5.9 5.9q-.54.54-.7 1.25l-.47 1.83c-.2.8.53 1.52 1.32 1.32l1.83-.46q.71-.18 1.25-.7l5.9-5.9a2.29 2.29 0 0 0-3.23-3.24"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function NoteEditIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
