// OvenIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
  48: '0 0 48 48',
};
const C = {
  20: (<><path d="M6 3a3 3 0 0 0-3 3v8a3 3 0 0 0 3 3h8a3 3 0 0 0 3-3V6a3 3 0 0 0-3-3zM4 14V8h12v6a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2m12-7H4V6c0-1.1.9-2 2-2h8a2 2 0 0 1 2 2zm-9.25-.75a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5m6.5 0a.75.75 0 1 0 0-1.5.75.75 0 0 0 0 1.5m-2.5-.75a.75.75 0 1 1-1.5 0 .75.75 0 0 1 1.5 0M6 9a1 1 0 0 0-1 1v4a1 1 0 0 0 1 1h8a1 1 0 0 0 1-1v-4a1 1 0 0 0-1-1zm0 5v-4h8v4z"/></>),
  24: (<><path d="M3 6.25C3 4.45 4.46 3 6.25 3h11.5C19.55 3 21 4.46 21 6.25v11.5c0 1.8-1.46 3.25-3.25 3.25H6.25A3.25 3.25 0 0 1 3 17.75zm16.5 0c0-.97-.78-1.75-1.75-1.75H6.25c-.97 0-1.75.78-1.75 1.75V8h15zm0 11.5V9.5h-15v8.25c0 .97.78 1.75 1.75 1.75h11.5c.97 0 1.75-.78 1.75-1.75M8 7.25a1 1 0 1 0 0-2 1 1 0 0 0 0 2m5-1a1 1 0 1 1-2 0 1 1 0 0 1 2 0m3 1a1 1 0 1 0 0-2 1 1 0 0 0 0 2M7.5 16.5v-4h9v4zM7.25 11C6.56 11 6 11.56 6 12.25v4.5c0 .69.56 1.25 1.25 1.25h9.5c.69 0 1.25-.56 1.25-1.25v-4.5c0-.69-.56-1.25-1.25-1.25z"/></>),
  48: (<><path d="M6 12.25C6 8.8 8.8 6 12.25 6h23.5C39.2 6 42 8.8 42 12.25v23.5C42 39.2 39.2 42 35.75 42h-23.5A6.25 6.25 0 0 1 6 35.75zm2.5 23.5a3.75 3.75 0 0 0 3.75 3.75h23.5a3.75 3.75 0 0 0 3.75-3.75V18.5h-31zm0-23.5V16h31v-3.75a3.75 3.75 0 0 0-3.75-3.75h-23.5a3.75 3.75 0 0 0-3.75 3.75m7.5 2a2 2 0 1 0 0-4 2 2 0 0 0 0 4m8 0a2 2 0 1 0 0-4 2 2 0 0 0 0 4m10-2a2 2 0 1 1-4 0 2 2 0 0 1 4 0M13.5 34.5v-11h21v11zM12.75 21c-.97 0-1.75.78-1.75 1.75v12.5c0 .97.78 1.75 1.75 1.75h22.5c.97 0 1.75-.78 1.75-1.75v-12.5c0-.97-.78-1.75-1.75-1.75z"/></>),
};
const SIZES = [20, 24, 48];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function OvenIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
