// PaddingLeftIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M2 3.5a.5.5 0 0 1 1 0v1a.5.5 0 0 1-1 0zm0 3a.5.5 0 0 1 1 0v2a.5.5 0 0 1-1 0zm0 4a.5.5 0 0 1 1 0v2a.5.5 0 0 1-1 0zm0 4a.5.5 0 0 1 1 0v1a.5.5 0 0 1-1 0zm2.15-4.65a.5.5 0 0 1 0-.7l4.5-4.5a.5.5 0 1 1 .7.7L5.71 9h9.79a.5.5 0 0 1 0 1H5.7l3.65 3.65a.5.5 0 0 1-.7.7zM17 3.5a.5.5 0 0 1 1 0v12a.5.5 0 0 1-1 0z"/></>),
  24: (<><path d="M2.75 4.5a.75.75 0 0 0-.75.75v.87a.75.75 0 0 0 1.5 0v-.87a.75.75 0 0 0-.75-.75m0 3.47a.75.75 0 0 0-.75.75v1.73a.75.75 0 0 0 1.5 0V8.72a.75.75 0 0 0-.75-.75m0 4.33a.75.75 0 0 0-.75.75v1.73a.75.75 0 0 0 1.5 0v-1.73a.75.75 0 0 0-.75-.75m0 4.33a.75.75 0 0 0-.75.75v.87a.75.75 0 0 0 1.5 0v-.87a.75.75 0 0 0-.75-.75M21.25 4.5a.75.75 0 0 0-.75.75v13a.75.75 0 0 0 1.5 0v-13a.75.75 0 0 0-.75-.75M5.22 12.28a.75.75 0 0 1 0-1.06l5-5a.75.75 0 1 1 1.06 1.06L7.56 11h10.69a.75.75 0 0 1 0 1.5H7.56l3.72 3.72a.75.75 0 1 1-1.06 1.06z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function PaddingLeftIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
