// PanelLeftHeaderAddIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
  48: '0 0 48 48',
};
const C = {
  16: (<><path d="M1 4.5v5A2.5 2.5 0 0 0 3.5 12H6V6.5h7v-2A2.5 2.5 0 0 0 10.5 2h-7A2.5 2.5 0 0 0 1 4.5m11 0v1H6V3h4.5c.83 0 1.5.67 1.5 1.5M3.5 3H5v8H3.5A1.5 1.5 0 0 1 2 9.5v-5C2 3.67 2.67 3 3.5 3M7 11.5a4.5 4.5 0 1 1 9 0 4.5 4.5 0 0 1-9 0m5-2a.5.5 0 0 0-1 0V11H9.5a.5.5 0 0 0 0 1H11v1.5a.5.5 0 0 0 1 0V12h1.5a.5.5 0 0 0 0-1H12z"/></>),
  20: (<><path d="M5 3a3 3 0 0 0-3 3v7a3 3 0 0 0 3 3h4.2q-.13-.49-.18-1H8.5V8H17v1.6q.54.27 1 .66V6a3 3 0 0 0-3-3zm12 4H8.5V4H15a2 2 0 0 1 2 2zM5 4h2.5v11H5a2 2 0 0 1-2-2V6c0-1.1.9-2 2-2m14 10.5a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0m-4-2a.5.5 0 0 0-1 0V14h-1.5a.5.5 0 0 0 0 1H14v1.5a.5.5 0 0 0 1 0V15h1.5a.5.5 0 0 0 0-1H15z"/></>),
  24: (<><path d="M5.25 4A3.25 3.25 0 0 0 2 7.25v9.5C2 18.55 3.46 20 5.25 20h6.25q-.3-.71-.42-1.5H9.5v-8h11v1.23q.83.44 1.5 1.08V7.25C22 5.45 20.54 4 18.75 4zM20.5 9h-11V5.5h9.25c.97 0 1.75.78 1.75 1.75zM5.25 5.5H8v13H5.25c-.97 0-1.75-.78-1.75-1.75v-9.5c0-.97.78-1.75 1.75-1.75M23 17.5a5.5 5.5 0 1 0-11 0 5.5 5.5 0 0 0 11 0m-5 .5v2.5a.5.5 0 1 1-1 0V18h-2.5a.5.5 0 0 1 0-1H17v-2.5a.5.5 0 1 1 1 0V17h2.5a.5.5 0 0 1 0 1z"/></>),
  28: (<><path d="M2 7.75A3.75 3.75 0 0 1 5.75 4h16.5A3.75 3.75 0 0 1 26 7.75v7.65q-.67-.72-1.5-1.25V11.5h-14v10h2.57q.1.78.36 1.5H5.75A3.75 3.75 0 0 1 2 19.25zm22.5 0c0-1.24-1-2.25-2.25-2.25H10.5V10h14zM5.75 5.5c-1.24 0-2.25 1-2.25 2.25v11.5c0 1.24 1.01 2.25 2.25 2.25H9v-16zM27 20.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0m-6-4a.5.5 0 0 0-1 0V20h-3.5a.5.5 0 0 0 0 1H20v3.5a.5.5 0 0 0 1 0V21h3.5a.5.5 0 0 0 0-1H21z"/></>),
  48: (<><path d="M4 13.25C4 9.8 6.8 7 10.25 7h27.5C41.2 7 44 9.8 44 13.25v12.37q-1.14-1.09-2.5-1.88V20.5H18.25v18h4.23q.36 1.31.98 2.5H10.25A6.25 6.25 0 0 1 4 34.75zM18.25 18H41.5v-4.75a3.75 3.75 0 0 0-3.75-3.75h-19.5zm-8-8.5a3.75 3.75 0 0 0-3.75 3.75v21.5a3.75 3.75 0 0 0 3.75 3.75h5.5v-29zM35 46a11 11 0 1 0 0-22 11 11 0 0 0 0 22m0-19a1 1 0 0 1 1 1v6h6a1 1 0 1 1 0 2h-6v6a1 1 0 1 1-2 0v-6h-6a1 1 0 1 1 0-2h6v-6a1 1 0 0 1 1-1"/></>),
};
const SIZES = [16, 20, 24, 28, 48];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function PanelLeftHeaderAddIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
