// PanelLeftAddIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
  48: '0 0 48 48',
};
const C = {
  16: (<><path d="M1 4.5A2.5 2.5 0 0 1 3.5 2h7A2.5 2.5 0 0 1 13 4.5v1.7q-.49-.13-1-.18V4.5c0-.83-.67-1.5-1.5-1.5H6v8h.02a6 6 0 0 0 0 1H3.5A2.5 2.5 0 0 1 1 9.5zM5 3H3.5C2.67 3 2 3.67 2 4.5v5c0 .83.67 1.5 1.5 1.5H5zm11 8.5a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0m-4-2a.5.5 0 0 0-1 0V11H9.5a.5.5 0 0 0 0 1H11v1.5a.5.5 0 0 0 1 0V12h1.5a.5.5 0 0 0 0-1H12z"/></>),
  20: (<><path d="M2 6a3 3 0 0 1 3-3h10a3 3 0 0 1 3 3v4.26a6 6 0 0 0-1-.66V6a2 2 0 0 0-2-2H8.5v11h.52q.05.51.19 1H5a3 3 0 0 1-3-3zm5.5-2H5a2 2 0 0 0-2 2v7c0 1.1.9 2 2 2h2.5zM19 14.5a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0m-4-2a.5.5 0 0 0-1 0V14h-1.5a.5.5 0 0 0 0 1H14v1.5a.5.5 0 0 0 1 0V15h1.5a.5.5 0 0 0 0-1H15z"/></>),
  24: (<><path d="M2 7.25C2 5.45 3.46 4 5.25 4h13.5C20.55 4 22 5.46 22 7.25v5.56a7 7 0 0 0-1.5-1.08V7.25c0-.97-.78-1.75-1.75-1.75H9.5v13h1.58q.12.79.42 1.5H5.25A3.25 3.25 0 0 1 2 16.75zM8 5.5H5.25c-.97 0-1.75.78-1.75 1.75v9.5c0 .97.78 1.75 1.75 1.75H8zm15 12a5.5 5.5 0 1 0-11 0 5.5 5.5 0 0 0 11 0m-5 .5v2.5a.5.5 0 1 1-1 0V18h-2.5a.5.5 0 0 1 0-1H17v-2.5a.5.5 0 1 1 1 0V17h2.5a.5.5 0 0 1 0 1z"/></>),
  28: (<><path d="M5.75 4A3.75 3.75 0 0 0 2 7.75v11.5A3.75 3.75 0 0 0 5.75 23h7.67q-.25-.72-.36-1.5H10.5v-16h11.75c1.24 0 2.25 1 2.25 2.25v6.4q.83.53 1.5 1.25V7.75A3.75 3.75 0 0 0 22.25 4zM3.5 7.75c0-1.24 1-2.25 2.25-2.25H9v16H5.75c-1.24 0-2.25-1-2.25-2.25zM27 20.5a6.5 6.5 0 1 1-13 0 6.5 6.5 0 0 1 13 0m-6-4a.5.5 0 0 0-1 0V20h-3.5a.5.5 0 0 0 0 1H20v3.5a.5.5 0 0 0 1 0V21h3.5a.5.5 0 0 0 0-1H21z"/></>),
  48: (<><path d="M10.25 7A6.25 6.25 0 0 0 4 13.25v21.5C4 38.2 6.8 41 10.25 41h13.21q-.61-1.19-.98-2.5h-4.23v-29h19.5a3.75 3.75 0 0 1 3.75 3.75v10.49q1.36.79 2.5 1.88V13.25C44 9.8 41.2 7 37.75 7zM6.5 13.25a3.75 3.75 0 0 1 3.75-3.75h5.5v29h-5.5a3.75 3.75 0 0 1-3.75-3.75zM46 35a11 11 0 1 1-22 0 11 11 0 0 1 22 0m-10-7a1 1 0 1 0-2 0v6h-6a1 1 0 1 0 0 2h6v6a1 1 0 1 0 2 0v-6h6a1 1 0 1 0 0-2h-6z"/></>),
};
const SIZES = [16, 20, 24, 28, 48];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function PanelLeftAddIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
