// PersonArrowRightIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M2 10c0 1.8 1.55 3.65 4.22 3.96a6 6 0 0 1-.72-1.16C3.88 12.33 3 11.13 3 10v-.5c0-.28.22-.5.5-.5h1.7q.16-.52.4-1H3.5C2.67 8 2 8.67 2 9.5zm7.75-5.75q0 .43-.12.82-.73.12-1.39.41A1.74 1.74 0 0 0 7 2.5a1.75 1.75 0 1 0 .4 3.45q-.6.42-1.07.97a2.75 2.75 0 1 1 3.42-2.67M15 10.5a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0m-2.15.35a.5.5 0 0 0 .15-.35.5.5 0 0 0-.15-.35l-2-2a.5.5 0 0 0-.7.7L11.29 10H8.5a.5.5 0 0 0 0 1h2.8l-1.15 1.15a.5.5 0 0 0 .7.7z"/></>),
  20: (<><path d="M9 2a4 4 0 1 0 0 8 4 4 0 0 0 0-8M6 6a3 3 0 1 1 6 0 3 3 0 0 1-6 0m-2 5a2 2 0 0 0-2 2c0 1.7.83 2.97 2.13 3.8A9 9 0 0 0 9 18q.62 0 1.21-.06A6 6 0 0 1 9.6 17L9 17a8 8 0 0 1-4.33-1.05A3.4 3.4 0 0 1 3 13a1 1 0 0 1 1-1h5.6q.27-.54.66-1zm15 3.5a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0m-2.15.35a.5.5 0 0 0 .15-.35.5.5 0 0 0-.15-.35l-2-2a.5.5 0 0 0-.7.7L15.29 14H12.5a.5.5 0 0 0 0 1h2.8l-1.15 1.15a.5.5 0 0 0 .7.7z"/></>),
  24: (<><path d="M11.31 15.5q.27-.8.71-1.5H4.25C3.01 14 2 15 2 16.25v.58c0 .89.32 1.75.9 2.43Q5.27 22.01 10 22q1.4 0 2.6-.24a7 7 0 0 1-.92-1.36q-.78.1-1.68.1c-2.74 0-4.7-.74-5.96-2.21-.34-.4-.54-.93-.54-1.46v-.58c0-.41.34-.75.75-.75zM10 2a5 5 0 1 1 0 10 5 5 0 0 1 0-10m0 1.5a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7m13 14a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0m-4.65-2.85a.5.5 0 0 0-.7.7L19.29 17H15a.5.5 0 1 0 0 1h4.3l-1.65 1.65a.5.5 0 0 0 .7.7l2.5-2.5a.5.5 0 0 0 .15-.34v-.01a.5.5 0 0 0-.15-.36z"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function PersonArrowRightIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
