// PersonMoneyIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M10 2a4 4 0 1 0 0 8 4 4 0 0 0 0-8M7 6a3 3 0 1 1 6 0 3 3 0 0 1-6 0m-2 5a2 2 0 0 0-2 2c0 1.7.83 2.97 2.13 3.8A8.5 8.5 0 0 0 9 17.96v-1a7.4 7.4 0 0 1-3.33-1A3.4 3.4 0 0 1 4 13a1 1 0 0 1 1-1h11.73A2 2 0 0 0 15 11zm14 3.5v3c0 .83-.67 1.5-1.5 1.5h-6a1.5 1.5 0 0 1-1.5-1.5v-3c0-.83.67-1.5 1.5-1.5h6c.83 0 1.5.67 1.5 1.5m-1 3v-1c-.83 0-1.5.67-1.5 1.5h1c0-.28.22-.5.5-.5m0-3a.5.5 0 0 1-.5-.5h-1c0 .83.67 1.5 1.5 1.5zm-6.5-.5a.5.5 0 0 1-.5.5v1c.83 0 1.5-.67 1.5-1.5zm-.5 3.5c.28 0 .5.22.5.5h1c0-.83-.67-1.5-1.5-1.5zm3.5-3a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3"/></>),
  24: (<><path d="M17.75 14c.78 0 1.47.4 1.87 1H13.5q-.86.02-1.5.5H6.25a.75.75 0 0 0-.75.75v.58c0 .53.2 1.05.54 1.46Q7.68 20.2 11 20.47v1.03q0 .24.04.47-4.02-.25-6.14-2.7a3.8 3.8 0 0 1-.9-2.44v-.58C4 15 5.01 14 6.25 14zM12 2a5 5 0 1 1 0 10 5 5 0 0 1 0-10m0 1.5a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7m0 14c0-.83.67-1.5 1.5-1.5h8c.83 0 1.5.67 1.5 1.5v4c0 .83-.67 1.5-1.5 1.5h-8a1.5 1.5 0 0 1-1.5-1.5zm10 .5a1 1 0 0 1-1-1h-1c0 1.1.9 2 2 2zm0 2a2 2 0 0 0-2 2h1a1 1 0 0 1 1-1zm-8-3a1 1 0 0 1-1 1v1a2 2 0 0 0 2-2zm1 5a2 2 0 0 0-2-2v1a1 1 0 0 1 1 1zm4.25-2.5a1.75 1.75 0 1 0-3.5 0 1.75 1.75 0 0 0 3.5 0"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function PersonMoneyIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
