// PersonAvailableIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M4 4.5a2.5 2.5 0 1 1 4.89.74 5.5 5.5 0 0 0-2.62 1.75A2.5 2.5 0 0 1 4 4.5M6.5 3a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3m4 12a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9m2.35-6.35c.2.2.2.5 0 .7l-3 3a.5.5 0 0 1-.7 0l-1-1a.5.5 0 0 1 .7-.7l.65.64 2.65-2.64c.2-.2.5-.2.7 0M5.6 8H3.5C2.67 8 2 8.95 2 9.75V10c0 1.73 1.55 3.64 4.22 3.95a6 6 0 0 1-.72-1.16C3.82 12.3 3 10.98 3 10v-.25c0-.14.07-.36.22-.55.15-.18.26-.2.28-.2h1.7q.16-.52.4-1"/></>),
  20: (<><path d="M5 6a4 4 0 1 1 8 0 4 4 0 0 1-8 0m4-3a3 3 0 1 0 0 6 3 3 0 0 0 0-6M2 13a2 2 0 0 1 2-2h6.26q-.39.46-.66 1H4a1 1 0 0 0-1 1c0 1.3.62 2.28 1.67 2.95A8 8 0 0 0 9 17l.6-.01q.25.51.61.95Q9.61 18 9 18a9 9 0 0 1-4.87-1.2A4.4 4.4 0 0 1 2 13m17 1.5a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0m-2.15-1.85a.5.5 0 0 0-.7 0l-2.65 2.64-.65-.64a.5.5 0 0 0-.7.7l1 1c.2.2.5.2.7 0l3-3a.5.5 0 0 0 0-.7"/></>),
  24: (<><path d="M17.5 12a5.5 5.5 0 1 1 0 11 5.5 5.5 0 0 1 0-11m-2.65 5.15a.5.5 0 1 0-.7.7l2 2c.2.2.5.2.7 0l4-4a.5.5 0 1 0-.7-.7l-3.65 3.64zM12.02 14q-.45.7-.7 1.5H4.24a.75.75 0 0 0-.75.75v.58c0 .53.2 1.05.54 1.46C5.3 19.76 7.26 20.5 10 20.5q.9 0 1.68-.1.37.74.91 1.36Q11.4 22 10 22q-4.74.01-7.1-2.74a3.8 3.8 0 0 1-.9-2.43v-.58C2 15 3.01 14 4.25 14zM10 2a5 5 0 1 1 0 10 5 5 0 0 1 0-10m0 1.5a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function PersonAvailableIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
