// PhoneKeyIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M7 2a2 2 0 0 0-2 2v12c0 1.1.9 2 2 2h2v-1H7a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1h6a1 1 0 0 1 1 1v5.54a4 4 0 0 1 1-.4V4a2 2 0 0 0-2-2zm3.38 13 .91-.9A.5.5 0 0 0 11 14H9a.5.5 0 0 0 0 1zm.12 4a.5.5 0 0 1-.35-.15.5.5 0 0 1-.15-.35V17q0-.2.15-.35l2.94-2.94a4 4 0 0 1-.09-.77q0-.6.24-1.14a3 3 0 0 1 1.61-1.57q.54-.21 1.15-.23a3 3 0 0 1 2.13.88A3 3 0 0 1 15 15.83v.69a1 1 0 0 1-.08.24 1 1 0 0 1-.15.17.5.5 0 0 1-.27.07H14q0 .36-.02.56a.5.5 0 0 1-.11.3.5.5 0 0 1-.3.12L13 18v.27q0 .13-.02.25l-.06.24a.4.4 0 0 1-.15.17 1 1 0 0 1-.27.07zm7-6.75q0-.31-.22-.53a.7.7 0 0 0-.53-.22q-.31 0-.53.22a.7.7 0 0 0-.22.53q0 .31.22.53.21.22.53.22.31 0 .53-.22a.7.7 0 0 0 .22-.53"/></>),
  24: (<><path d="M15.75 2C16.99 2 18 3 18 4.25v7q-.85.3-1.5.9v-7.9a.75.75 0 0 0-.75-.75h-7.5a.75.75 0 0 0-.75.75v15.5c0 .41.34.75.75.75h2.78q-.03.15-.03.31V22H8.25C7.01 22 6 21 6 19.75V4.25C6 3.01 7 2 8.25 2zm-2.5 15.5q.15 0 .28.05L12.08 19h-1.33a.75.75 0 0 1 0-1.5zM19.5 19a3.5 3.5 0 1 0-3.38-2.59l-.15.12-3.75 3.75a.8.8 0 0 0-.22.53v1.44c0 .41.34.75.75.75h1.75a.5.5 0 0 0 .5-.5V22h1a.5.5 0 0 0 .5-.5v-1h1a.5.5 0 0 0 .5-.5v-1zm1.5-4a1 1 0 1 1-2 0 1 1 0 0 1 2 0"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function PhoneKeyIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
