// PhoneMultipleIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  24: '0 0 24 24',
};
const C = {
  24: (<><path d="M9.75 15.5a.75.75 0 0 0 0 1.5h2.5a.75.75 0 0 0 0-1.5zM8.25 2C7.01 2 6 3 6 4.25v13c0 1.24 1 2.25 2.25 2.25h5.5c1.24 0 2.25-1 2.25-2.25v-13C16 3.01 15 2 13.75 2zM7.5 4.25c0-.41.34-.75.75-.75h5.5c.41 0 .75.34.75.75v13c0 .41-.34.75-.75.75h-5.5a.75.75 0 0 1-.75-.75zM10.75 22c-.98 0-1.81-.63-2.12-1.5h5.62A2.75 2.75 0 0 0 17 17.75V4.63c.87.3 1.5 1.14 1.5 2.12v11c0 2.35-1.9 4.25-4.25 4.25z"/></>),
};
const SIZES = [24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function PhoneMultipleIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
