// PositionBackwardIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M4.5 2A2.5 2.5 0 0 0 2 4.5v6A2.5 2.5 0 0 0 4.5 13H6v-1.7l-.7.7h-.8a2 2 0 0 1-.65-.15L6 9.71V9.5q.01-.86.38-1.59l-3.23 3.24A2 2 0 0 1 3 10.5v-.94L9.56 3h.94q.35 0 .65.15L7.9 6.38A3.5 3.5 0 0 1 9.5 6h.2l2.15-2.15q.15.3.15.65v.8l-.7.7H13V4.5A2.5 2.5 0 0 0 10.5 2zM3 4.5C3 3.67 3.67 3 4.5 3h.65L3 5.15zm0 2.06L6.56 3h1.59L3 8.15zM7 9.5A2.5 2.5 0 0 1 9.5 7h6A2.5 2.5 0 0 1 18 9.5v6a2.5 2.5 0 0 1-2.5 2.5h-6A2.5 2.5 0 0 1 7 15.5zM9.5 8C8.67 8 8 8.67 8 9.5v6c0 .83.67 1.5 1.5 1.5h6c.83 0 1.5-.67 1.5-1.5v-6c0-.83-.67-1.5-1.5-1.5z"/></>),
  24: (<><path d="M6.5 16.5H5.25A3.25 3.25 0 0 1 2 13.25v-8C2 3.45 3.46 2 5.25 2h8c1.8 0 3.25 1.46 3.25 3.25V6.5h-1.65l.15-.15v-1.1q0-.35-.13-.65l-1.9 1.9h-2.12l2.92-2.92a2 2 0 0 0-.52-.08h-1.28L3.5 11.97v1.28q0 .27.08.52l2.92-2.92v2.12l-1.9 1.9q.3.13.65.13h1.1l.15-.15zm3.35-13H7.97L3.5 7.97v1.88zm-4 0h-.6c-.97 0-1.75.78-1.75 1.75v.6zM22 18.75c0 1.8-1.46 3.25-3.25 3.25h-8a3.25 3.25 0 0 1-3.25-3.25v-8c0-1.8 1.46-3.25 3.25-3.25h8c1.8 0 3.25 1.46 3.25 3.25zm-3.25 1.75c.97 0 1.75-.78 1.75-1.75v-8c0-.97-.78-1.75-1.75-1.75h-8C9.78 9 9 9.78 9 10.75v8c0 .97.78 1.75 1.75 1.75z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function PositionBackwardIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
