// PresenceOofIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M8.2 6.2a1 1 0 1 0-1.4-1.4L4.3 7.3a1 1 0 0 0 0 1.4l2.5 2.5a1 1 0 0 0 1.4-1.4L7.42 9H11a1 1 0 1 0 0-2H7.41zM8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0M2 8a6 6 0 1 1 12 0A6 6 0 0 1 2 8"/></>),
  20: (<><path d="M10.7 7.7A1 1 0 1 0 9.28 6.3l-3 3a1 1 0 0 0 0 1.41l3 3a1 1 0 1 0 1.42-1.41l-1.3-1.3H13a1 1 0 1 0 0-2H9.4zM10 0a10 10 0 1 0 0 20 10 10 0 0 0 0-20M2 10a8 8 0 1 1 16 0 8 8 0 0 1-16 0"/></>),
  24: (<><path d="M12.56 9.06a1.5 1.5 0 0 0-2.12-2.12l-4 4a1.5 1.5 0 0 0 0 2.12l4 4a1.5 1.5 0 0 0 2.12-2.12l-1.44-1.44h5.38a1.5 1.5 0 1 0 0-3h-5.38zM12 0a12 12 0 1 0 0 24 12 12 0 0 0 0-24M3 12a9 9 0 1 1 18 0 9 9 0 0 1-18 0"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function PresenceOofIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
