// PresenceAwayIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M8.5 7.52V4.5a1 1 0 1 0-2 0V8c0 .3.14.6.38.78l2.5 2a1 1 0 1 0 1.24-1.56zM8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0M2 8a6 6 0 1 1 12 0A6 6 0 0 1 2 8"/></>),
  20: (<><path d="M10 9.59V6a1 1 0 1 0-2 0V10q0 .42.3.7l3 3a1 1 0 1 0 1.4-1.4zm-10 .4a10 10 0 1 1 20 0 10 10 0 0 1-20 0M10 2a8 8 0 1 0 0 16 8 8 0 0 0 0-16"/></>),
  24: (<><path d="M13 11.31V6.5a1.5 1.5 0 0 0-3 0V12c0 .44.2.85.52 1.14l3.5 3a1.5 1.5 0 0 0 1.96-2.28zM0 12a12 12 0 1 1 24 0 12 12 0 0 1-24 0m12-9a9 9 0 1 0 0 18 9 9 0 0 0 0-18"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function PresenceAwayIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
