// PreviousFrameIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M15.5 3a.5.5 0 0 0-.5.5v13a.5.5 0 0 0 1 0v-13a.5.5 0 0 0-.5-.5m-5.45.21c.83-.55 1.95.04 1.95 1.04v11.5c0 1-1.12 1.6-1.95 1.04l-8.5-5.8a1.25 1.25 0 0 1 0-2.07zM11 4.25c0-.2-.22-.32-.39-.2l-8.5 5.7a.25.25 0 0 0 0 .42l8.5 5.79c.17.11.39 0 .39-.2z"/></>),
  24: (<><path d="M18.5 3.75a.75.75 0 0 1 1.5 0v16.5a.75.75 0 0 1-1.5 0zm-6.24-.44c1.16-.8 2.74.04 2.74 1.44v14.5a1.75 1.75 0 0 1-2.75 1.43l-10.5-7.3c-1-.7-1-2.19.01-2.88zm1.24 1.44c0-.2-.22-.32-.4-.2L2.62 11.74a.25.25 0 0 0 0 .41l10.5 7.3c.16.12.39 0 .39-.2z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function PreviousFrameIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
