// ProductionCheckmarkIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M5 3.5c0-.28.22-.5.5-.5h3c.28 0 .5.22.5.5v3a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5zm6.5-.5a.5.5 0 0 0-.5.5v3c0 .28.22.5.5.5h3a.5.5 0 0 0 .5-.5v-3a.5.5 0 0 0-.5-.5zm.5 3V4h2v2zM2 12a4 4 0 0 1 4-4h8a4 4 0 0 1 3.33 1.78A5.5 5.5 0 0 0 14 9H6a3 3 0 1 0 0 6h3.02q.05.51.19 1H6a4 4 0 0 1-4-4m8-1 .23.03a6 6 0 0 0-.93 1.68A1 1 0 0 1 10 11m-4 2a1 1 0 1 0 0-2 1 1 0 0 0 0 2m13 1.5a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0m-2.85-1.85-2.65 2.64-.65-.64a.5.5 0 0 0-.7.7l1 1c.2.2.5.2.7 0l3-3a.5.5 0 0 0-.7-.7"/></>),
  24: (<><path d="M6.25 3.5c-.97 0-1.75.78-1.75 1.75v2.5c0 .97.78 1.75 1.75 1.75h2.5c.97 0 1.75-.78 1.75-1.75v-2.5c0-.97-.78-1.75-1.75-1.75zm7.25 1.75c0-.97.78-1.75 1.75-1.75h2.5c.97 0 1.75.78 1.75 1.75v2.5c0 .97-.78 1.75-1.75 1.75h-2.5c-.97 0-1.75-.78-1.75-1.75zM15.25 5a.25.25 0 0 0-.25.25v2.5c0 .14.11.25.25.25h2.5c.14 0 .25-.11.25-.25v-2.5a.25.25 0 0 0-.25-.25zM7 17.5a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3M6.5 13h6.31A7 7 0 0 1 15 11.5H6.5a4.5 4.5 0 1 0 0 9h5.23a7 7 0 0 1-.56-1.5H6.5a3 3 0 1 1 0-6m4 3c0 .45.2.85.51 1.13q.09-1.42.7-2.6A1.5 1.5 0 0 0 10.5 16M23 17.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0m-2.15-2.35a.5.5 0 0 0-.7 0l-3.65 3.64-1.65-1.64a.5.5 0 0 0-.7.7l2 2c.2.2.5.2.7 0l4-4a.5.5 0 0 0 0-.7"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ProductionCheckmarkIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
