// ProhibitedMultipleIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
};
const C = {
  16: (<><path d="M3.46 3.46a5 5 0 0 1 6.7-.33l-7.03 7.03a5 5 0 0 1 .33-6.7m.38 7.41 7.03-7.03a5 5 0 0 1-7.03 7.03m7.4-8.11a6 6 0 1 0-8.48 8.48 6 6 0 0 0 8.48-8.48M14 7q-.02 1.84-.86 3.36a5 5 0 0 1-2.78 2.78 7 7 0 0 1-4.44.78q1.18.57 2.58.58a6 6 0 0 0 5.42-8.58Q14 6.45 14 7"/></>),
  20: (<><path d="M4.76 4.76a6 6 0 0 1 8.11-.34l-8.45 8.45a6 6 0 0 1 .34-8.11m.37 8.82 8.45-8.45a6 6 0 0 1-8.45 8.45m8.82-9.53a7 7 0 1 0-9.9 9.9 7 7 0 0 0 9.9-9.9M17 9c0 1.37-.34 2.66-.95 3.79a6 6 0 0 1-3.26 3.26 8 8 0 0 1-5.17.83q1.33.61 2.88.62a7 7 0 0 0 6.38-9.88Q17 8.29 17 9"/></>),
  24: (<><path d="M5.7 5.7a7.5 7.5 0 0 1 10.05-.5L5.19 15.74A7.5 7.5 0 0 1 5.7 5.7m.55 11.1L16.81 6.26A7.5 7.5 0 0 1 6.25 16.81M17.36 4.65A9 9 0 1 0 4.64 17.36 9 9 0 0 0 17.36 4.64M21 11a10 10 0 0 1-12.5 9.68A9 9 0 0 0 20.69 8.5q.3 1.21.31 2.51"/></>),
  28: (<><path d="M6.28 6.28a9.5 9.5 0 0 1 12.89-.5L5.77 19.16a9.5 9.5 0 0 1 .51-12.89m.55 13.95 13.4-13.4a9.5 9.5 0 0 1-13.4 13.4m13.95-15A11 11 0 1 0 5.22 20.77 11 11 0 0 0 20.78 5.22M25 13A12 12 0 0 1 9.77 24.56a11 11 0 0 0 14.8-14.8q.43 1.56.43 3.24"/></>),
};
const SIZES = [16, 20, 24, 28];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ProhibitedMultipleIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
