// ReceiptPlayIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M4 5c0-1.1.9-2 2-2h7a2 2 0 0 1 2 2v7h3v2a3 3 0 0 1-3 3h-4.6q.25-.48.4-1H14V5a1 1 0 0 0-1-1H6a1 1 0 0 0-1 1v4.02q-.51.05-1 .19zm7.5 5H8.66a6 6 0 0 0-1.58-.77A.5.5 0 0 1 7.5 9h4a.5.5 0 0 1 0 1m3.5 6a2 2 0 0 0 2-2v-1h-2zM7 6.5c0-.28.22-.5.5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5m3 8a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0M4 16c0 .38.42.62.76.42l2.5-1.5a.5.5 0 0 0 0-.85l-2.5-1.5A.5.5 0 0 0 4 13z"/></>),
  24: (<><path d="M4 5.25C4 4.01 5 3 6.25 3h9.5C16.99 3 18 4 18 5.25V14h4v3.75c0 1.8-1.46 3.25-3.25 3.25h-6.77q.45-.7.7-1.5h3.82V5.25a.75.75 0 0 0-.75-.75h-9.5a.75.75 0 0 0-.75.75v5.83q-.79.12-1.5.42zm9.75 7.25h-3.1a6.5 6.5 0 0 0-2.83-1.37 1 1 0 0 1 .43-.13h5.5a.75.75 0 0 1 0 1.5m4.25 7h.75c.97 0 1.75-.78 1.75-1.75V15.5H18zM8.25 7a.75.75 0 0 0 0 1.5h5.5a.75.75 0 0 0 0-1.5zM12 17.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0m-7 2c0 .4.44.64.78.42l3-2a.5.5 0 0 0 0-.84l-3-2a.5.5 0 0 0-.78.42z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ReceiptPlayIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
