// ReplayIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
};
const C = {
  16: (<><path d="M2.5 3.67V2.5a.5.5 0 0 0-1 0v3c0 .28.22.5.5.5h2.5a.5.5 0 0 0 0-1H2.8a6 6 0 1 1-.78 3.5.53.53 0 0 0-.52-.5c-.28 0-.5.22-.48.5A7 7 0 1 0 2.5 3.67M6 6a1 1 0 0 1 1.5-.87l3.5 2a1 1 0 0 1 0 1.74l-3.5 2A1 1 0 0 1 6 10zm4.5 2L7 6v4z"/></>),
  20: (<><path d="M4.25 6a7 7 0 1 1-1.24 3.57A.53.53 0 0 0 2.5 9a.47.47 0 0 0-.48.44L2 10a8 8 0 1 0 1.5-4.66V3.5a.5.5 0 0 0-1 0v3c0 .28.22.5.5.5h3a.5.5 0 0 0 0-1zM8 7.75a1 1 0 0 1 1.5-.87l3.99 2.25a1 1 0 0 1 0 1.74l-4 2.25A1 1 0 0 1 8 12.25zM13 10 9 7.75v4.5z"/></>),
  24: (<><path d="M12 3.5a8.5 8.5 0 0 0-6.48 3h1.73a.75.75 0 0 1 0 1.5h-3.5A.75.75 0 0 1 3 7.25v-3.5a.75.75 0 0 1 1.5 0v1.64a10 10 0 1 1-2.4 5.2.7.7 0 0 1 .7-.59c.48 0 .83.45.77.92q-.07.52-.07 1.08A8.5 8.5 0 1 0 12 3.5m-.77 4.69A1.5 1.5 0 0 0 9 9.5v5a1.5 1.5 0 0 0 2.23 1.31l4.5-2.5a1.5 1.5 0 0 0 0-2.62zM10.5 9.5 15 12l-4.5 2.5z"/></>),
  28: (<><path d="M14 3.5c-3.34 0-6.32 1.56-8.25 4h2.5a.75.75 0 0 1 0 1.5h-4a.75.75 0 0 1-.75-.75v-4a.75.75 0 0 1 1.5 0v1.81a12 12 0 1 1-2.92 6.56.7.7 0 0 1 .71-.62.8.8 0 0 1 .77.89q-.06.54-.06 1.11A10.5 10.5 0 1 0 14 3.5m-.74 5.7A1.5 1.5 0 0 0 11 10.5v7a1.5 1.5 0 0 0 2.26 1.29l6-3.5c.99-.57.99-2 0-2.59zm-.76 1.3 6 3.5-6 3.5z"/></>),
};
const SIZES = [16, 20, 24, 28];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ReplayIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
