// RotateRightIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M7.61 12c.3 0 .54-.23.54-.52a.53.53 0 0 0-.54-.52h-.35c-1.77 0-3.2-1.08-3.2-2.42 0-1.3 1.35-2.36 3.04-2.42h5.08L10.96 7.3c-.2.2-.2.53 0 .73.2.18.49.2.7.05l.06-.05 2.12-2.08c.21-.2.21-.53 0-.73l-2.12-2.08-.06-.05a.54.54 0 0 0-.7.05c-.2.2-.2.53 0 .74l1.22 1.19H7.26C4.9 5.08 3 6.63 3 8.54S4.9 12 7.26 12zM16 10.41V16H5.82zm.2 6.59c.44 0 .8-.34.8-.75V9.38c0-.21-.18-.38-.4-.38a.4.4 0 0 0-.2.05L3.2 16.3a.37.37 0 0 0-.15.51q.12.19.35.19z"/></>),
  24: (<><path d="M8.98 5h-.26a7 7 0 0 0-3.13.89A4.8 4.8 0 0 0 3 10c0 1.7 1.03 3.22 2.6 4.12.96.55 2.14.88 3.4.88h.5a.75.75 0 0 0 0-1.5H9a5.4 5.4 0 0 1-2.59-.64C5.26 12.23 4.5 11.18 4.5 10s.76-2.23 1.91-2.86q1.04-.57 2.37-.64h7.16l-1.72 1.72a.75.75 0 0 0 .98 1.13l.08-.07 3-3 .02-.02a.75.75 0 0 0-.02-1.04l-3-3-.08-.07a.75.75 0 0 0-.98 1.13L15.94 5H8.98M3.61 20.07a.5.5 0 0 0 .25.93H20a1 1 0 0 0 1-1v-9.13a.5.5 0 0 0-.75-.44zm3.97-.57 11.92-6.9v6.9z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function RotateRightIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
