// RotateLeftIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M12.39 12a.53.53 0 0 1-.54-.52c0-.29.24-.52.54-.52h.35c1.77 0 3.2-1.08 3.2-2.42 0-1.3-1.35-2.36-3.04-2.42H7.82L9.04 7.3c.2.2.2.53 0 .73a.54.54 0 0 1-.7.05l-.06-.05-2.12-2.08a.5.5 0 0 1 0-.73l2.12-2.08.06-.05c.21-.15.5-.13.7.05.2.2.2.53 0 .74L7.82 5.08h4.92C15.1 5.08 17 6.63 17 8.54S15.1 12 12.74 12zM4 10.41V16h10.18zM3.8 17a.77.77 0 0 1-.8-.75V9.38c0-.21.18-.38.4-.38q.1 0 .2.05l13.2 7.25c.2.1.26.33.15.51a.4.4 0 0 1-.35.19z"/></>),
  24: (<><path d="M15.02 5h.26c1.16.05 2.24.37 3.13.89C19.98 6.79 21 8.29 21 10c0 1.7-1.03 3.22-2.6 4.12-.96.55-2.14.88-3.4.88h-.5a.75.75 0 1 1 0-1.5h.5a5.4 5.4 0 0 0 2.59-.64c1.15-.63 1.91-1.68 1.91-2.86s-.76-2.23-1.91-2.86a5.4 5.4 0 0 0-2.37-.64H8.06l1.72 1.72a.75.75 0 0 1-.98 1.13l-.08-.07-3-3-.02-.02a.75.75 0 0 1 .02-1.04l3-3 .08-.07a.75.75 0 0 1 .98 1.13L8.06 5h6.96m5.37 15.07a.5.5 0 0 1-.25.93H4a1 1 0 0 1-1-1v-9.13a.5.5 0 0 1 .75-.44zm-3.97-.57L4.5 12.6v6.9z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function RotateLeftIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
