// SaveImageIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
};
const C = {
  20: (<><path d="M17 6.13v2.9L16.5 9H16V6.13a1 1 0 0 0-.29-.72L13.6 3.3A1 1 0 0 0 13 3V5.5a1.5 1.5 0 0 1-.44 1.06q-.21.2-.48.32T11.5 7h-4a1.5 1.5 0 0 1-1.05-.44 2 2 0 0 1-.33-.48A1.3 1.3 0 0 1 6 5.5V3H5a1 1 0 0 0-.7.29q-.15.15-.22.32A1 1 0 0 0 4 4v10q0 .2.08.4.08.16.2.31.14.15.32.21.2.08.4.08v-4.5a1.5 1.5 0 0 1 .44-1.05q.21-.21.48-.33Q6.2 9 6.5 9h6c-.96 0-1.82.38-2.45 1H6.5a.5.5 0 0 0-.5.5V15h3v1H5q-.4 0-.76-.16a2 2 0 0 1-.64-.42 2 2 0 0 1-.6-1.38V4q0-.4.16-.76.15-.36.42-.64A2 2 0 0 1 4.96 2h7.92q.4 0 .76.15.38.15.65.44L16.4 4.7q.29.28.43.65.16.36.16.77M7 3v2.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5V3zm3 9.5a2.5 2.5 0 0 1 2.5-2.5h4a2.5 2.5 0 0 1 2.5 2.5v4q-.01.77-.41 1.38l-3.03-3.03a1.5 1.5 0 0 0-2.12 0l-3.03 3.03q-.4-.6-.41-1.38zm7 .25a.75.75 0 1 0-1.5 0 .75.75 0 0 0 1.5 0m-5.88 5.84q.6.4 1.38.41h4q.77-.01 1.38-.41l-3.03-3.03a.5.5 0 0 0-.7 0z"/></>),
};
const SIZES = [20];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function SaveImageIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
