// ScanTypeOffIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M2.41 3.12q-.4.6-.41 1.38v2a.5.5 0 0 0 1 0v-2q0-.35.15-.65L6 6.71v.79a.5.5 0 0 0 .97.18L9.5 10.2V13H9a.5.5 0 0 0 0 1h2a.5.5 0 0 0 0-1h-.5v-1.8l5.65 5.65q-.3.15-.65.15h-2a.5.5 0 0 0 0 1h2q.77-.01 1.38-.41l.27.26a.5.5 0 0 0 .7-.7l-15-15a.5.5 0 1 0-.7.7zM8.12 6l1 1h.38v.38l1 1V7H13v.5a.5.5 0 0 0 1 0v-1a.5.5 0 0 0-.5-.5zM18 15.5q0 .18-.02.35l-.98-.97V13.5a.5.5 0 0 1 1 0zM4.15 2.02l.97.98H6.5a.5.5 0 0 0 0-1h-2q-.18 0-.35.02M4.5 17A1.5 1.5 0 0 1 3 15.5v-2a.5.5 0 0 0-1 0v2A2.5 2.5 0 0 0 4.5 18h2a.5.5 0 0 0 0-1zM17 4.5c0-.83-.67-1.5-1.5-1.5h-2a.5.5 0 0 1 0-1h2A2.5 2.5 0 0 1 18 4.5v2a.5.5 0 0 1-1 0z"/></>),
  24: (<><path d="M2.48 3.54Q2.02 4.3 2 5.25v3a.75.75 0 0 0 1.5 0v-3q0-.3.1-.59L7 8.06V9a.75.75 0 0 0 1.37.43l2.88 2.88v3.19h-1.5a.75.75 0 0 0 0 1.5h4.5a.75.75 0 0 0 .72-.97l4.37 4.37q-.28.1-.59.1h-3a.75.75 0 0 0 0 1.5h3q.96-.01 1.7-.48l.27.26a.75.75 0 0 0 1.06-1.06L3.28 2.22a.75.75 0 1 0-1.06 1.06zm12 12-.23-.04h-1.5v-1.69zM10.17 7l2.57 2.57V8.5h2.75V9A.75.75 0 0 0 17 9V7.75a.75.75 0 0 0-.75-.75zM20.5 17.32l1.5 1.5v-3.07a.75.75 0 0 0-1.5 0zM5.18 2l1.5 1.5h1.57a.75.75 0 0 0 0-1.5H5.18m.07 18.5c-.97 0-1.75-.78-1.75-1.75v-3a.75.75 0 0 0-1.5 0v3C2 20.55 3.46 22 5.25 22h3a.75.75 0 0 0 0-1.5zM20.5 5.25c0-.97-.78-1.75-1.75-1.75h-3a.75.75 0 0 1 0-1.5h3C20.55 2 22 3.46 22 5.25v3a.75.75 0 0 1-1.5 0z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ScanTypeOffIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
