// ScanIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M4.68 4.26a5 5 0 0 1 3.88-1.23L6.29 6.96 6.27 7zm-.7.77L6.27 9H3.1a5 5 0 0 1 .88-3.97M8 6l1.58-2.74a5 5 0 0 1 3 2.74zm-.87 1.5.02-.02A1 1 0 0 1 8.87 8.5l-.02.02A1 1 0 0 1 7.13 7.5m2.6-.5h3.17a5 5 0 0 1-.88 3.97zm0 2 1.59 2.74a5 5 0 0 1-3.88 1.23l2.27-3.93zM8 10l-1.58 2.74a5 5 0 0 1-3-2.74zm0-8a6 6 0 1 0 0 12A6 6 0 0 0 8 2m1.73 5Z"/></>),
  20: (<><path d="M4.91 5.19a7 7 0 0 1 5.65-2.17L7.4 8.5q-.16.26-.25.56zm-.67.83 3.12 5.4a3 3 0 0 0 .4.58H3.3a7 7 0 0 1 .95-5.98M8.27 11l-.04-.06A2 2 0 0 1 11.73 9l.04.06A2 2 0 0 1 8.27 11m1.12-3.94 2.23-3.87c2.08.5 3.8 1.92 4.7 3.81H10q-.32 0-.61.06m2.85.94h4.47a7 7 0 0 1-.95 5.98l-3.12-5.4q-.16-.3-.4-.58m.61 2.94 2.24 3.87a7 7 0 0 1-5.65 2.17l3.16-5.48q.15-.27.25-.56m-2.24 2L8.38 16.8A7 7 0 0 1 3.68 13H10q.32 0 .61-.06M10 2a8 8 0 1 0 0 16 8 8 0 0 0 0-16"/></>),
  24: (<><path d="M12 2a10 10 0 1 1 0 20 10 10 0 0 1 0-20m3.25 12.33-.04.07-.06.1-4.76 5.85a8.5 8.5 0 0 0 7.26-2l-2.08-4.54q-.14.27-.32.52M4.49 16a8.5 8.5 0 0 0 4.34 3.9L11.99 16h-.19l-.13-.01zM20.13 9.5h-5l.3.41.05.1.04.07q.13.24.22.5l3.02 6.57a8.5 8.5 0 0 0 1.37-7.65M3.5 12q0 1.3.37 2.49h5l-.23-.32-.14-.23-3.61-6.6A8.5 8.5 0 0 0 3.5 12m6.52-1.53-.04.08-.08.1q-.39.58-.4 1.35c0 1.3.98 2.36 2.24 2.49h.52a2.5 2.5 0 0 0-.03-4.98h-.43a2.5 2.5 0 0 0-1.78.96M12 3.5c-2.4 0-4.55.99-6.1 2.58l2.4 4.38a4 4 0 0 1 .49-.85l3.9-6.08zm-.4 4.52a4 4 0 0 1 .7 0h7.2A8.5 8.5 0 0 0 14.6 3.9l-.3-.09z"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ScanIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
