// SelectObjectSkewEditIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M16.49 6h.01a1.5 1.5 0 1 0-1.41-2l-.01.02a1.5 1.5 0 0 0 .47 1.64q.4.33.94.34M2 15.5a1.5 1.5 0 1 0 2.92-.48V15a1.5 1.5 0 0 0-1.4-1H3.5c-.83 0-1.5.67-1.5 1.5M7.49 6zc.65 0 1.2-.42 1.41-1l.01-.02a1.5 1.5 0 1 0-2.37.68q.4.33.94.34m-1.3.63-2.32 6.4q.52.08.94.34l2.32-6.4a3 3 0 0 1-.94-.34M14.05 5h-4.1a3 3 0 0 0 0-1h4.1a3 3 0 0 0 0 1m-.64 6.53 1.67-1.67 1.05-2.89a3 3 0 0 1-.94-.34zM5.95 16h3.52q.17-.54.52-1H5.95a3 3 0 0 1 0 1m5.03-.62 4.83-4.83a1.87 1.87 0 1 1 2.64 2.64l-4.83 4.83a2 2 0 0 1-1.02.58l-1.5.37a.9.9 0 0 1-1.07-1.07l.37-1.5q.16-.6.58-1.02"/></>),
  24: (<><path d="M18.88 6.66a2 2 0 0 0 1.33.33 2 2 0 1 0-1.33-.33M2 19a2 2 0 1 0 4 0 2 2 0 0 0-4 0M6.88 6.66a2 2 0 0 0 3-.97 2 2 0 1 0-3 .97M4.08 16l2.4-8.41q.65.39 1.44.4l-2.4 8.42q-.65-.39-1.44-.4M17.09 5.75h-6.18a3 3 0 0 0 0-1.5h6.18a3 3 0 0 0 0 1.5m-5.57 13.83q.18-.74.64-1.33H6.9a3 3 0 0 1 0 1.5h4.57zM19.92 8l-1 3.54a3 3 0 0 0-.53.42l-1.62 1.63 1.71-6q.65.39 1.44.4m-.82 4.67-5.9 5.9q-.54.54-.7 1.25l-.47 1.83c-.2.8.53 1.52 1.32 1.32l1.83-.46q.71-.18 1.25-.7l5.9-5.9a2.29 2.29 0 0 0-3.23-3.24"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function SelectObjectSkewEditIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
