// SelectAllOffIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M4.5 2A2.5 2.5 0 0 0 2 4.5v5A2.5 2.5 0 0 0 4.5 12h5A2.5 2.5 0 0 0 12 9.5v-5A2.5 2.5 0 0 0 9.5 2zM3 4.5C3 3.67 3.67 3 4.5 3h5c.83 0 1.5.67 1.5 1.5v5c0 .83-.67 1.5-1.5 1.5h-5A1.5 1.5 0 0 1 3 9.5zM5 13c.46.6 1.18 1 2 1h2.5A4.5 4.5 0 0 0 14 9.5V6c0-.82-.4-1.54-1-2v5.5A3.5 3.5 0 0 1 9.5 13z"/></>),
  20: (<><path d="M6 3a3 3 0 0 0-3 3v6a3 3 0 0 0 3 3h6a3 3 0 0 0 3-3V6a3 3 0 0 0-3-3zM4 6c0-1.1.9-2 2-2h6a2 2 0 0 1 2 2v6a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2zm3.99 11a3 3 0 0 1-2.24-1h6.74a3.5 3.5 0 0 0 3.5-3.5V5.77A3 3 0 0 1 17 8v4.5a4.5 4.5 0 0 1-4.5 4.5z"/></>),
  24: (<><path d="M6.25 3A3.25 3.25 0 0 0 3 6.25v9c0 1.8 1.46 3.25 3.25 3.25h9c1.8 0 3.25-1.46 3.25-3.25v-9c0-1.8-1.46-3.25-3.25-3.25zM4.5 6.25c0-.97.78-1.75 1.75-1.75h9c.97 0 1.75.78 1.75 1.75v9c0 .97-.78 1.75-1.75 1.75h-9c-.97 0-1.75-.78-1.75-1.75zM6.01 19.5c.58.9 1.59 1.5 2.74 1.5h7c2.9 0 5.25-2.35 5.25-5.25v-7c0-1.15-.6-2.16-1.5-2.74v9.74a3.75 3.75 0 0 1-3.75 3.75H6.02"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function SelectAllOffIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
