// SelectObjectSkewDismissIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M16.49 6h.01a1.5 1.5 0 1 0-1.41-2l-.01.02a1.5 1.5 0 0 0 .47 1.64q.4.33.94.34M2 15.5a1.5 1.5 0 1 0 2.92-.48V15a1.5 1.5 0 0 0-1.4-1H3.5c-.83 0-1.5.67-1.5 1.5M7.49 6zc.65 0 1.2-.42 1.41-1l.01-.02a1.5 1.5 0 1 0-2.37.68q.4.33.94.34m-1.3.63-2.32 6.4q.52.08.94.34l2.32-6.4a3 3 0 0 1-.94-.34M14.05 5h-4.1a3 3 0 0 0 0-1h4.1a3 3 0 0 0 0 1m.45 4q.45 0 .87.07l.76-2.1a3 3 0 0 1-.94-.34L14.33 9zm-5.48 6q.05.51.19 1H5.95a3 3 0 0 0 0-1zm9.98-.5a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0m-2.65-1.15a.5.5 0 0 0-.7-.7l-1.15 1.14-1.15-1.14a.5.5 0 0 0-.7.7l1.14 1.15-1.14 1.15a.5.5 0 0 0 .7.7l1.15-1.14 1.15 1.14a.5.5 0 0 0 .7-.7l-1.14-1.15z"/></>),
  24: (<><path d="M18.88 6.66a2 2 0 0 0 1.33.33 2 2 0 1 0-1.33-.33M2 19a2 2 0 1 0 4 0 2 2 0 0 0-4 0M6.88 6.66a2 2 0 0 0 3-.97 2 2 0 1 0-3 .97M4.08 16l2.4-8.41q.65.39 1.44.4l-2.4 8.42q-.65-.39-1.44-.4M17.09 5.75h-6.18a3 3 0 0 0 0-1.5h6.18a3 3 0 0 0 0 1.5m-5.69 14q-.27-.72-.36-1.5H6.91a3 3 0 0 1 0 1.5zM19.92 8l-.9 3.18A7 7 0 0 0 17.5 11l.97-3.41q.65.39 1.44.4M23 17.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0m-7.15-2.35a.5.5 0 0 0-.7.7l1.64 1.65-1.64 1.65a.5.5 0 0 0 .7.7l1.65-1.64 1.65 1.64a.5.5 0 0 0 .7-.7l-1.64-1.65 1.64-1.65a.5.5 0 0 0-.7-.7l-1.65 1.64z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function SelectObjectSkewDismissIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
