// SendClockIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
};
const C = {
  20: (<><path d="M2.18 1.11a.5.5 0 0 1 .54-.06l15 7.5a.5.5 0 1 1-.44.9l-14.01-7L4.88 8.5h6.62a.5.5 0 1 1 0 1H4.88l-1.61 6.06 6.1-3.06q-.23.62-.32 1.29l-6.33 3.16a.5.5 0 0 1-.7-.58L3.98 9 2.02 1.63a.5.5 0 0 1 .16-.52M19 14.5a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0M14.5 12a.5.5 0 0 0-.5.5v2c0 .28.22.5.5.5H16a.5.5 0 0 0 0-1h-1v-1.5a.5.5 0 0 0-.5-.5"/></>),
  24: (<><path d="M2.3 3.27 5.7 12l-3.4 8.73-.03.1a.75.75 0 0 0 1.06.84l7.68-3.84a7 7 0 0 1 .14-1.75L4.4 19.46l2.61-6.71h6.05q.6-.55 1.3-.94a.75.75 0 0 0-.72-.56H7l-2.6-6.71L17.32 11h.17c1.55 0 2.98.54 4.1 1.45a.75.75 0 0 0-.27-1.12l-18-9-.09-.04a.75.75 0 0 0-.94.98M23 17.5a5.5 5.5 0 1 0-11 0 5.5 5.5 0 0 0 11 0M17.5 14c.28 0 .5.22.5.5V17h2a.5.5 0 0 1 0 1h-2.5a.5.5 0 0 1-.5-.5v-3c0-.28.22-.5.5-.5"/></>),
  28: (<><path d="M20.5 14a6.5 6.5 0 1 1 0 13 6.5 6.5 0 0 1 0-13M2.04 4.08A1.25 1.25 0 0 1 3.8 2.62l21.5 10.25c.85.4.93 1.53.26 2.09a7.5 7.5 0 0 0-2.67-1.57L3.63 4.2l2.42 9.04h11.2q.34.01.55.25-1.16.46-2.12 1.25H6.05L3.63 23.8l9.47-4.51a8 8 0 0 0-.08 1.7l-9.23 4.4a1.25 1.25 0 0 1-1.75-1.45L4.7 14zM20.5 16.5a.5.5 0 0 0-.5.5v3.5c0 .28.22.5.5.5h3a.5.5 0 0 0 0-1H21v-3a.5.5 0 0 0-.5-.5"/></>),
};
const SIZES = [20, 24, 28];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function SendClockIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
