// ShareIosIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
  48: '0 0 48 48',
};
const C = {
  20: (<><path d="M10.35 2.15a.5.5 0 0 0-.7 0l-4.5 4.5a.5.5 0 1 0 .7.7L9.5 3.71v8.79a.5.5 0 0 0 1 0V3.7l3.65 3.65a.5.5 0 0 0 .7-.7zM4 9.5a.5.5 0 0 0-1 0V14a3 3 0 0 0 3 3h8a3 3 0 0 0 3-3V9.5a.5.5 0 0 0-1 0V14a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2z"/></>),
  24: (<><path d="M12.53 2.22a.75.75 0 0 0-1.06 0L6.22 7.47a.75.75 0 0 0 1.06 1.06l3.97-3.97v10.69a.75.75 0 0 0 1.5 0V4.56l3.97 3.97a.75.75 0 1 0 1.06-1.06zM3.75 11c.41 0 .75.34.75.75v6c0 .97.78 1.75 1.75 1.75h11.5c.97 0 1.75-.78 1.75-1.75v-6a.75.75 0 0 1 1.5 0v6c0 1.8-1.46 3.25-3.25 3.25H6.25A3.25 3.25 0 0 1 3 17.75v-6c0-.41.34-.75.75-.75"/></>),
  28: (<><path d="M14 2a.8.8 0 0 1 .53.22l6.75 6.75a.75.75 0 1 1-1.06 1.06l-5.47-5.47v13.69a.75.75 0 0 1-1.5 0V4.56l-5.47 5.47a.75.75 0 1 1-1.06-1.06l6.75-6.75A.8.8 0 0 1 14 2M4.5 13.75a.75.75 0 0 0-1.5 0v7.5A3.75 3.75 0 0 0 6.75 25h14.5A3.75 3.75 0 0 0 25 21.25v-7.5a.75.75 0 0 0-1.5 0v7.5c0 1.24-1 2.25-2.25 2.25H6.75c-1.24 0-2.25-1-2.25-2.25z"/></>),
  48: (<><path d="M23.12 4.37a1.25 1.25 0 0 1 1.76 0l11.5 11.5a1.25 1.25 0 0 1-1.76 1.76l-9.37-9.36v22.48a1.25 1.25 0 1 1-2.5 0V8.27l-9.37 9.36a1.25 1.25 0 0 1-1.76-1.76zM7.25 22c.69 0 1.25.56 1.25 1.25v12.5a3.75 3.75 0 0 0 3.75 3.75h23.5a3.75 3.75 0 0 0 3.75-3.75v-12.5a1.25 1.25 0 1 1 2.5 0v12.5C42 39.2 39.2 42 35.75 42h-23.5A6.25 6.25 0 0 1 6 35.75v-12.5c0-.69.56-1.25 1.25-1.25"/></>),
};
const SIZES = [20, 24, 28, 48];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ShareIosIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
