// ShieldBadgeIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M2 7c0-1.1.9-2 2-2h11a2 2 0 0 1 2 2v1.57a2 2 0 0 1-1-.82V7a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v4a1 1 0 0 0 1 1h6v1H4a2 2 0 0 1-2-2zm12.53 1.83a.5.5 0 0 1 .95.02q0 .04.06.1.09.16.39.4c.4.3 1.16.65 2.57.65.28 0 .5.22.5.5v2c0 1.03-.13 2.14-.7 3.12a5.4 5.4 0 0 1-3.14 2.35.5.5 0 0 1-.32 0 5.4 5.4 0 0 1-3.15-2.35A6 6 0 0 1 11 12.5v-2a.5.5 0 0 1 .5-.5c1.41 0 2.18-.35 2.57-.65a2 2 0 0 0 .46-.52m.94 0v.01m-.94 0v.01m.15 1.32c-.54.4-1.38.76-2.68.84v1.51c0 .97.12 1.86.56 2.63A4.3 4.3 0 0 0 15 16.97a4.3 4.3 0 0 0 2.44-1.84c.44-.77.56-1.66.56-2.63v-1.51a5 5 0 0 1-2.68-.84L15 9.87q-.14.14-.32.28m-.15-1.32"/></>),
  24: (<><path d="M4.75 5A2.75 2.75 0 0 0 2 7.75v4.5A2.75 2.75 0 0 0 4.75 15H11v-1.5H4.75c-.69 0-1.25-.56-1.25-1.25v-4.5c0-.69.56-1.25 1.25-1.25h12.5c.69 0 1.25.56 1.25 1.25v1.33c.46.55 1 .9 1.5 1.13V7.76A2.75 2.75 0 0 0 17.25 5zM17 9.25a.8.8 0 0 0-.61.32h-.01q-.03.06-.23.28-.25.29-.73.68c-.65.5-1.56.97-2.67.97a.75.75 0 0 0-.75.75V15q0 2.45 1.3 3.98a8 8 0 0 0 3.44 2.22q.26.1.52 0c1.4-.52 2.6-1.2 3.44-2.22A6 6 0 0 0 22 15v-2.75a.75.75 0 0 0-.75-.75 4.4 4.4 0 0 1-2.67-.97 6 6 0 0 1-.96-.95v-.01a.8.8 0 0 0-.62-.32m-.67 2.47q.4-.3.67-.59.27.29.67.59a6 6 0 0 0 2.83 1.23V15c0 1.36-.35 2.3-.95 3.02A6 6 0 0 1 17 19.7a6 6 0 0 1-2.55-1.68A4.5 4.5 0 0 1 13.5 15v-2.05c1.2-.17 2.16-.71 2.83-1.23m.06-2.15Z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ShieldBadgeIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
