// ShiftsAddIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M6 3a3 3 0 0 0-3 3v3.6q.48-.24 1-.4V6c0-1.1.9-2 2-2h8a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2h-3.2q-.15.52-.4 1H14a3 3 0 0 0 3-3V6a3 3 0 0 0-3-3zm-.5 16a4.5 4.5 0 1 0 0-9 4.5 4.5 0 0 0 0 9m0-7c.28 0 .5.22.5.5V14h1.5a.5.5 0 0 1 0 1H6v1.5a.5.5 0 0 1-1 0V15H3.5a.5.5 0 0 1 0-1H5v-1.5c0-.28.22-.5.5-.5M11 6.5a.5.5 0 0 0-1 0v3c0 .28.22.5.5.5h2a.5.5 0 0 0 0-1H11z"/></>),
  24: (<><path d="M4.5 6.25c0-.97.78-1.75 1.75-1.75h11.5c.97 0 1.75.78 1.75 1.75v11.5c0 .97-.78 1.75-1.75 1.75h-5.06a7 7 0 0 1-.71 1.5h5.77c1.8 0 3.25-1.46 3.25-3.25V6.25C21 4.45 19.54 3 17.75 3H6.25A3.25 3.25 0 0 0 3 6.25v5.77q.7-.45 1.5-.7zm2 5.75a5.5 5.5 0 1 1 0 11 5.5 5.5 0 0 1 0-11m.5 8.5V18h2.5a.5.5 0 1 0 0-1H7v-2.5a.5.5 0 1 0-1 0V17H3.5a.5.5 0 0 0 0 1H6v2.5a.5.5 0 1 0 1 0m5.5-13.75a.75.75 0 0 0-1.5 0v6c0 .41.34.75.75.75h4.5a.75.75 0 0 0 0-1.5H12.5z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ShiftsAddIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
