// StackArrowForwardIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M14.5 10a4.5 4.5 0 1 1 0-9 4.5 4.5 0 0 1 0 9m1.6-7.1a.5.5 0 0 0-.7.7l.9.9h-1.55A2.75 2.75 0 0 0 12 7.25v.25a.5.5 0 0 0 1 0v-.25c0-.97.78-1.75 1.75-1.75h1.54l-.9.9a.5.5 0 0 0 .71.7l1.76-1.75a.5.5 0 0 0 0-.7zM14 11v-.02q-.51-.05-1-.19V11a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V5a1 1 0 0 1 1-1h5.2q.16-.52.4-1H4a2 2 0 0 0-2 2v6c0 1.1.9 2 2 2h8a2 2 0 0 0 2-2m1-.02q.51-.05 1-.19V11a4 4 0 0 1-4 4H6a2 2 0 0 1-1.73-1H12a3 3 0 0 0 3-3zm3-1.24q-.46.39-1 .66v.6a5 5 0 0 1-5 5H6.27c.34.6.99 1 1.73 1h4a6 6 0 0 0 6-6z"/></>),
  24: (<><path d="M17.5 12a5.5 5.5 0 1 1 0-11 5.5 5.5 0 0 1 0 11m1.85-8.35a.5.5 0 0 0-.7.7l.64.65h-2.04A3.25 3.25 0 0 0 14 8.25v.25a.5.5 0 0 0 1 0v-.25C15 7.01 16 6 17.25 6h2.04l-.64.65a.5.5 0 0 0 .7.7l1.5-1.5a.5.5 0 0 0 0-.7zM17 13v-.02a7 7 0 0 1-1.5-.3V13a.5.5 0 0 1-.5.5H4a.5.5 0 0 1-.5-.5V6c0-.28.22-.5.5-.5h7.08q.12-.79.42-1.5H4a2 2 0 0 0-2 2v7c0 1.1.9 2 2 2h11a2 2 0 0 0 2-2m1-.02a7 7 0 0 0 1.5-.3v.82a4 4 0 0 1-4 4h-9A2 2 0 0 1 4.56 16H15.5a2.5 2.5 0 0 0 2.5-2.5zm4-1.79q-.67.65-1.5 1.08v1.98c0 2.35-1.9 4.25-4.25 4.25H7.06A2 2 0 0 0 9 20h7.25A5.75 5.75 0 0 0 22 14.25z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function StackArrowForwardIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
