// StarProhibitedIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M8.8 2.1a.9.9 0 0 0-1.6 0L5.66 5.18l-3.4.5a.9.9 0 0 0-.5 1.53l2.46 2.4L3.65 13a.9.9 0 0 0 1.3.95l.92-.48a6 6 0 0 1-.46-.89l-.74.39.35-2.02a6 6 0 0 1 .14-1.76 1 1 0 0 0-.19-.26l-2.35-2.3 3.25-.46a.9.9 0 0 0 .68-.5L8 2.73l1.2 2.42a6 6 0 0 1 1.04-.14zM6 10.5a4.5 4.5 0 1 0 9 0 4.5 4.5 0 0 0-9 0m1 0a3.5 3.5 0 0 1 5.6-2.8l-4.9 4.9a3.5 3.5 0 0 1-.7-2.1m3.5 3.5c-.79 0-1.51-.26-2.1-.7l4.9-4.9a3.5 3.5 0 0 1-2.8 5.6"/></>),
  20: (<><path d="M9.1 2.9a1 1 0 0 1 1.8 0l1.93 3.91 4.31.63a1 1 0 0 1 .56 1.7l-.55.54a6 6 0 0 0-1-.43l.85-.82-4.32-.63a1 1 0 0 1-.75-.55L10 3.35l-1.93 3.9a1 1 0 0 1-.75.55L3 8.43l3.12 3.04a1 1 0 0 1 .3.89l-.75 4.3 3.35-1.76q.03.53.17 1.04l-3.05 1.6a1 1 0 0 1-1.45-1.05l.74-4.3L2.3 9.14a1 1 0 0 1 .56-1.7l4.31-.63zm.9 11.6a4.5 4.5 0 1 0 9 0 4.5 4.5 0 0 0-9 0m1 0a3.5 3.5 0 0 1 5.6-2.8l-4.9 4.9a3.5 3.5 0 0 1-.7-2.1m3.5 3.5c-.78 0-1.51-.26-2.1-.7l4.9-4.9q.68.9.7 2.1a3.5 3.5 0 0 1-3.5 3.5"/></>),
  24: (<><path d="M10.79 3.1c.5-1 1.92-1 2.42 0l2.36 4.78 5.27.77c1.1.16 1.55 1.52.75 2.3l-.9.88a7 7 0 0 0-1.52-.62l1.15-1.12-5.05-.74a1.4 1.4 0 0 1-1.01-.74L12 4.04 9.74 8.6c-.2.4-.58.68-1.02.74l-5.05.74 3.66 3.56c.32.3.46.76.39 1.2l-.87 5.02L11 17.7q.03.82.24 1.57l-3.96 2.08a1.35 1.35 0 0 1-1.96-1.42l.9-5.25-3.81-3.72c-.8-.78-.36-2.14.75-2.3l5.27-.77zM23 17.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0m-9.5 0c0 .83.26 1.6.7 2.25l5.55-5.56a4 4 0 0 0-6.25 3.3m4 4a4 4 0 0 0 3.3-6.25l-5.55 5.56c.64.43 1.42.69 2.25.69"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function StarProhibitedIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
