// SubtractParenthesesIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
  48: '0 0 48 48',
};
const C = {
  16: (<><path d="M4.77 2.94a.5.5 0 1 0-.54-.84 7 7 0 0 0 0 11.8.5.5 0 1 0 .54-.84 6 6 0 0 1 0-10.12m7-.84a.5.5 0 0 0-.54.84 6 6 0 0 1 0 10.12.5.5 0 1 0 .54.84 7 7 0 0 0 0-11.8M5.5 7.5a.5.5 0 0 0 0 1h5a.5.5 0 0 0 0-1z"/></>),
  20: (<><path d="M5.8 4.4a.5.5 0 0 0-.6-.8 8 8 0 0 0 0 12.8.5.5 0 0 0 .6-.8 7 7 0 0 1 0-11.2m9-.8a.5.5 0 0 0-.6.8 7 7 0 0 1 0 11.2.5.5 0 1 0 .6.8 8 8 0 0 0 0-12.8M6.5 9.5a.5.5 0 1 0 0 1h7a.5.5 0 1 0 0-1z"/></>),
  24: (<><path d="M6.72 5.34a.75.75 0 1 0-.93-1.18 9.98 9.98 0 0 0 0 15.68.75.75 0 1 0 .93-1.18 8.48 8.48 0 0 1 0-13.32m11.5-1.18a.75.75 0 1 0-.94 1.18 8.48 8.48 0 0 1 0 13.32.75.75 0 0 0 .93 1.18 9.98 9.98 0 0 0 0-15.68M7.74 11.25a.75.75 0 0 0 0 1.5h8.5a.75.75 0 0 0 0-1.5z"/></>),
  28: (<><path d="M7.7 5.6a.75.75 0 1 0-.9-1.2 11.98 11.98 0 0 0 0 19.2.75.75 0 1 0 .9-1.2 10.48 10.48 0 0 1 0-16.8m13.5-1.2a.75.75 0 1 0-.9 1.2 10.48 10.48 0 0 1 .23 16.62.75.75 0 1 0 .94 1.17A11.98 11.98 0 0 0 21.2 4.4M8.75 13.25a.75.75 0 0 0 0 1.5h10.5a.75.75 0 0 0 0-1.5z"/></>),
  48: (<><path d="M13.5 10A1.25 1.25 0 1 0 12 8a19.97 19.97 0 0 0 0 32 1.25 1.25 0 1 0 1.5-2 17.47 17.47 0 0 1 0-28M36 8a1.25 1.25 0 1 0-1.5 2 17.47 17.47 0 0 1 0 28 1.25 1.25 0 0 0 1.5 2 19.97 19.97 0 0 0 0-32M15.25 22.75a1.25 1.25 0 0 0 0 2.5h17.5a1.25 1.25 0 1 0 0-2.5z"/></>),
};
const SIZES = [16, 20, 24, 28, 48];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function SubtractParenthesesIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
