// TabDesktopArrowClockwiseIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M4 2a2 2 0 0 0-2 2v3a5 5 0 0 1 1-.58V4a1 1 0 0 1 1-1h3v.75C7 4.44 7.56 5 8.25 5H13v7a1 1 0 0 1-1 1H9.58A5 5 0 0 1 9 14h3a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2zm9 2H8.25A.25.25 0 0 1 8 3.75V3h4a1 1 0 0 1 1 1M7.75 6.75c.28 0 .5.22.5.5V9a.5.5 0 0 1-.5.5H6a.5.5 0 0 1 0-1h.66A3 3 0 1 0 8 11a.5.5 0 0 1 1 0 4 4 0 1 1-1.75-3.3v-.45c0-.28.22-.5.5-.5"/></>),
  20: (<><path d="M3 5.5A2.5 2.5 0 0 1 5.5 3h9A2.5 2.5 0 0 1 17 5.5v9a2.5 2.5 0 0 1-2.5 2.5h-3.76q.39-.46.66-1h3.1c.83 0 1.5-.67 1.5-1.5V7H9.5A1.5 1.5 0 0 1 8 5.5V4H5.5C4.67 4 4 4.67 4 5.5v3.1q-.54.27-1 .66zM16 6v-.5c0-.83-.67-1.5-1.5-1.5H9v1.5c0 .28.22.5.5.5zM9.5 8.5c.28 0 .5.22.5.5v2a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h.8a3.5 3.5 0 1 0 1.7 3 .5.5 0 0 1 1 0 4.5 4.5 0 1 1-2-3.74V9c0-.28.22-.5.5-.5"/></>),
  24: (<><path d="M5.75 3A2.75 2.75 0 0 0 3 5.75v5.35q.67-.68 1.5-1.16V5.75c0-.69.56-1.25 1.25-1.25H11v1.25C11 6.99 12 8 13.25 8h6.25v10.25c0 .69-.56 1.25-1.25 1.25h-4.19A7 7 0 0 1 12.9 21h5.35A2.75 2.75 0 0 0 21 18.25V5.75A2.75 2.75 0 0 0 18.25 3zM19.5 6.5h-6.25a.75.75 0 0 1-.75-.75V4.5h5.75c.69 0 1.25.56 1.25 1.25zm-7.25 3.25c.41 0 .75.34.75.75v2.75c0 .41-.34.75-.75.75H9.5a.75.75 0 0 1 0-1.5h1.33l-.02-.01A4.5 4.5 0 1 0 12.5 16a.75.75 0 0 1 1.5 0 6 6 0 1 1-2.5-4.87v-.63c0-.41.34-.75.75-.75"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TabDesktopArrowClockwiseIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
