// TabDesktopImageIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M4 2a2 2 0 0 0-2 2v1.34q.47-.23 1-.3V4a1 1 0 0 1 1-1h3v.5C7 4.33 7.67 5 8.5 5H13v7a1 1 0 0 1-1 1h-1.04q-.07.53-.3 1H12a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2zm9 2H8.5a.5.5 0 0 1-.5-.5V3h4a1 1 0 0 1 1 1M1 8.5A2.5 2.5 0 0 1 3.5 6h4A2.5 2.5 0 0 1 10 8.5v4q-.01.77-.41 1.38l-3.03-3.03a1.5 1.5 0 0 0-2.12 0L1.4 13.88q-.4-.6-.41-1.38zm7 .25a.75.75 0 1 0-1.5 0 .75.75 0 0 0 1.5 0m-5.88 5.84q.6.4 1.38.41h4q.77-.01 1.38-.41l-3.03-3.03a.5.5 0 0 0-.7 0z"/></>),
  20: (<><path d="M3 5.5A2.5 2.5 0 0 1 5.5 3h9A2.5 2.5 0 0 1 17 5.5v9a2.5 2.5 0 0 1-2.5 2.5h-2.84q.22-.47.3-1h2.54c.82 0 1.5-.67 1.5-1.5V7H9.5A1.5 1.5 0 0 1 8 5.5V4H5.5C4.67 4 4 4.67 4 5.5v2.54q-.54.08-1 .3zM16 6v-.5c0-.83-.68-1.5-1.5-1.5H9v1.5c0 .28.22.5.5.5zM2 11.5A2.5 2.5 0 0 1 4.5 9h4a2.5 2.5 0 0 1 2.5 2.5v4q-.01.77-.41 1.38l-3.03-3.03a1.5 1.5 0 0 0-2.12 0L2.4 16.88q-.4-.6-.41-1.38zm7 .25a.75.75 0 1 0-1.5 0 .75.75 0 0 0 1.5 0m-5.88 5.84q.6.4 1.38.41h4q.77-.01 1.38-.41l-3.03-3.03a.5.5 0 0 0-.7 0z"/></>),
  24: (<><path d="M5.75 3A2.75 2.75 0 0 0 3 5.75v4.79q.68-.4 1.5-.5V5.74c0-.69.56-1.25 1.25-1.25H11v1.25C11 6.99 12 8 13.25 8h6.25v10.25c0 .69-.56 1.25-1.25 1.25h-4.28a4 4 0 0 1-.5 1.5h4.78A2.75 2.75 0 0 0 21 18.25V5.75A2.75 2.75 0 0 0 18.25 3zM19.5 6.5h-6.25a.75.75 0 0 1-.75-.75V4.5h5.75c.69 0 1.25.56 1.25 1.25zM5 11a3 3 0 0 0-3 3v5q0 .85.42 1.52l3.49-3.49c.88-.88 2.3-.88 3.18 0l3.5 3.5q.4-.68.41-1.53v-5a3 3 0 0 0-3-3zm0 11q-.85 0-1.52-.42l3.49-3.49c.3-.3.77-.3 1.06 0l3.5 3.5q-.68.4-1.53.41zm5-7a1 1 0 1 1 0-2 1 1 0 0 1 0 2"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TabDesktopImageIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
