// TabInPrivateIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
};
const C = {
  16: (<><path d="M4 2a2 2 0 0 0-2 2v8c0 1.1.9 2 2 2h8a2 2 0 0 0 2-2V4a2 2 0 0 0-2-2zM3 4a1 1 0 0 1 1-1h2.3L3 6.3zm0 3.7L7.7 3h2.6L3 10.3zM11.7 3h.3a1 1 0 0 1 1 1v.3L4.3 13H4a1 1 0 0 1-1-1v-.3zM13 5.7v2.6L8.3 13H5.7zm0 4V12a1 1 0 0 1-1 1H9.7z"/></>),
  20: (<><path d="M5.5 3h9A2.5 2.5 0 0 1 17 5.5v9a2.5 2.5 0 0 1-2.5 2.5h-9A2.5 2.5 0 0 1 3 14.5v-9A2.5 2.5 0 0 1 5.5 3M4 5.5v1.8L7.3 4H5.5C4.67 4 4 4.67 4 5.5m0 3.2v2.6L11.3 4H8.7zM12.7 4 4 12.7v1.8q0 .35.15.65l11-11A2 2 0 0 0 14.5 4zm3.15.85-11 11q.3.15.65.15h1.8L16 7.3V5.5q0-.35-.15-.65M16 8.71 8.7 16h2.6l4.7-4.7zm0 4L12.7 16h1.8c.83 0 1.5-.67 1.5-1.5z"/></>),
  24: (<><path d="M5.75 3h12.5A2.75 2.75 0 0 1 21 5.75v12.5A2.75 2.75 0 0 1 18.25 21H5.75A2.75 2.75 0 0 1 3 18.25V5.75A2.75 2.75 0 0 1 5.75 3M4.5 5.75v1.04L6.8 4.5H5.74c-.69 0-1.25.56-1.25 1.25m0 2.46v2.58l6.3-6.29H8.2zm7.7-3.71-7.7 7.7v2.6L14.8 4.5zm4 0L4.5 16.2v2.05q0 .25.09.46L18.7 4.59q-.22-.09-.46-.09zm3.21.8L5.3 19.4q.21.09.46.09h2.04L19.5 7.8V5.74q0-.25-.09-.46m.09 3.9L9.2 19.5h2.6l7.7-7.7zm0 4-6.3 6.3h2.6l3.7-3.7zm0 4-2.3 2.3h1.05c.69 0 1.25-.56 1.25-1.25z"/></>),
  28: (<><path d="M6.25 3h15.5C23.55 3 25 4.46 25 6.25v15.5c0 1.8-1.46 3.25-3.25 3.25H6.25A3.25 3.25 0 0 1 3 21.75V6.25C3 4.45 4.46 3 6.25 3M4.5 6.25v1.19L7.44 4.5H6.25c-.97 0-1.75.78-1.75 1.75m0 3.31v2.88l7.94-7.94H9.56zM14.56 4.5 4.5 14.56v2.88L17.44 4.5zm5 0L4.5 19.56v2.19q0 .3.1.59L22.34 4.6q-.28-.1-.59-.1zm3.84 1.16L5.66 23.4q.28.1.59.1h2.19L23.5 8.44V6.25q0-.3-.1-.59m.1 4.9L10.56 23.5h2.88L23.5 13.44zm0 5-7.94 7.94h2.88l5.06-5.06zm0 5-2.94 2.94h1.19c.97 0 1.75-.78 1.75-1.75z"/></>),
};
const SIZES = [16, 20, 24, 28];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TabInPrivateIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
