// TableSimpleExcludeIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
  48: '0 0 48 48',
};
const C = {
  16: (<><path d="M3.5 1A2.5 2.5 0 0 0 1 3.5v6A2.5 2.5 0 0 0 3.5 12h3a.5.5 0 0 0 .5-.5V7h4.5a.5.5 0 0 0 .5-.5v-3A2.5 2.5 0 0 0 9.5 1zM6 7v4H3.5A1.5 1.5 0 0 1 2 9.5V7zm0-1H2V3.5C2 2.67 2.67 2 3.5 2H6zm1 0V2h2.5c.83 0 1.5.67 1.5 1.5V6zm1.5 4.25c0-.97.78-1.75 1.75-1.75h3c.97 0 1.75.78 1.75 1.75v3c0 .97-.78 1.75-1.75 1.75h-3c-.97 0-1.75-.78-1.75-1.75z"/></>),
  20: (<><path d="M4.5 2A2.5 2.5 0 0 0 2 4.5v8A2.5 2.5 0 0 0 4.5 15h4a.5.5 0 0 0 .5-.5V9h5.5a.5.5 0 0 0 .5-.5v-4A2.5 2.5 0 0 0 12.5 2zM8 9v5H4.5A1.5 1.5 0 0 1 3 12.5V9zm0-1H3V4.5C3 3.67 3.67 3 4.5 3H8zm1 0V3h3.5c.83 0 1.5.67 1.5 1.5V8zm2 5c0-1.1.9-2 2-2h4a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2h-4a2 2 0 0 1-2-2z"/></>),
  24: (<><path d="M2 5.25C2 3.45 3.46 2 5.25 2h10c1.8 0 3.25 1.46 3.25 3.25V10a1 1 0 0 1-1 1H11v6.5a1 1 0 0 1-1 1H5.25A3.25 3.25 0 0 1 2 15.25zm15 0c0-.97-.78-1.75-1.75-1.75H11v6h6zM9.5 3.5H5.25c-.97 0-1.75.78-1.75 1.75V9.5h6zm-6 11.75c0 .97.78 1.75 1.75 1.75H9.5v-6h-6zm9-.5c0-1.24 1-2.25 2.25-2.25h5c1.24 0 2.25 1 2.25 2.25v5c0 1.24-1 2.25-2.25 2.25h-5c-1.24 0-2.25-1-2.25-2.25z"/></>),
  28: (<><path d="M5.75 2A3.75 3.75 0 0 0 2 5.75v12a3.75 3.75 0 0 0 3.75 3.75h5.75a1 1 0 0 0 1-1v-8h8a1 1 0 0 0 1-1V5.75A3.75 3.75 0 0 0 17.75 2zM11 12.5V20H5.75c-1.24 0-2.25-1-2.25-2.25V12.5zm0-1.5H3.5V5.75c0-1.24 1-2.25 2.25-2.25H11zm1.5 0V3.5h5.25c1.24 0 2.25 1 2.25 2.25V11zm1.5 5.75A2.75 2.75 0 0 1 16.75 14h6.5A2.75 2.75 0 0 1 26 16.75v6.5A2.75 2.75 0 0 1 23.25 26h-6.5A2.75 2.75 0 0 1 14 23.25z"/></>),
  48: (<><path d="M4 10.25C4 6.8 6.8 4 10.25 4h19c3.45 0 6.25 2.8 6.25 6.25V21H21v14.5H10.25A6.25 6.25 0 0 1 4 29.25zm29 0a3.75 3.75 0 0 0-3.75-3.75H21v12h12zM18.5 6.5h-8.25a3.75 3.75 0 0 0-3.75 3.75v8.25h12zm-12 22.75A3.75 3.75 0 0 0 10.25 33h8.25V21h-12zm18.5 0C25 26.9 26.9 25 29.25 25h10.5C42.1 25 44 26.9 44 29.25v10.5C44 42.1 42.1 44 39.75 44h-10.5A4.25 4.25 0 0 1 25 39.75z"/></>),
};
const SIZES = [16, 20, 24, 28, 48];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TableSimpleExcludeIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
