// TabletSpeakerIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M18.1 3.07a4 4 0 0 0-.45-.87.5.5 0 0 0-.8.6l.07.1q.1.18.24.53.33.86.34 2.07a6 6 0 0 1-.58 2.6l-.12.18a.5.5 0 0 0 .85.52q.2-.24.44-.87.4-1.03.41-2.43-.01-1.41-.4-2.43M14 2.5a.5.5 0 0 0-.85-.35L11.29 4h-.79a.5.5 0 0 0-.5.5v2c0 .28.22.5.5.5h.8l1.85 1.85A.5.5 0 0 0 14 8.5zm1.95.78a5.5 5.5 0 0 1 .55 2.22 5 5 0 0 1-.55 2.22.5.5 0 1 1-.9-.44l.08-.17.15-.4q.21-.63.22-1.21 0-.58-.22-1.22l-.23-.56a.5.5 0 1 1 .9-.44M17 9.98V14a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1h5v-.5q0-.27.09-.5H4a2 2 0 0 0-2 2v8c0 1.1.9 2 2 2h12a2 2 0 0 0 2-2V9.8q-.47.26-1 .18M8.5 13a.5.5 0 0 0 0 1h3a.5.5 0 0 0 0-1z"/></>),
  24: (<><path d="M22.14 3.3a5 5 0 0 0-.91-1.13.75.75 0 0 0-.96 1.16q.21.15.59.74c.4.67.64 1.48.64 2.43q-.02 1.42-.64 2.43-.38.59-.59.74a.75.75 0 0 0 .96 1.16c.25-.21.59-.58.91-1.13.54-.9.86-1.96.86-3.2s-.32-2.3-.86-3.2"/><path d="M19.87 4.4q-.36-.53-.67-.75a.75.75 0 0 0-.9 1.2q.1.07.33.38.36.52.37 1.27a2.2 2.2 0 0 1-.7 1.65l-.08.07a.75.75 0 0 0 .98 1.13q.3-.21.67-.75.62-.88.63-2.1-.02-1.22-.63-2.1"/><path d="M17 3.75a.75.75 0 0 0-1.31-.5L14.16 5h-1.41a.75.75 0 0 0-.75.75v1.5c0 .41.34.75.75.75h1.41l1.53 1.74A.75.75 0 0 0 17 9.25z"/><path d="M4.25 4H12a1 1 0 0 0-1 1v.5H4.25a.75.75 0 0 0-.75.75v11.5c0 .42.34.75.75.75h15.5c.41 0 .75-.33.75-.75v-5.77a1.8 1.8 0 0 0 1.5-.5v6.27C22 19 21 20 19.75 20H4.25C3.01 20 2 19 2 17.75V6.25C2 5.01 3 4 4.25 4"/><path d="M13.75 15.5a.75.75 0 0 1 .1 1.5h-3.6a.75.75 0 0 1-.1-1.5h3.6"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TabletSpeakerIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
