// TableEditIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
};
const C = {
  16: (<><path d="M2 4.5A2.5 2.5 0 0 1 4.5 2h7A2.5 2.5 0 0 1 14 4.5v.63a2.9 2.9 0 0 0-2.9.71L10 6.94V6H6v4h.94l-.67.67q-.62.63-.84 1.49l-.37 1.5q-.04.17-.06.34h-.5A2.5 2.5 0 0 1 2 11.5zM5 11H3v.5c0 .83.67 1.5 1.5 1.5H5zm0-5H3v4h2zm1-1h4V3H6zM5 3h-.5C3.67 3 3 3.67 3 4.5V5h2zm8 2v-.5c0-.83-.67-1.5-1.5-1.5H11v2zm-6.02 6.38 4.83-4.83a1.87 1.87 0 1 1 2.64 2.64l-4.83 4.83a2 2 0 0 1-1.02.58l-1.5.37a.9.9 0 0 1-1.07-1.07l.37-1.5q.15-.6.58-1.02"/></>),
  20: (<><path d="M17 5.5A2.5 2.5 0 0 0 14.5 3h-9A2.5 2.5 0 0 0 3 5.5v9A2.5 2.5 0 0 0 5.5 17h3.72l.21-.85.05-.15H8v-3h3.94L13 11.94V8h3v1.23q.48-.2 1-.23zm-13 9V13h3v3H5.36A1.5 1.5 0 0 1 4 14.5M12 8v4H8V8zm0-1H8V4h4zm1-3h1.64A1.5 1.5 0 0 1 16 5.5V7h-3zM4 7V5.36A1.5 1.5 0 0 1 5.5 4H7v3zm3 1v4H4V8zm8.8 2.55-4.82 4.83a2 2 0 0 0-.58 1.02l-.37 1.5a.9.9 0 0 0 1.08 1.07l1.5-.37q.58-.16 1.01-.58l4.83-4.83a1.87 1.87 0 0 0-2.64-2.64M14.66 17 17 14.65Z"/></>),
  24: (<><path d="M3 6.25C3 4.45 4.45 3 6.25 3h11.5C19.55 3 21 4.45 21 6.25v4.76a3 3 0 0 0-1.5.22V10h-4v4h.85L14 16.35v-.85h-4v4h1.54l-.02.08-.36 1.42H6.25A3.25 3.25 0 0 1 3 17.75zM6.25 4.5c-.97 0-1.75.78-1.75 1.75V8.5h4v-4zM4.5 10v4h4v-4zm5.5 0v4h4v-4zm5.5-1.5h4V6.25c0-.97-.78-1.75-1.75-1.75H15.5zm-1.5-4h-4v4h4zm-9.5 11v2.25c0 .97.78 1.75 1.75 1.75H8.5v-4zm15.26-3.3a2 2 0 0 0-.66.47l-5.9 5.9a2.7 2.7 0 0 0-.71 1.25l-.46 1.83c-.2.8.52 1.52 1.32 1.32l1.83-.46q.71-.18 1.25-.7l5.9-5.9a2.29 2.29 0 0 0-2.57-3.7"/></>),
  28: (<><path d="M3 6.75A3.75 3.75 0 0 1 6.75 3h14.5A3.75 3.75 0 0 1 25 6.75v6.26a3 3 0 0 0-1.5.22V11h-5v6h.86L17 19.36v-.86h-6v5h2.54l-.02.08-.35 1.42H6.75A3.75 3.75 0 0 1 3 21.25zM4.5 18.5v2.75c0 1.24 1 2.25 2.25 2.25H9.5v-5zm5-1.5v-6h-5v6zm7.5 0v-6h-6v6zm6.5-10.25c0-1.24-1-2.25-2.25-2.25H18.5v5h5zM17 4.5h-6v5h6zm-7.5 0H6.75c-1.24 0-2.25 1-2.25 2.25V9.5h5zm13.6 10.17-7.9 7.9q-.54.54-.7 1.25l-.47 1.83c-.2.8.53 1.52 1.32 1.32l1.83-.46q.71-.18 1.25-.7l7.9-7.9a2.29 2.29 0 0 0-3.23-3.24"/></>),
};
const SIZES = [16, 20, 24, 28];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TableEditIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
