// TableStackRightIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
};
const C = {
  16: (<><path d="M14 2.5a.5.5 0 0 0-1 0v11a.5.5 0 0 0 1 0zm-12 9A2.5 2.5 0 0 0 4.5 14h5a.5.5 0 0 0 .5-.5v-11a.5.5 0 0 0-.5-.5h-5A2.5 2.5 0 0 0 2 4.5zM9 3v2H6V3zm0 3v4H6V6zm0 5v2H6v-2zm-6-1V6h2v4zm0-5v-.5C3 3.67 3.67 3 4.5 3H5v2zm0 6h2v2h-.5A1.5 1.5 0 0 1 3 11.5z"/></>),
  20: (<><path d="M16.5 3c.28 0 .5.22.5.5v13a.5.5 0 0 1-1 0v-13c0-.28.22-.5.5-.5m-5 0c.28 0 .5.22.5.5v13a.5.5 0 0 1-.5.5H5a2 2 0 0 1-2-2V5c0-1.1.9-2 2-2zM7 4H5a1 1 0 0 0-1 1v2h3zm-3 8h3V8H4zm0 1v2a1 1 0 0 0 1 1h2v-3zm4 0v3h3v-3zm3-1V8H8v4zm0-8H8v3h3z"/></>),
  24: (<><path d="M15.5 3.75a.75.75 0 0 0-.75-.75h-8.5A3.25 3.25 0 0 0 3 6.25v11.5C3 19.55 4.46 21 6.25 21h8.5c.41 0 .75-.34.75-.75zM14 10v4h-4v-4zm-9.5 4v-4h4v4zM14 8.5h-4v-4h4zm-5.5 0h-4V6.25c0-.97.78-1.75 1.75-1.75H8.5zm0 11H6.25c-.97 0-1.75-.78-1.75-1.75V15.5h4zm1.5-4h4v4h-4zm9.5-11.75a.75.75 0 0 1 1.5 0v16.5a.75.75 0 0 1-1.5 0z"/></>),
  28: (<><path d="M3 21.25A3.75 3.75 0 0 0 6.75 25H17.5a1 1 0 0 0 1-1V4a1 1 0 0 0-1-1H6.75A3.75 3.75 0 0 0 3 6.75zM17 9.5h-6v-5h6zM11 11h6v6h-6zM9.5 9.5h-5V6.75c0-1.24 1-2.25 2.25-2.25H9.5zm-5 1.5h5v6h-5zm0 10.25V18.5h5v5H6.75c-1.24 0-2.25-1-2.25-2.25M11 23.5v-5h6v5zM25 3.75a.75.75 0 0 0-1.5 0v20.5a.75.75 0 0 0 1.5 0z"/></>),
};
const SIZES = [16, 20, 24, 28];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TableStackRightIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
