// TableFreezeRowIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
};
const C = {
  16: (<><path d="M11.5 2A2.5 2.5 0 0 1 14 4.5v7a2.5 2.5 0 0 1-2.5 2.5h-7A2.5 2.5 0 0 1 2 11.5v-7A2.5 2.5 0 0 1 4.5 2zM3 6v4h2V6zm10-1v-.5c0-.83-.67-1.5-1.5-1.5h-7C3.67 3 3 3.67 3 4.5V5zM6 6v4h4V6zm5 0v4h2V6zm-1 7v-2H6v2zm-5 0v-2H3v.5c0 .83.67 1.5 1.5 1.5zm6 0h.5c.83 0 1.5-.67 1.5-1.5V11h-2z"/></>),
  20: (<><path d="M14.5 17a2.5 2.5 0 0 0 2.5-2.5v-9A2.5 2.5 0 0 0 14.5 3h-9A2.5 2.5 0 0 0 3 5.5v9A2.5 2.5 0 0 0 5.5 17zM4 12V8h3v4zm12-5H4V5.36A1.5 1.5 0 0 1 5.5 4h9.14A1.5 1.5 0 0 1 16 5.5zM8 8h4v4H8zm-4 6.5V13h3v3H5.36A1.5 1.5 0 0 1 4 14.5m8-1.5v3H8v-3zm4-5v4h-3V8zm0 5v1.64A1.5 1.5 0 0 1 14.5 16H13v-3z"/></>),
  24: (<><path d="M6.25 3A3.25 3.25 0 0 0 3 6.25v11.5C3 19.55 4.46 21 6.25 21h11.5c1.8 0 3.25-1.46 3.25-3.25V6.25C21 4.45 19.54 3 17.75 3zM4.5 6.25c0-.97.78-1.75 1.75-1.75h11.5c.97 0 1.75.78 1.75 1.75V8.5h-15zM10 10h4v4h-4zm-1.5 0v4h-4v-4zm0 5.5v4H6.25c-.97 0-1.75-.78-1.75-1.75V15.5zm1.5 4v-4h4v4zm5.5-5.5v-4h4v4zm0 1.5h4v2.25c0 .97-.78 1.75-1.75 1.75H15.5z"/></>),
  28: (<><path d="M25 6.75A3.75 3.75 0 0 0 21.25 3H6.75A3.75 3.75 0 0 0 3 6.75v14.5A3.75 3.75 0 0 0 6.75 25h14.5A3.75 3.75 0 0 0 25 21.25zM4.5 11h5v6h-5zM17 17h-6v-6h6zM4.5 18.5h5v5H6.75c-1.24 0-2.25-1-2.25-2.25zm12.5 5h-6v-5h6zm6.5-2.25c0 1.24-1 2.25-2.25 2.25H18.5v-5h5zm0-10.25v6h-5v-6zm-19-4.25c0-1.24 1-2.25 2.25-2.25h14.5c1.24 0 2.25 1 2.25 2.25V9.5h-19z"/></>),
};
const SIZES = [16, 20, 24, 28];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TableFreezeRowIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
