// TableCellCenterLinkIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
};
const C = {
  20: (<><path d="M17 5.5A2.5 2.5 0 0 0 14.5 3h-9A2.5 2.5 0 0 0 3 5.5v9A2.5 2.5 0 0 0 5.5 17h3.84a4 4 0 0 1-.3-1H8v-3h2.05c.63-.62 1.5-1 2.45-1h.5V8h3v4h.5q.26 0 .5.04zm-13 9V13h3v3H5.36A1.5 1.5 0 0 1 4 14.5M12 7H8V4h4zm1-3h1.64A1.5 1.5 0 0 1 16 5.5V7h-3zM4 7V5.36A1.5 1.5 0 0 1 5.5 4H7v3zm3 1v4H4V8zm5.5 5a2.5 2.5 0 0 0 0 5h.5a.5.5 0 0 0 0-1h-.5a1.5 1.5 0 0 1 0-3h.5a.5.5 0 0 0 0-1zm3.5 0a.5.5 0 0 0 0 1h.5a1.5 1.5 0 0 1 0 3H16a.5.5 0 0 0 0 1h.5a2.5 2.5 0 0 0 0-5zm-4 2.5c0-.28.22-.5.5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5"/></>),
  24: (<><path d="M6.25 3A3.25 3.25 0 0 0 3 6.25v11.5C3 19.55 4.46 21 6.25 21h5.32a5 5 0 0 1-.51-1.5H10v-4h2.29A4.7 4.7 0 0 1 15.5 14v-4h4v4q.8.05 1.5.33V6.25C21 4.45 19.54 3 17.75 3zM4.5 6.25c0-.97.78-1.75 1.75-1.75H8.5v4h-4zm0 7.75v-4h4v4zm15-5.5h-4v-4h2.25c.97 0 1.75.78 1.75 1.75zm-9.5-4h4v4h-4zM4.5 17.75V15.5h4v4H6.25c-.97 0-1.75-.78-1.75-1.75m18.5 1A3.75 3.75 0 0 0 19.25 15h-.1a.75.75 0 0 0 .1 1.5h.15a2.25 2.25 0 0 1-.15 4.5l-.1.01a.75.75 0 0 0 .1 1.5v-.01h.2A3.75 3.75 0 0 0 23 18.74m-6.5-3a.75.75 0 0 0-.75-.75h-.2a3.75 3.75 0 0 0 .2 7.5h.1a.75.75 0 0 0-.1-1.5h-.15a2.25 2.25 0 0 1 .15-4.5h.1a.75.75 0 0 0 .65-.75m3.5 3a.75.75 0 0 0-.75-.75h-3.6a.75.75 0 0 0 .1 1.5h3.6a.75.75 0 0 0 .65-.75"/></>),
  28: (<><path d="M3 6.75A3.75 3.75 0 0 1 6.75 3h14.5A3.75 3.75 0 0 1 25 6.75v11.58a5 5 0 0 0-1.75-.33h-5.5q-1.15.01-2.12.5H11v5h2.06q.13.81.5 1.5H6.76A3.75 3.75 0 0 1 3 21.25zM4.5 18.5v2.75c0 1.24 1 2.25 2.25 2.25H9.5v-5zm5-1.5v-6h-5v6zm14 0v-6h-5v6zm0-10.25c0-1.24-1-2.25-2.25-2.25H18.5v5h5zM17 4.5h-6v5h6zm-7.5 0H6.75c-1.24 0-2.25 1-2.25 2.25V9.5h5zm8.25 16a2.25 2.25 0 0 0 0 4.5h.5a.75.75 0 0 1 0 1.5h-.5a3.75 3.75 0 1 1 0-7.5h.5a.75.75 0 0 1 0 1.5zM17 22.75c0-.41.34-.75.75-.75h5.5a.75.75 0 0 1 0 1.5h-5.5a.75.75 0 0 1-.75-.75M23.25 25a2.25 2.25 0 0 0 0-4.5h-.5a.75.75 0 0 1 0-1.5h.5a3.75 3.75 0 1 1 0 7.5h-.5a.75.75 0 0 1 0-1.5z"/></>),
};
const SIZES = [20, 24, 28];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TableCellCenterLinkIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
