// TableCellCenterEditIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
};
const C = {
  16: (<><path d="M2 4.5A2.5 2.5 0 0 1 4.5 2h7A2.5 2.5 0 0 1 14 4.5V6q-.51.03-1 .23V6h-2v1.94L7.94 11H6v2h.48l-.05.16-.2.84H4.5A2.5 2.5 0 0 1 2 11.5zM5 11H3v.5c0 .83.67 1.5 1.5 1.5H5zm0-5H3v4h2zm1-1h4V3H6zM5 3h-.5C3.67 3 3 3.67 3 4.5V5h2zm8 2v-.5c0-.83-.67-1.5-1.5-1.5H11v2zm-5.02 7.38 4.83-4.83a1.87 1.87 0 1 1 2.64 2.64l-4.83 4.83a2 2 0 0 1-1.02.58l-1.5.37a.9.9 0 0 1-1.07-1.07l.37-1.5q.15-.6.58-1.02"/></>),
  20: (<><path d="M17 5.5A2.5 2.5 0 0 0 14.5 3h-9A2.5 2.5 0 0 0 3 5.5v9A2.5 2.5 0 0 0 5.5 17h3.72l.21-.84.05-.16H8v-3h3.94L13 11.94V8h3v1.23q.48-.2 1-.23zm-13 9V13h3v3H5.36A1.5 1.5 0 0 1 4 14.5M12 7H8V4h4zm1-3h1.64A1.5 1.5 0 0 1 16 5.5V7h-3zM4 7V5.36A1.5 1.5 0 0 1 5.5 4H7v3zm3 1v4H4V8zm3.98 7.38 4.83-4.83a1.87 1.87 0 1 1 2.64 2.64l-4.83 4.83a2 2 0 0 1-1.02.58l-1.5.37a.9.9 0 0 1-1.07-1.07l.37-1.5q.16-.6.58-1.02"/></>),
  24: (<><path d="M6.25 3A3.25 3.25 0 0 0 3 6.25v11.5C3 19.55 4.46 21 6.25 21h4.92l.35-1.42.02-.08H10v-4h4v.86L16.36 14h-.86v-4h4v1.23q.73-.28 1.5-.22V6.25C21 4.45 19.54 3 17.75 3zM4.5 6.25c0-.97.78-1.75 1.75-1.75H8.5v4h-4zm0 7.75v-4h4v4zm15-5.5h-4v-4h2.25c.97 0 1.75.78 1.75 1.75zm-9.5-4h4v4h-4zM4.5 17.75V15.5h4v4H6.25c-.97 0-1.75-.78-1.75-1.75m14.6-5.08-5.9 5.9q-.54.54-.7 1.25l-.47 1.83c-.2.8.53 1.52 1.32 1.32l1.83-.46q.71-.18 1.25-.7l5.9-5.9a2.29 2.29 0 0 0-3.23-3.24"/></>),
  28: (<><path d="M6.75 3A3.75 3.75 0 0 0 3 6.75v14.5A3.75 3.75 0 0 0 6.75 25h6.42l.35-1.42.02-.08H11v-5h6v.86L19.36 17h-.86v-6h5v2.23q.73-.28 1.5-.22V6.75A3.75 3.75 0 0 0 21.25 3zM4.5 21.25V18.5h5v5H6.75c-1.24 0-2.25-1-2.25-2.25M9.5 11v6h-5v-6zm11.75-6.5c1.24 0 2.25 1 2.25 2.25V9.5h-5v-5zM11 4.5h6v5h-6zm-4.25 0H9.5v5h-5V6.75c0-1.24 1-2.25 2.25-2.25M23.1 14.67l-7.9 7.9q-.54.54-.7 1.25l-.47 1.83c-.2.8.53 1.52 1.32 1.32l1.83-.46q.71-.18 1.25-.7l7.9-7.9a2.29 2.29 0 0 0-3.23-3.24"/></>),
};
const SIZES = [16, 20, 24, 28];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TableCellCenterEditIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
