// TableColumnTopBottomIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
};
const C = {
  16: (<><path d="M4.5 2A2.5 2.5 0 0 0 2 4.5v7A2.5 2.5 0 0 0 4.5 14h7a2.5 2.5 0 0 0 2.5-2.5v-7A2.5 2.5 0 0 0 11.5 2zM3 11h2v2h-.5A1.5 1.5 0 0 1 3 11.5zm7-1H6V6h4zM3 6h2v4H3zm1.5-3H5v2H3v-.5C3 3.67 3.67 3 4.5 3M11 6h2v4h-2zm0 5h2v.5c0 .83-.67 1.5-1.5 1.5H11zm2-6.5V5h-2V3h.5c.83 0 1.5.67 1.5 1.5"/></>),
  20: (<><path d="M17 5.5A2.5 2.5 0 0 0 14.5 3h-9A2.5 2.5 0 0 0 3 5.5v9A2.5 2.5 0 0 0 5.5 17h9a2.5 2.5 0 0 0 2.5-2.5zm-13 9V13h3v3H5.36A1.5 1.5 0 0 1 4 14.5M14.5 16H13v-3h3v1.64A1.5 1.5 0 0 1 14.5 16M12 8v4H8V8zm1 0h3v4h-3zm0-4h1.64A1.5 1.5 0 0 1 16 5.5V7h-3zM4 7V5.36A1.5 1.5 0 0 1 5.5 4H7v3zm3 1v4H4V8z"/></>),
  24: (<><path d="M3 6.25C3 4.45 4.46 3 6.25 3h11.5C19.55 3 21 4.46 21 6.25v11.5c0 1.8-1.46 3.25-3.25 3.25H6.25A3.25 3.25 0 0 1 3 17.75zM6.25 4.5c-.97 0-1.75.78-1.75 1.75V8.5h4v-4zM4.5 10v4h4v-4zm5.5 0v4h4v-4zm5.5 0v4h4v-4zm0 9.5h2.25c.97 0 1.75-.78 1.75-1.75V15.5h-4zm0-11h4V6.25c0-.97-.78-1.75-1.75-1.75H15.5zm-11 7v2.25c0 .97.78 1.75 1.75 1.75H8.5v-4z"/></>),
  28: (<><path d="M6.75 3A3.75 3.75 0 0 0 3 6.75v14.5A3.75 3.75 0 0 0 6.75 25h14.5A3.75 3.75 0 0 0 25 21.25V6.75A3.75 3.75 0 0 0 21.25 3zM4.5 21.25V18.5h5v5H6.75c-1.24 0-2.25-1-2.25-2.25M9.5 11v6h-5v-6zm7.5 0v6h-6v-6zm1.5 12.5v-5h5v2.75c0 1.24-1 2.25-2.25 2.25zm5-12.5v6h-5v-6zm-2.25-6.5c1.24 0 2.25 1 2.25 2.25V9.5h-5v-5zm-14.5 0H9.5v5h-5V6.75c0-1.24 1-2.25 2.25-2.25"/></>),
};
const SIZES = [16, 20, 24, 28];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TableColumnTopBottomIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
