// TextBulletListSquareShieldIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  48: '0 0 48 48',
};
const C = {
  20: (<><path d="M14.12 9.96c.2-.19.56-.19.76 0 .5.49 1.48 1.26 2.68 1.41.24.04.44.22.44.44v2.11c0 2.84-2.78 3.87-3.39 4.06a.4.4 0 0 1-.22 0c-.6-.19-3.39-1.22-3.39-4.06v-2.1c0-.23.2-.41.44-.45a5 5 0 0 0 2.68-1.4M14.25 3A2.75 2.75 0 0 1 17 5.75v4.44a4 4 0 0 1-1-.58V5.75C16 4.78 15.22 4 14.25 4h-8.5C4.78 4 4 4.78 4 5.75v8.5c0 .97.78 1.75 1.75 1.75h4.71q.27.56.65 1H5.75A2.75 2.75 0 0 1 3 14.25v-8.5A2.75 2.75 0 0 1 5.75 3zm-7.5 9.5a.75.75 0 1 1 0 1.5.75.75 0 0 1 0-1.5M10 13.92V14h-.5a.5.5 0 0 1 0-1h.5zM6.75 9.5a.75.75 0 1 1 0 1.5.75.75 0 0 1 0-1.5m5.65.5q-.43.25-.93.36l-.27.04c-.34.07-.7.28-.94.6H9.5a.5.5 0 0 1 0-1zM6.75 6.5a.75.75 0 1 1 0 1.5.75.75 0 0 1 0-1.5m6.75.5a.5.5 0 0 1 0 1h-4a.5.5 0 0 1 0-1z"/></>),
  48: (<><path d="M12.25 6A6.25 6.25 0 0 0 6 12.25v23.5C6 39.2 8.8 42 12.25 42h14.4a13 13 0 0 1-1.5-2.5h-12.9a3.75 3.75 0 0 1-3.75-3.75v-23.5a3.75 3.75 0 0 1 3.75-3.75h23.5a3.75 3.75 0 0 1 3.75 3.75v11.49l.22.12q1.16.6 2.28.96V12.25C42 8.8 39.2 6 35.75 6zM42 26.9q1.57.4 3.17.4c.46 0 .83.37.83.82v5.78c0 5.5-3.29 9.54-9.7 12.04a1 1 0 0 1-.6 0 18 18 0 0 1-6.78-4.34 11 11 0 0 1-1.86-2.75A11.4 11.4 0 0 1 26 33.9v-5.77c0-.46.37-.83.83-.83q4.44 0 8.67-3.14c.3-.21.7-.21 1 0a19 19 0 0 0 3 1.82 14 14 0 0 0 2.5.92M29.34 25c1.61-.4 3.25-1.17 4.9-2.4q-.22-.1-.49-.1h-13.5a1.25 1.25 0 1 0 0 2.5zM24 33v-2.5h-3.75a1.25 1.25 0 1 0 0 2.5zm-7-17.25a2 2 0 1 1-4 0 2 2 0 0 1 4 0m0 8a2 2 0 1 1-4 0 2 2 0 0 1 4 0m-2 10a2 2 0 1 0 0-4 2 2 0 0 0 0 4m4-18c0-.69.56-1.25 1.25-1.25h13.5a1.25 1.25 0 1 1 0 2.5h-13.5c-.69 0-1.25-.56-1.25-1.25"/></>),
};
const SIZES = [20, 48];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TextBulletListSquareShieldIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
