// TextWrapOffIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M14.15 14.85 11.29 12H9.71l.64.65a.5.5 0 0 1-.7.7l-1.5-1.5a.5.5 0 0 1 0-.7L9.29 10l-2-2H2.5a.5.5 0 0 1 0-1h3.8l-3-3h-.8a.5.5 0 0 1-.18-.97L1.15 1.85a.5.5 0 1 1 .7-.7l13 13a.5.5 0 0 1-.7.7M10.12 8l-1-1h3.38a2.5 2.5 0 0 1 1.27 4.65l-.74-.74A1.5 1.5 0 0 0 12.5 8zm-4-4-1-1h8.38a.5.5 0 0 1 0 1zM6 11a.5.5 0 0 1 0 1H2.5a.5.5 0 0 1 0-1z"/></>),
  20: (<><path d="M2.85 2.15a.5.5 0 1 0-.7.7L3.29 4H2.5a.5.5 0 0 0 0 1h1.8l4 4H2.5a.5.5 0 0 0 0 1h6.8l2.52 2.53a1 1 0 0 0-.17.12l-1.5 1.5a.5.5 0 0 0 0 .7l1.5 1.5a.5.5 0 0 0 .7-.7l-.64-.65h2.58l2.86 2.85a.5.5 0 0 0 .7-.7zM13.3 14h-1.58l.64-.65a1 1 0 0 0 .12-.17zm-2.17-5 1 1H16a2 2 0 0 1 .12 4l.84.84A3 3 0 0 0 16 9zm-5-5 1 1H17.5a.5.5 0 0 0 0-1zM2 14.5c0-.28.22-.5.5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5"/></>),
  24: (<><path d="M3.28 2.22a.75.75 0 1 0-1.06 1.06L3.94 5H2.75a.75.75 0 0 0 0 1.5h2.69l5 5H2.75a.75.75 0 0 0 0 1.5h9.19l3.03 3.03a.8.8 0 0 0-.75.19l-2 2c-.3.3-.3.77 0 1.06l2 2a.75.75 0 1 0 1.06-1.06l-.72-.72h3.88l2.28 2.28a.75.75 0 0 0 1.06-1.06zM16.94 18h-2.38l.72-.72c.2-.2.27-.5.19-.75zM19 11.5h-4.32l1.5 1.5H19a2.5 2.5 0 0 1 1.6 4.42l1.06 1.06A3.99 3.99 0 0 0 19 11.5M8.18 5l1.5 1.5h11.57a.75.75 0 0 0 0-1.5zM2 18.75c0-.41.34-.75.75-.75h6.5a.75.75 0 0 1 0 1.5h-6.5a.75.75 0 0 1-.75-.75"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TextWrapOffIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
