// TextDirectionRotate45RightIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M1.15 6.15c.2-.2.5-.2.7 0L9 13.29V12a.5.5 0 0 1 1 0v2.5a.5.5 0 0 1-.5.5H7a.5.5 0 0 1 0-1h1.3L1.14 6.85a.5.5 0 0 1 0-.7m9.5-.5c.2-.2.5-.2.7 0L14 8.29V7a.5.5 0 0 1 1 0v2.5a.5.5 0 0 1-.5.5H12a.5.5 0 0 1 0-1h1.3l-2.65-2.65a.5.5 0 0 1 0-.7m-.29-4.63a.5.5 0 0 1 .6.69l-3 6.5a.5.5 0 0 1-.91-.42l.9-1.95-1.8-1.79-1.94.9a.5.5 0 1 1-.42-.9l6.5-3zM7.13 3.6l1.26 1.26 1.09-2.35z"/></>),
  20: (<><path d="M18 8.5a.5.5 0 0 0-1 0v1.8l-3.15-3.15a.5.5 0 1 0-.7.7L16.29 11H14.5a.5.5 0 1 0 0 1h3a.5.5 0 0 0 .5-.5zm-5.05-5.78a.5.5 0 0 0-.67-.67l-8 4a.5.5 0 0 0 .45.9l2.34-1.18 2.15 2.16-1.17 2.35a.5.5 0 1 0 .9.44zM9.7 7 8 5.3l3.37-1.68zm2.3 7.5a.5.5 0 0 0-1 0v1.8L2.85 8.15a.5.5 0 1 0-.7.7L10.29 17H8.5a.5.5 0 1 0 0 1h3a.5.5 0 0 0 .5-.5z"/></>),
  24: (<><path d="M21.25 10.5a.75.75 0 0 0-.75.75v1.19l-4.22-4.22a.75.75 0 1 0-1.06 1.06l4.22 4.22h-1.19a.75.75 0 0 0 0 1.5h3c.41 0 .75-.34.75-.75v-3a.75.75 0 0 0-.75-.75m-5.32-7.43a.75.75 0 0 0-1-1l-9.5 4.5a.75.75 0 1 0 .64 1.36L8.65 6.7l2.64 2.64-1.22 2.58a.75.75 0 0 0 1.36.64zm-3.96 4.84L10.1 6.03l3.58-1.7zM15 18.25a.75.75 0 0 0-1.5 0v1.19L3.28 9.22a.75.75 0 1 0-1.06 1.06L12.44 20.5h-1.19a.75.75 0 0 0 0 1.5h3c.41 0 .75-.34.75-.75z"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TextDirectionRotate45RightIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
