// TextPositionSquareRightIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M13.5 2a.5.5 0 0 1 0 1h-11a.5.5 0 0 1 0-1zM6 4.5a.5.5 0 0 1 0 1H2.5a.5.5 0 0 1 0-1zm.5 3A.5.5 0 0 0 6 7H2.5a.5.5 0 0 0 0 1H6a.5.5 0 0 0 .5-.5m-.5 2a.5.5 0 0 1 0 1H2.5a.5.5 0 0 1 0-1zm8 3a.5.5 0 0 0-.5-.5h-11a.5.5 0 0 0 0 1h11a.5.5 0 0 0 .5-.5M13 7a2 2 0 1 0-4 0v3.5a.5.5 0 0 1-1 0V7a3 3 0 0 1 6 0v3.5a.5.5 0 0 1-1 0z"/></>),
  20: (<><path d="M16.5 3a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1zM8 6a.5.5 0 0 1 0 1H3.5a.5.5 0 0 1 0-1zm.5 3.5A.5.5 0 0 0 8 9H3.5a.5.5 0 0 0 0 1H8a.5.5 0 0 0 .5-.5M8 12a.5.5 0 0 1 0 1H3.5a.5.5 0 0 1 0-1zm9 3.5a.5.5 0 0 0-.5-.5h-13a.5.5 0 0 0 0 1h13a.5.5 0 0 0 .5-.5m-1-7a2.5 2.5 0 0 0-5 0v5a.5.5 0 0 1-1 0v-5a3.5 3.5 0 1 1 7 0v5a.5.5 0 0 1-1 0z"/></>),
  24: (<><path d="M20.25 4a.75.75 0 0 1 0 1.5H3.75a.75.75 0 0 1 0-1.5zm-9.5 3.5a.75.75 0 0 1 0 1.5h-7a.75.75 0 1 1 0-1.5zm.75 7.75a.75.75 0 0 0-.75-.75h-7a.75.75 0 0 0 0 1.5h7c.41 0 .75-.34.75-.75M10.75 11a.75.75 0 0 1 0 1.5h-7a.75.75 0 0 1 0-1.5zM21 18.75a.75.75 0 0 0-.75-.75H3.75a.75.75 0 0 0 0 1.5h16.5c.41 0 .75-.34.75-.75M19.5 11a2.5 2.5 0 0 0-5 0v4.75a.75.75 0 0 1-1.5 0V11a4 4 0 0 1 8 0v4.75a.75.75 0 0 1-1.5 0z"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TextPositionSquareRightIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
