// TextGrammarCheckmarkIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M17.5 5a.5.5 0 0 1 0 1h-15a.5.5 0 0 1 0-1zm0 3a.5.5 0 0 1 0 1h-15a.5.5 0 0 1 0-1zM9 14.5q0-.26.02-.5H2.5a.5.5 0 0 0 0 1h6.52zm.6-2.5q.27-.54.66-1H2.5a.5.5 0 0 0 0 1zm4.9-2a4.5 4.5 0 1 1 0 9 4.5 4.5 0 0 1 0-9m-1.12 5.77-1-1.23-.06-.06a.5.5 0 0 0-.72.7l1.34 1.64.07.07c.2.16.48.15.67-.02l3.5-3.65.07-.06a.5.5 0 0 0-.75-.66z"/></>),
  24: (<><path d="M17.5 12a5.5 5.5 0 1 1 0 11 5.5 5.5 0 0 1 0-11m2.65 3.15-4.1 4.09-1.15-1.54a.5.5 0 0 0-.8.6l1.5 2a.5.5 0 0 0 .75.05l4.5-4.5a.5.5 0 0 0-.7-.7M11.02 17H2.65a.75.75 0 0 0 .1 1.5h8.33a7 7 0 0 1-.06-1.5m.71-2.5H2.75a.75.75 0 0 1-.1-1.5H12.8q-.65.67-1.08 1.5M21.25 9H2.65a.75.75 0 0 0 .1 1.5h18.6a.75.75 0 0 0-.1-1.5m0-4H2.65a.75.75 0 0 0 .1 1.5h18.6a.75.75 0 0 0-.1-1.5"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TextGrammarCheckmarkIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
