// TextAbcUnderlineDoubleIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  32: '0 0 32 32',
};
const C = {
  32: (<><path d="M7.5 5a1 1 0 0 1 .92.6l3.5 8a1 1 0 1 1-1.84.8l-.6-1.4H5.52l-.61 1.4a1 1 0 0 1-1.84-.8l3.5-8A1 1 0 0 1 7.5 5m1.1 6L7.5 8.5 6.4 11zM4 19a1 1 0 1 0 0 2h24a1 1 0 0 0 0-2zm0 6a1 1 0 1 0 0 2h24a1 1 0 0 0 0-2zm9-19a1 1 0 0 1 1-1h2.5a3 3 0 0 1 2.46 4.72A3 3 0 0 1 17 15h-3a1 1 0 0 1-1-1zm2 5v2h2a1 1 0 0 0 0-2zm0-2h1.5a1 1 0 0 0 0-2H15zm8 1c0-1.18.3-1.93.65-2.37Q24.17 7 24.98 7c.66 0 1.23.32 1.6 1.18a1 1 0 1 0 1.84-.8A3.7 3.7 0 0 0 24.98 5c-1.11 0-2.15.46-2.88 1.37-.73.9-1.1 2.14-1.1 3.63 0 1.5.37 2.74 1.1 3.63A3.6 3.6 0 0 0 24.98 15c1.53 0 2.78-.87 3.44-2.38a1 1 0 1 0-1.84-.8c-.37.86-.94 1.18-1.6 1.18q-.8 0-1.33-.63c-.36-.44-.65-1.2-.65-2.37"/></>),
};
const SIZES = [32];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TextAbcUnderlineDoubleIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
