// TextDirectionVerticalIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M4.5 2c.28 0 .5.22.5.5v9.8l1.15-1.15a.5.5 0 1 1 .7.7l-2 2a.5.5 0 0 1-.7 0l-2-2a.5.5 0 1 1 .7-.7L4 12.29V2.5c0-.28.22-.5.5-.5m6 7.5c.28 0 .5.22.5.5v2.3l1.15-1.15a.5.5 0 1 1 .7.7l-2 2a.5.5 0 0 1-.7 0l-2-2a.5.5 0 1 1 .7-.7L10 12.29V10c0-.28.22-.5.5-.5m0-7.5c.2 0 .4.13.47.32l2.5 6.5a.5.5 0 0 1-.94.36L11.7 7H9.3l-.83 2.18a.5.5 0 0 1-.94-.36l2.5-6.5.04-.07A.5.5 0 0 1 10.5 2m-.81 4h1.62l-.81-2.1z"/></>),
  20: (<><path d="M5 3.5a.5.5 0 0 1 1 0v11.8l1.15-1.15a.5.5 0 0 1 .7.7l-2 2a.5.5 0 0 1-.35.15.5.5 0 0 1-.35-.15l-2-2a.5.5 0 0 1 .7-.7L5 15.29zm8 9a.5.5 0 0 1 1 0v2.8l1.15-1.15a.5.5 0 0 1 .7.7l-2 2a.5.5 0 0 1-.7 0l-2-2a.5.5 0 0 1 .7-.7L13 15.29zm.5-9.5a.5.5 0 0 0-.47.32l-3 8a.5.5 0 0 0 .94.36l1-2.68h3.06l1 2.68a.5.5 0 0 0 .94-.36l-3-8A.5.5 0 0 0 13.5 3m0 1.92L14.65 8h-2.3z"/></>),
  24: (<><path d="M6 3.75a.75.75 0 0 1 1.5 0v14.69l.72-.72a.75.75 0 0 1 1.06 1.06l-2 2c-.3.3-.77.3-1.06 0l-2-2a.75.75 0 1 1 1.06-1.06l.72.72zm5.55 9.22 3.76-9.5a.75.75 0 0 1 1.34-.1l.05.1 3.75 9.5a.75.75 0 0 1-1.35.65l-.05-.1-1-2.52h-4.1l-1 2.52a.75.75 0 0 1-.88.45l-.1-.03a.75.75 0 0 1-.45-.87zM16 5.79 14.54 9.5h2.92zm.25 8.21a.75.75 0 0 0-.75.75v3.69l-.72-.72a.75.75 0 1 0-1.06 1.06l2 2c.3.3.77.3 1.06 0l2-2a.75.75 0 1 0-1.06-1.06l-.72.72v-3.69a.75.75 0 0 0-.75-.75"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TextDirectionVerticalIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
