// TextParagraphDirectionRightIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M9 3a2.5 2.5 0 0 0 0 5h1V3zm2 0v10.5a.5.5 0 0 1-1 0V9H9a3.5 3.5 0 1 1 0-7h4.5a.5.5 0 0 1 0 1H13v10.5a.5.5 0 0 1-1 0V3zM2.15 6.15c.2-.2.5-.2.7 0l1.5 1.5c.2.2.2.5 0 .7l-1.5 1.5a.5.5 0 0 1-.7-.7L3.29 8 2.15 6.85a.5.5 0 0 1 0-.7"/></>),
  20: (<><path d="M11.5 3a4 4 0 1 0 0 8H13v6.5a.5.5 0 0 0 1 0V4h1v13.5a.5.5 0 0 0 1 0V4h.5a.5.5 0 0 0 0-1zM13 4v6h-1.5a3 3 0 0 1 0-6zM3.15 7.65c.2-.2.5-.2.7 0l2 2c.2.2.2.5 0 .7l-2 2a.5.5 0 0 1-.7-.7L4.79 10 3.15 8.35a.5.5 0 0 1 0-.7"/></>),
  24: (<><path d="M8 8.5A5.5 5.5 0 0 1 13.5 3h6.55c.52 0 .95.34.95.75 0 .38-.36.7-.83.74l-.12.01h-.55v16.7c0 .45-.34.8-.75.8a.77.77 0 0 1-.75-.8V4.5h-1.5v16.7c0 .45-.34.8-.75.8a.77.77 0 0 1-.75-.8V14h-1.5A5.5 5.5 0 0 1 8 8.5m7-4h-1.5a4 4 0 0 0 0 8H15zM4.08 14.86a.67.67 0 0 1-.9-.99L4.9 12l-1.72-1.87-.06-.08a.67.67 0 0 1 1.03-.84l2.15 2.33.06.08c.18.26.16.6-.06.84l-2.15 2.33z"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TextParagraphDirectionRightIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
