// TextHeader4Icon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M15.71 4.23c.45-.47 1.3-.17 1.3.52V12h1.5a.5.5 0 0 1 0 1H17v2.5a.5.5 0 0 1-1 0V13h-4.32a1 1 0 0 1-.83-1.56l4.77-7.1zM9.5 4c.28 0 .5.22.5.5v11a.5.5 0 0 1-1 0V10H3v5.5a.5.5 0 0 1-1 0v-11a.5.5 0 0 1 1 0V9h6V4.5c0-.28.22-.5.5-.5m2.19 8H16V5.58z"/></>),
  24: (<><path d="M10.75 5c.41 0 .75.34.75.75v12.5a.75.75 0 0 1-1.5 0V12.5H3.5v5.75a.75.75 0 0 1-1.5 0V5.75a.75.75 0 0 1 1.5 0V11H10V5.75c0-.41.34-.75.75-.75m8.55.3A1 1 0 0 1 21 6v8.5h1.25a.75.75 0 0 1 0 1.5H21v2.25a.75.75 0 0 1-1.5 0V16h-5.34a1.25 1.25 0 0 1-1.02-1.97l6.05-8.6zm-4.66 9.2h4.86V7.58z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TextHeader4Icon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
