// TextPositionTightIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M3 3.5c0-.28.22-.5.5-.5h13a.5.5 0 0 1 0 1h-13a.5.5 0 0 1-.5-.5M3.5 6h2.76q-.31.45-.5 1H3.5a.5.5 0 0 1 0-1m0 3h2v1h-2a.5.5 0 0 1 0-1m0 3h2v1h-2a.5.5 0 0 1 0-1m0 3h13a.5.5 0 0 1 0 1h-13a.5.5 0 0 1 0-1m13-2h-2v-1h2a.5.5 0 0 1 0 1m-2-4v1h2a.5.5 0 0 0 0-1zm-.76-3q.31.45.5 1h2.26a.5.5 0 0 0 0-1zM7.5 8.5a2.5 2.5 0 0 1 5 0v5a.5.5 0 0 0 1 0v-5a3.5 3.5 0 1 0-7 0v5a.5.5 0 0 0 1 0z"/></>),
  24: (<><path d="M3.75 4a.75.75 0 0 0 0 1.5h16.5a.75.75 0 0 0 0-1.5zM3 8.25c0-.41.34-.75.75-.75h4.68A5 5 0 0 0 7.42 9H3.75A.75.75 0 0 1 3 8.25M15.46 9a4 4 0 0 0-5.4-1.5A4 4 0 0 0 8 11v4.75a.75.75 0 1 0 1.5 0V11a2.5 2.5 0 1 1 5 0v4.75a.75.75 0 0 0 .75.75.75.75 0 0 0 .75-.75V11q-.01-1.1-.54-2M3.75 11H7v1.5H3.75a.75.75 0 0 1 0-1.5m0 3.5H7v1.25q0 .13.02.25H3.75a.75.75 0 0 1 0-1.5m16.5 1.5h-3.27l.02-.25V14.5h3.25a.75.75 0 0 1 0 1.5m0-3.5H17V11h3.25a.75.75 0 0 1 0 1.5m0-3.5h-3.67a5 5 0 0 0-1-1.5h4.67a.75.75 0 0 1 0 1.5m-16.5 9a.75.75 0 0 0 0 1.5h16.5a.75.75 0 0 0 0-1.5z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TextPositionTightIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
