// TextDirectionHorizontalRightIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="M11.15 9.15c.2-.2.5-.2.7 0l2 2c.2.2.2.5 0 .7l-2 2a.5.5 0 0 1-.7-.7L12.29 12H2.5a.5.5 0 0 1 0-1h9.8l-1.15-1.15a.5.5 0 0 1 0-.7M5 2c.2 0 .4.13.47.32l2.5 6.5a.5.5 0 0 1-.94.36L6.2 7H3.8l-.83 2.18a.5.5 0 0 1-.94-.36l2.5-6.5.04-.07A.5.5 0 0 1 5 2m6.15 1.15c.2-.2.5-.2.7 0l2 2c.2.2.2.5 0 .7l-2 2a.5.5 0 0 1-.7-.7L12.29 6H8.5a.5.5 0 0 1 0-1h3.8l-1.15-1.15a.5.5 0 0 1 0-.7M4.19 6H5.8L5 3.9z"/></>),
  20: (<><path d="M6.5 3c.2 0 .4.13.47.32l3 8a.5.5 0 0 1-.94.36L8.03 9H4.97l-1 2.68a.5.5 0 0 1-.94-.36l3-8A.5.5 0 0 1 6.5 3m0 1.92L5.35 8h2.3zm8.35-.77a.5.5 0 1 0-.7.7L15.29 6H10.5a.5.5 0 0 0 0 1h4.8l-1.15 1.15a.5.5 0 1 0 .7.7l2-2a.5.5 0 0 0 0-.7zm0 8a.5.5 0 0 0-.7.7L15.29 14H3.5a.5.5 0 0 0 0 1h11.8l-1.15 1.15a.5.5 0 0 0 .7.7l2-2a.5.5 0 0 0 0-.7z"/></>),
  24: (<><path d="m3.05 12.97 3.76-9.5a.75.75 0 0 1 1.34-.1l.05.1 3.75 9.5a.75.75 0 0 1-1.35.65l-.05-.1-1-2.52h-4.1l-1 2.52a.75.75 0 0 1-.88.45l-.1-.03a.75.75 0 0 1-.45-.87zM7.5 5.79 6.04 9.5h2.92zM12 7.75c0 .41.34.75.75.75h5.69l-.72.72a.75.75 0 1 0 1.06 1.06l2-2c.3-.3.3-.77 0-1.06l-2-2a.75.75 0 1 0-1.06 1.06l.72.72h-5.69a.75.75 0 0 0-.75.75m-9 9.5c0 .41.34.75.75.75h14.69l-.72.72a.75.75 0 1 0 1.06 1.06l2-2c.3-.3.3-.77 0-1.06l-2-2a.75.75 0 1 0-1.06 1.06l.72.72H3.75a.75.75 0 0 0-.75.75"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TextDirectionHorizontalRightIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
