// TextAsteriskIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
};
const C = {
  16: (<><path d="M13.5 7.5H9.2l3.04-3.04a.5.5 0 0 0-.7-.7L8.5 6.79V2.5a.5.5 0 0 0-1 0v4.3L4.46 3.75a.5.5 0 0 0-.7.7L6.79 7.5H2.5a.5.5 0 0 0 0 1h4.3l-3.04 3.04a.5.5 0 0 0 .7.7L7.5 9.21v4.29a.5.5 0 0 0 1 0V9.2l3.04 3.04a.5.5 0 0 0 .7 0 .5.5 0 0 0 0-.7L9.22 8.5h4.3a.5.5 0 0 0 0-1z"/></>),
  20: (<><path d="M10.5 2.5a.5.5 0 0 0-1 0v6.3L5.05 4.33a.5.5 0 1 0-.7.71L8.78 9.5H2.5a.5.5 0 0 0 0 1h6.3l-4.46 4.45a.5.5 0 1 0 .71.7l4.45-4.44v6.29a.5.5 0 0 0 1 0v-6.3l4.45 4.46a.5.5 0 1 0 .7-.71l-4.44-4.45h6.29a.5.5 0 0 0 0-1h-6.3l4.46-4.45a.5.5 0 1 0-.71-.7L10.5 8.78z"/></>),
};
const SIZES = [16, 20];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TextAsteriskIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
