// Timer10Icon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M7 2.5c0-.28.22-.5.5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5m7.45 1.43c.2-.2.51-.2.7 0l1.42 1.41a.5.5 0 1 1-.7.71l-1.42-1.41a.5.5 0 0 1 0-.71M9 6.5a.5.5 0 0 1 1 0v4a.5.5 0 0 1-1 0zM9.5 18q.77 0 1.5-.16V16.8a6.01 6.01 0 1 1 4.44-6.65q.47-.15.99-.16a7 7 0 1 0-6.93 8m4.5-4.5a2.5 2.5 0 0 1 5 0v3a2.5 2.5 0 0 1-5 0zm2.5-1.5c-.83 0-1.5.67-1.5 1.5v3a1.5 1.5 0 0 0 3 0v-3c0-.83-.67-1.5-1.5-1.5m-3.5-.5a.5.5 0 0 0-.66-.47l-1.5.5a.5.5 0 1 0 .32.94l.84-.28v6.31a.5.5 0 0 0 1 0z"/></>),
  24: (<><path d="M12 5a8.5 8.5 0 0 1 8.38 7.05 4 4 0 0 0-1.52.04 7 7 0 1 0-6.36 8.4v1.5L12 22a8.5 8.5 0 0 1 0-17m.75 7.4V8.66a.75.75 0 0 0-1.5.1v4.59q.32-.53.95-.75zm6.4-7.29.08.06 1.16.97a.75.75 0 0 1-.88 1.21l-.08-.06-1.16-.96a.75.75 0 0 1 .88-1.22m-4.9-2.61a.75.75 0 0 1 .1 1.5h-4.6a.75.75 0 0 1-.1-1.5h4.6m.44 10.64q.3.23.31.61v8.5a.75.75 0 0 1-1.5 0v-7.46l-.51.17a.75.75 0 0 1-.48-1.42l1.5-.5a.8.8 0 0 1 .68.1m1.81 3.11a3.25 3.25 0 0 1 6.5 0v3.5a3.25 3.25 0 0 1-6.5 0zm3.25-1.75c-.97 0-1.75.78-1.75 1.75v3.5a1.75 1.75 0 1 0 3.5 0v-3.5c0-.97-.78-1.75-1.75-1.75"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function Timer10Icon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
