// TimerOffIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M4.96 5.67 2.15 2.85a.5.5 0 1 1 .7-.7l15 15a.5.5 0 0 1-.7.7l-2.32-2.31A6.98 6.98 0 0 1 2.5 11c0-2.13.96-4.05 2.46-5.33m9.16 9.16L10 10.7v.79a.5.5 0 0 1-1 0V9.7L5.67 6.39A5.99 5.99 0 0 0 9.5 17c1.86 0 3.52-.85 4.62-2.17M9 6.5v.38l1 1V6.5a.5.5 0 0 0-1 0m6.5 4.5a6 6 0 0 1-.35 2.03l.77.77q.57-1.3.58-2.8a7 7 0 0 0-9.8-6.42l.77.77A6 6 0 0 1 15.5 11m-8-9a.5.5 0 0 0 0 1h4a.5.5 0 0 0 0-1zm7.66 1.93a.5.5 0 1 0-.71.7l1.41 1.42a.5.5 0 1 0 .71-.7z"/></>),
  24: (<><path d="M3.28 2.22a.75.75 0 1 0-1.06 1.06l4 4a8.5 8.5 0 1 0 12.01 12.01l2.49 2.5a.75.75 0 0 0 1.06-1.07zm13.88 16a7 7 0 1 1-9.89-9.89l3.98 3.98v1.04a.75.75 0 0 0 1.37.33zm-5.72-9.97 1.31 1.32v-.92a.75.75 0 0 0-1.31-.4M19 13.5a7 7 0 0 1-.3 2.02l1.18 1.18q.61-1.5.62-3.2A8.5 8.5 0 0 0 8.8 5.62L9.98 6.8A7 7 0 0 1 19 13.5m.15-8.39.08.06 1.16.97a.75.75 0 0 1-.88 1.21l-.08-.06-1.16-.96a.75.75 0 0 1 .88-1.22m-4.9-2.61a.75.75 0 0 1 .1 1.5h-4.6a.75.75 0 0 1-.1-1.5h4.6"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TimerOffIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
