// ToiletIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
};
const C = {
  16: (<><path d="M13.5 1c.83 0 1.5.67 1.5 1.5v5a2.5 2.5 0 0 1-2 2.45V13a2 2 0 0 1-2 2H5a1 1 0 0 1-.91-1.41l1.1-2.45a5 5 0 0 1-2.1-3.2A1.5 1.5 0 0 1 3.5 5H10V2.5c0-.83.67-1.5 1.5-1.5zM12 10a5 5 0 0 1-5.93 1.61L5 14h6a1 1 0 0 0 1-1zM4.13 8a4 4 0 0 0 6.95 1.55A2.5 2.5 0 0 1 10.05 8zm7.37-6a.5.5 0 0 0-.5.5v5a1.5 1.5 0 0 0 3 0v-5a.5.5 0 0 0-.5-.5zm-8 4a.5.5 0 0 0 0 1H10V6z"/></>),
  20: (<><path d="M16.5 1c.83 0 1.5.67 1.5 1.5v6a2.5 2.5 0 0 1-2 2.45V16a2 2 0 0 1-2 2H6a1 1 0 0 1-.9-1.42l1.28-2.8a6 6 0 0 1-2.33-4.02A2 2 0 0 1 5 6h8V2.5c0-.83.67-1.5 1.5-1.5zM15 12.31a6 6 0 0 1-7.77 2.01L6 17h8a1 1 0 0 0 1-1zM13.5 10H5.1a5 5 0 0 0 9.55.85A2.5 2.5 0 0 1 13.5 10m1-8a.5.5 0 0 0-.5.5v6a1.5 1.5 0 0 0 3 0v-6a.5.5 0 0 0-.5-.5zM5 7a1 1 0 0 0 0 2h8.05a3 3 0 0 1-.05-.5V7z"/></>),
};
const SIZES = [16, 20];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function ToiletIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
