// TreeDeciduousIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
};
const C = {
  20: (<><path d="M10 2a3.5 3.5 0 0 0-3.39 2.61A3.5 3.5 0 0 0 4.05 8.6 3.5 3.5 0 0 0 6 15h2v1.75c0 .69.56 1.25 1.25 1.25h1.5c.69 0 1.25-.56 1.25-1.25V15h2a3.5 3.5 0 0 0 1.95-6.4 3.5 3.5 0 0 0-2.56-3.99A3.5 3.5 0 0 0 10 2m1 13v1.75q-.02.23-.25.25h-1.5a.25.25 0 0 1-.25-.25V15zM7.53 5.11a2.5 2.5 0 0 1 4.94 0c.03.22.2.39.42.42A2.5 2.5 0 0 1 14.9 8.7a.5.5 0 0 0 .25.58A2.5 2.5 0 0 1 14 14H6a2.5 2.5 0 0 1-1.15-4.72.5.5 0 0 0 .25-.58A2.5 2.5 0 0 1 7.1 5.53a.5.5 0 0 0 .42-.42"/></>),
  24: (<><path d="M12 2a4.25 4.25 0 0 0-4 2.82 4.25 4.25 0 0 0-3.37 5.24A4.25 4.25 0 0 0 6.5 18h3v2.25c0 .97.78 1.75 1.75 1.75h1.5c.97 0 1.75-.78 1.75-1.75V18h3q.09 0 .18-.02a4.25 4.25 0 0 0 1.69-7.92A4.26 4.26 0 0 0 16 4.82 4.25 4.25 0 0 0 12 2m1 16v2.25q-.02.23-.25.25h-1.5a.25.25 0 0 1-.25-.25V18zm-6.39-1.5h-.06a2.75 2.75 0 0 1-.73-5.34.75.75 0 0 0 .43-1.02 2.75 2.75 0 0 1 2.37-3.89.75.75 0 0 0 .7-.59 2.75 2.75 0 0 1 5.37 0c.07.33.36.58.7.6a2.75 2.75 0 0 1 2.36 3.88.75.75 0 0 0 .43 1.02 2.75 2.75 0 0 1-.8 5.34z"/></>),
  28: (<><path d="M14 2a5 5 0 0 0-4.79 3.56 5 5 0 0 0-4.02 6.3A5 5 0 0 0 8 21h3v3c0 1.1.9 2 2 2h2a2 2 0 0 0 2-2v-3h3a5 5 0 0 0 2.81-9.14 5 5 0 0 0-4.02-6.3A5 5 0 0 0 14 2m1.5 19v3a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1-.5-.5v-3zM10.55 6.38a3.5 3.5 0 0 1 6.9 0c.06.35.35.6.7.62a3.5 3.5 0 0 1 3.06 4.9c-.16.36 0 .79.35.97A3.5 3.5 0 0 1 20 19.5H8a3.5 3.5 0 0 1-1.56-6.63c.35-.18.5-.6.35-.97q-.29-.65-.29-1.4A3.5 3.5 0 0 1 9.85 7a.75.75 0 0 0 .7-.62"/></>),
};
const SIZES = [20, 24, 28];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TreeDeciduousIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
