// TriangleIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
  28: '0 0 28 28',
  48: '0 0 48 48',
};
const C = {
  16: (<><path d="M6.69 1.78a1.5 1.5 0 0 1 2.63 0l5.5 10A1.5 1.5 0 0 1 13.5 14h-11a1.5 1.5 0 0 1-1.31-2.22zm1.75.48a.5.5 0 0 0-.88 0l-5.5 10a.5.5 0 0 0 .44.74h11a.5.5 0 0 0 .44-.74z"/></>),
  20: (<><path d="M2.5 18a1.5 1.5 0 0 1-1.32-2.2l7.4-14a1.5 1.5 0 0 1 2.64-.02l7.6 14A1.5 1.5 0 0 1 17.5 18zm-.44-1.73a.5.5 0 0 0 .44.73h15a.5.5 0 0 0 .44-.74l-7.6-14a.5.5 0 0 0-.89 0z"/></>),
  24: (<><path d="M2.3 16.63A2.25 2.25 0 0 0 4.25 20h15.5a2.25 2.25 0 0 0 1.94-3.37l-7.74-13.5a2.25 2.25 0 0 0-3.9 0zm1.95 1.87a.75.75 0 0 1-.65-1.12l7.75-13.5a.75.75 0 0 1 1.3 0l7.74 13.5a.75.75 0 0 1-.65 1.12z"/></>),
  28: (<><path d="M12.03 4.16a2.25 2.25 0 0 1 3.94 0l8.96 16.13A2.5 2.5 0 0 1 22.75 24H5.25a2.5 2.5 0 0 1-2.18-3.71zm2.63.73a.75.75 0 0 0-1.31 0L4.38 21a1 1 0 0 0 .87 1.49h17.5a1 1 0 0 0 .87-1.49z"/></>),
  48: (<><path d="M25.76 8.43a1.75 1.75 0 0 0-3.09-.01L6.72 37.92a1.75 1.75 0 0 0 1.54 2.58h31.48c1.32 0 2.17-1.4 1.55-2.56zm-5.29-1.2a4.25 4.25 0 0 1 7.5.04l15.53 29.5A4.25 4.25 0 0 1 39.74 43H8.26a4.25 4.25 0 0 1-3.74-6.27z"/></>),
};
const SIZES = [16, 20, 24, 28, 48];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function TriangleIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
