// VehicleTractorIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M4.3 4.67A2 2 0 0 1 6.27 3h2.46a2 2 0 0 1 1.97 1.67L11.26 8H13V6a.5.5 0 0 1 1 0v2h1a3 3 0 0 1 3 3v1a3 3 0 0 1-.08.7A3 3 0 1 1 13 15h-2.42a5 5 0 1 1-6.94-6.41zM10.84 9H9a5 5 0 0 1 1.9 5h2.27A3 3 0 0 1 17 12.17V11a2 2 0 0 0-2-2zM9.71 4.84A1 1 0 0 0 8.73 4H6.27a1 1 0 0 0-.99.84l-.55 3.32A5 5 0 0 1 6 8h4.24zM6 9a4 4 0 1 0 0 8 4 4 0 0 0 0-8m8 6a2 2 0 1 0 4 0 2 2 0 0 0-4 0"/></>),
  24: (<><path d="M7.02 3c-1.1 0-2.04.8-2.22 1.88l-.82 4.93A6 6 0 1 0 12.66 17h3.38q-.04.24-.04.5a3.5 3.5 0 1 0 6-2.45v-2.8C22 10.45 20.54 9 18.75 9H17.5V6.75a.75.75 0 0 0-1.5 0V9h-2.11l-.7-4.12A2.25 2.25 0 0 0 10.99 3zm5.96 12.5L13 15c0-1.8-.79-3.4-2.03-4.5h7.78c.96 0 1.75.78 1.75 1.75v1.9a3.5 3.5 0 0 0-3.87 1.35zM7.04 9a6 6 0 0 0-1.43.16l.67-4.03a.75.75 0 0 1 .74-.63h3.96c.37 0 .68.27.74.63L12.36 9H7.04m12.46 6.5a2 2 0 1 1 0 4 2 2 0 0 1 0-4m-17-.5a4.5 4.5 0 1 1 9 0 4.5 4.5 0 0 1-9 0"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function VehicleTractorIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
