// VideoSecurityIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M2 5c0-1.1.9-2 2-2h8a2 2 0 0 1 2 2v.9l3.25-1.84a.5.5 0 0 1 .75.44v7a.5.5 0 0 1-.75.44L14 10.1v.9a2 2 0 0 1-2 2h-2v1a4 4 0 0 1-4 4H3.5a.5.5 0 0 1-.5-.5v-2c0-.28.22-.5.5-.5h2c.83 0 1.5-.67 1.5-1.5V13H4a2 2 0 0 1-2-2zm6 8v.5A2.5 2.5 0 0 1 5.5 16H4v1h2a3 3 0 0 0 3-3v-1zm-4-1h8a1 1 0 0 0 1-1V5a1 1 0 0 0-1-1H4a1 1 0 0 0-1 1v6a1 1 0 0 0 1 1m10-4.96v1.91l3 1.7v-5.3z"/></>),
  24: (<><path d="M5.25 3A3.25 3.25 0 0 0 2 6.25v6.5C2 14.55 3.46 16 5.25 16h2.24c-.08.84-.78 1.5-1.65 1.5H3.25a.75.75 0 0 0-.75.75v3c0 .41.34.75.75.75h3A5.75 5.75 0 0 0 12 16.25V16h1.75a3.25 3.25 0 0 0 3.23-2.93l3.88 2.32a.75.75 0 0 0 1.14-.64V4.25a.75.75 0 0 0-1.14-.64l-3.88 2.32A3.25 3.25 0 0 0 13.75 3zM17 7.67l3.5-2.1v7.86l-3.5-2.1zM6.25 20.5H4V19h1.84c1.7 0 3.07-1.33 3.16-3h1.5v.25c0 2.35-1.9 4.25-4.25 4.25M3.5 6.25c0-.97.78-1.75 1.75-1.75h8.5c.97 0 1.75.78 1.75 1.75v6.5c0 .97-.78 1.75-1.75 1.75h-8.5c-.97 0-1.75-.78-1.75-1.75z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function VideoSecurityIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
