// VideoClipOffIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  16: (<><path d="m12.2 12.9 1.95 1.95a.5.5 0 0 0 .7-.7l-13-13a.5.5 0 1 0-.7.7L2.88 3.6A2.5 2.5 0 0 0 2 5.5v5A2.5 2.5 0 0 0 4.5 13h7q.36 0 .7-.1m-.9-.9H4.5A1.5 1.5 0 0 1 3 10.5v-5c0-.49.23-.92.6-1.2l2.9 2.9v2.98c0 .25.27.4.49.27l1.7-1.04zM8.73 6.62l1.68 1.68a.54.54 0 0 0-.17-.76zM13 10.5q0 .18-.04.34l.78.78q.26-.52.26-1.12v-5A2.5 2.5 0 0 0 11.5 3H5.12l1 1h5.38c.83 0 1.5.67 1.5 1.5z"/></>),
  20: (<><path d="M2.85 2.15a.5.5 0 1 0-.7.7l.73.74A2.5 2.5 0 0 0 2 5.5v9A2.5 2.5 0 0 0 4.5 17h11q.36 0 .7-.1l.95.95a.5.5 0 0 0 .7-.7zM15.3 16H4.5A1.5 1.5 0 0 1 3 14.5v-9c0-.49.23-.92.6-1.2L8 8.7v3.95a.5.5 0 0 0 .78.42l2.15-1.43zM9.92 7.8l2.71 2.71.15-.1a.5.5 0 0 0-.01-.83zM17 14.5q0 .18-.04.34l.78.78q.26-.52.26-1.12v-9A2.5 2.5 0 0 0 15.5 3H5.12l1 1h9.38c.83 0 1.5.67 1.5 1.5z"/></>),
  24: (<><path d="M3.28 2.22a.75.75 0 1 0-1.06 1.06l.7.7A3.2 3.2 0 0 0 2 6.25v11.5C2 19.55 3.46 21 5.25 21h13.5q.54 0 1.02-.16l.95.94a.75.75 0 0 0 1.06-1.06zM18.44 19.5H5.25c-.97 0-1.75-.78-1.75-1.75V6.25c0-.47.18-.9.48-1.2L9 10.05v4.69a1 1 0 0 0 1.48.88l2.64-1.45zm-5.57-9.81 2.92 2.92a1 1 0 0 0-.3-1.49zm7.63-3.44v11.07l1.36 1.36q.14-.44.14-.93V6.25C22 4.45 20.54 3 18.75 3H6.18l1.5 1.5h11.07c.97 0 1.75.78 1.75 1.75"/></>),
};
const SIZES = [16, 20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function VideoClipOffIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
