// Video360OffIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
};
const C = {
  20: (<><path d="M6 11a1 1 0 1 0 0-2 1 1 0 0 0 0 2M2.85 2.15a.5.5 0 1 0-.7.7l1.18 1.19A1.7 1.7 0 0 0 2 5.7v8.6a1.7 1.7 0 0 0 1.97 1.68c3.7-.6 7.46-.64 11.17-.13l2 2a.5.5 0 0 0 .71-.7l-1.18-1.19-6.12-6.12-1.39-1.39L6.01 5.3 4.86 4.15zM13 13.7v.9l-1-.06V12.7zM10.3 11H9a1 1 0 0 0-1 1v2.55l-1 .06V12H5a1 1 0 0 0-1 1v1.96l-.19.03A.7.7 0 0 1 3 14.3V5.7a.7.7 0 0 1 .81-.7l.58.1zm3.82 1L16 13.88V13a1 1 0 0 0-1-1zm2.73 2.73.71.71q.42-.46.44-1.14V5.7a1.7 1.7 0 0 0-1.97-1.68q-4.77.77-9.57.32l1.09 1.09q4.34.27 8.64-.42a.7.7 0 0 1 .81.69v8.6a.7.7 0 0 1-.15.43M14 11a1 1 0 1 0 0-2 1 1 0 0 0 0 2"/></>),
};
const SIZES = [20];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function Video360OffIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
