// VideoPersonStarIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M2 5.5C2 4.67 2.67 4 3.5 4h13c.83 0 1.5.67 1.5 1.5v4.76a6 6 0 0 0-1-.66V5.5a.5.5 0 0 0-.5-.5h-13a.5.5 0 0 0-.5.5v9c0 .28.22.5.5.5H6v-1.5c0-.83.67-1.5 1.5-1.5h2.1q-.24.48-.4 1H7.5a.5.5 0 0 0-.5.5V15h2.02q.05.51.19 1H3.5A1.5 1.5 0 0 1 2 14.5zm10.5 3q0 .51-.19.95Q11.1 10 10.27 11L10 11a2.5 2.5 0 1 1 2.5-2.5M10 10a1.5 1.5 0 1 0 0-3 1.5 1.5 0 0 0 0 3m9 4.5a4.5 4.5 0 1 1-9 0 4.5 4.5 0 0 1 9 0m-4.02-2.64a.5.5 0 0 0-.96 0l-.47 1.53H12c-.48 0-.69.65-.3.95l1.26.94-.48 1.53c-.15.49.38.89.77.59l1.25-.95 1.25.95c.4.3.92-.1.77-.59l-.48-1.53 1.25-.94c.4-.3.2-.95-.3-.95h-1.54z"/></>),
  24: (<><path d="M19.75 4C20.99 4 22 5 22 6.25v6.56a7 7 0 0 0-1.5-1.08V6.25a.75.75 0 0 0-.75-.75H4.25a.75.75 0 0 0-.75.75v11.5c0 .42.34.75.75.75H7v-2.75c0-.92.7-1.67 1.6-1.74l.15-.01h3.27q-.45.7-.7 1.5H8.74a.25.25 0 0 0-.24.2l-.01.05v2.75h2.58q.12.8.42 1.5H4.25C3.01 20 2 19 2 17.75V6.25C2 5.01 3 4 4.25 4zM12 7a3 3 0 1 1 0 6 3 3 0 0 1 0-6m0 1.5a1.5 1.5 0 1 0 0 3 1.5 1.5 0 0 0 0-3m11 9a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0m-4.94-3.08a.58.58 0 0 0-1.12 0l-.55 1.79h-1.8c-.57 0-.8.75-.35 1.1l1.46 1.1-.56 1.79c-.17.56.44 1.03.9.68l1.46-1.1 1.46 1.1c.46.35 1.07-.12.9-.68l-.56-1.79 1.46-1.1c.46-.35.22-1.1-.35-1.1h-1.8z"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function VideoPersonStarIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
