// VoicemailArrowForwardIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  16: '0 0 16 16',
  20: '0 0 20 20',
};
const C = {
  16: (<><path d="M6.33 5q.17.35.17.75A1.75 1.75 0 1 1 4.75 4h4.5c.7 0 1.3.41 1.59 1.01a6 6 0 0 0-1.26.07.75.75 0 0 0-.95.25q-.6.21-1.12.56A2 2 0 0 1 7.67 5zM4 5.75a.75.75 0 1 0 1.5 0 .75.75 0 0 0-1.5 0m8-3.25v2.7q.52.16 1 .4V2.5c0-.83-.67-1.5-1.5-1.5h-9C1.67 1 1 1.67 1 2.5V9c0 .83.67 1.5 1.5 1.5H5q0-.52.1-1H2.5A.5.5 0 0 1 2 9V2.5c0-.28.22-.5.5-.5h9c.28 0 .5.22.5.5M10.5 15a4.5 4.5 0 1 1 0-9 4.5 4.5 0 0 1 0 9m.9-6.4.9.9h-1.55A2.75 2.75 0 0 0 8 12.25v.25a.5.5 0 0 0 1 0v-.25c0-.97.78-1.75 1.75-1.75h1.54l-.9.9a.5.5 0 0 0 .71.7l1.76-1.75a.5.5 0 0 0 0-.7L12.1 7.9a.5.5 0 0 0-.7.7"/></>),
  20: (<><path d="M8.73 9A2 2 0 1 1 7 8h6a2 2 0 0 1 1.74 1 6 6 0 0 0-1.3.1 1 1 0 0 0-1.33.45q-.6.28-1.1.7A2 2 0 0 1 11.27 9zM6 10a1 1 0 1 0 2 0 1 1 0 0 0-2 0m11-4v3.6q.54.27 1 .66V6a2 2 0 0 0-2-2H4a2 2 0 0 0-2 2v8c0 1.1.9 2 2 2h5.2q-.13-.49-.18-1H4a1 1 0 0 1-1-1V6a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1m-7 8.5a4.5 4.5 0 1 0 9 0 4.5 4.5 0 0 0-9 0m5.4-2.6c.2-.2.5-.2.7 0l1.75 1.75a.5.5 0 0 1 0 .7L16.1 16.1a.5.5 0 0 1-.7-.7l.9-.9h-1.55c-.97 0-1.75.78-1.75 1.75v.25a.5.5 0 0 1-1 0v-.25a2.75 2.75 0 0 1 2.75-2.75h1.54l-.9-.9a.5.5 0 0 1 0-.7"/></>),
};
const SIZES = [16, 20];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function VoicemailArrowForwardIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
