// Wifi2Icon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
  24: '0 0 24 24',
};
const C = {
  20: (<><path d="M14.6 9.36q.71.72 1.2 1.65a.5.5 0 1 1-.9.46q-.4-.8-1.01-1.4a5.45 5.45 0 0 0-8.72 1.38.5.5 0 0 1-.89-.45q.45-.9 1.2-1.64a6.45 6.45 0 0 1 9.12 0m-1.71 2.5q.53.53.85 1.25a.5.5 0 1 1-.92.4 3.03 3.03 0 0 0-5.56-.01.5.5 0 1 1-.92-.4q.3-.72.84-1.25a4.03 4.03 0 0 1 5.7 0m-1.93 1.93a1.3 1.3 0 1 1-1.83 1.83 1.3 1.3 0 0 1 1.83-1.83"/></>),
  24: (<><path d="M17.74 10.75q.9.9 1.5 2.07a.75.75 0 1 1-1.34.68 6.56 6.56 0 0 0-11.71-.02.75.75 0 1 1-1.34-.67q.57-1.14 1.5-2.06a8.06 8.06 0 0 1 11.4 0m-2.1 3.07q.68.7 1.08 1.58a.75.75 0 1 1-1.38.6A3.6 3.6 0 0 0 8.75 16a.75.75 0 1 1-1.37-.6q.4-.89 1.06-1.57a5.1 5.1 0 0 1 7.2 0m-2.58 2.62a1.5 1.5 0 1 1-2.12 2.12 1.5 1.5 0 0 1 2.12-2.12"/></>),
};
const SIZES = [20, 24];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function Wifi2Icon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
