// WindowHeaderHorizontalOffIcon — Microsoft Fluent System Icons (Regular theme).
// Auto-generated by scripts/generate-fluent-icons.mjs — do not edit by hand.
// Source: @fluentui/svg-icons (MIT). See ./README.md.
import React from 'react';

const V = {
  20: '0 0 20 20',
};
const C = {
  20: (<><path d="M2.85 2.15a.5.5 0 1 0-.7.7L3.4 4.12q-.4.6-.41 1.38v9A2.5 2.5 0 0 0 5.5 17h9q.77-.01 1.38-.41l1.27 1.26a.5.5 0 0 0 .7-.7zm12.3 13.7q-.3.15-.65.15h-9A1.5 1.5 0 0 1 4 14.5V7h2.3zM16 7v6.88l.98.97.02-.35v-9A2.5 2.5 0 0 0 14.5 3h-9q-.18 0-.35.02L9.12 7z"/></>),
};
const SIZES = [20];

function pick(size) {
  if (C[size]) return size;
  let best = SIZES[0], bd = Infinity;
  for (const s of SIZES) { const d = Math.abs(s - size); if (d < bd) { bd = d; best = s; } }
  return best;
}

export function WindowHeaderHorizontalOffIcon({ size = 20, ...props }) {
  const k = pick(size);
  return (
    <svg width={size} height={size} viewBox={V[k]} fill="currentColor" xmlns="http://www.w3.org/2000/svg" aria-hidden="true" {...props}>{C[k]}</svg>
  );
}
